// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: recursos.proto

package recursos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RecursosService_CrearRepositorio_FullMethodName          = "/recursos.RecursosService/CrearRepositorio"
	RecursosService_AgregarArchivo_FullMethodName            = "/recursos.RecursosService/AgregarArchivo"
	RecursosService_ActualizarVersionArchivo_FullMethodName  = "/recursos.RecursosService/ActualizarVersionArchivo"
	RecursosService_ActualizarTag_FullMethodName             = "/recursos.RecursosService/ActualizarTag"
	RecursosService_EliminarArchivo_FullMethodName           = "/recursos.RecursosService/EliminarArchivo"
	RecursosService_ConsultarRepositorio_FullMethodName      = "/recursos.RecursosService/ConsultarRepositorio"
	RecursosService_ConsultarVersionesArchivo_FullMethodName = "/recursos.RecursosService/ConsultarVersionesArchivo"
	RecursosService_ConsultarVersionArchivo_FullMethodName   = "/recursos.RecursosService/ConsultarVersionArchivo"
	RecursosService_ConsultarApunte_FullMethodName           = "/recursos.RecursosService/ConsultarApunte"
	RecursosService_CrearApunte_FullMethodName               = "/recursos.RecursosService/CrearApunte"
	RecursosService_ActualizarApunte_FullMethodName          = "/recursos.RecursosService/ActualizarApunte"
	RecursosService_AgregarMarcadorTiempo_FullMethodName     = "/recursos.RecursosService/AgregarMarcadorTiempo"
	RecursosService_EliminarMarcadorTiempo_FullMethodName    = "/recursos.RecursosService/EliminarMarcadorTiempo"
	RecursosService_ConsultarDudasClase_FullMethodName       = "/recursos.RecursosService/ConsultarDudasClase"
	RecursosService_CrearDuda_FullMethodName                 = "/recursos.RecursosService/CrearDuda"
	RecursosService_CrearRespuesta_FullMethodName            = "/recursos.RecursosService/CrearRespuesta"
	RecursosService_MarcarRespuesta_FullMethodName           = "/recursos.RecursosService/MarcarRespuesta"
)

// RecursosServiceClient is the client API for RecursosService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ──────────────────────────────────────────────
// Servicio de repositorio de recursos
// ──────────────────────────────────────────────
type RecursosServiceClient interface {
	// Repositorio
	CrearRepositorio(ctx context.Context, in *CrearRepositorioRequest, opts ...grpc.CallOption) (*CrearRepositorioResponse, error)
	// Archivos
	AgregarArchivo(ctx context.Context, in *AgregarArchivoRequest, opts ...grpc.CallOption) (*AgregarArchivoResponse, error)
	ActualizarVersionArchivo(ctx context.Context, in *ActualizarVersionArchivoRequest, opts ...grpc.CallOption) (*ActualizarVersionArchivoResponse, error)
	ActualizarTag(ctx context.Context, in *ActualizarTagRequest, opts ...grpc.CallOption) (*ActualizarTagResponse, error)
	EliminarArchivo(ctx context.Context, in *EliminarArchivoRequest, opts ...grpc.CallOption) (*EliminarArchivoResponse, error)
	// Consultas
	ConsultarRepositorio(ctx context.Context, in *ConsultarRepositorioRequest, opts ...grpc.CallOption) (*ConsultarRepositorioResponse, error)
	ConsultarVersionesArchivo(ctx context.Context, in *ConsultarVersionesArchivoRequest, opts ...grpc.CallOption) (*ConsultarVersionesArchivoResponse, error)
	ConsultarVersionArchivo(ctx context.Context, in *ConsultarVersionArchivoRequest, opts ...grpc.CallOption) (*ConsultarVersionArchivoResponse, error)
	// Apuntes
	ConsultarApunte(ctx context.Context, in *ConsultarApunteRequest, opts ...grpc.CallOption) (*ConsultarApunteResponse, error)
	CrearApunte(ctx context.Context, in *CrearApunteRequest, opts ...grpc.CallOption) (*CrearApunteResponse, error)
	ActualizarApunte(ctx context.Context, in *ActualizarApunteRequest, opts ...grpc.CallOption) (*ActualizarApunteResponse, error)
	AgregarMarcadorTiempo(ctx context.Context, in *AgregarMarcadorTiempoRequest, opts ...grpc.CallOption) (*AgregarMarcadorTiempoResponse, error)
	EliminarMarcadorTiempo(ctx context.Context, in *EliminarMarcadorTiempoRequest, opts ...grpc.CallOption) (*EliminarMarcadorTiempoResponse, error)
	// Dudas y respuestas
	ConsultarDudasClase(ctx context.Context, in *ConsultarDudasClaseRequest, opts ...grpc.CallOption) (*ConsultarDudasClaseResponse, error)
	CrearDuda(ctx context.Context, in *CrearDudaRequest, opts ...grpc.CallOption) (*CrearDudaResponse, error)
	CrearRespuesta(ctx context.Context, in *CrearRespuestaRequest, opts ...grpc.CallOption) (*CrearRespuestaResponse, error)
	MarcarRespuesta(ctx context.Context, in *MarcarRespuestaRequest, opts ...grpc.CallOption) (*MarcarRespuestaResponse, error)
}

type recursosServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRecursosServiceClient(cc grpc.ClientConnInterface) RecursosServiceClient {
	return &recursosServiceClient{cc}
}

func (c *recursosServiceClient) CrearRepositorio(ctx context.Context, in *CrearRepositorioRequest, opts ...grpc.CallOption) (*CrearRepositorioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrearRepositorioResponse)
	err := c.cc.Invoke(ctx, RecursosService_CrearRepositorio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recursosServiceClient) AgregarArchivo(ctx context.Context, in *AgregarArchivoRequest, opts ...grpc.CallOption) (*AgregarArchivoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgregarArchivoResponse)
	err := c.cc.Invoke(ctx, RecursosService_AgregarArchivo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recursosServiceClient) ActualizarVersionArchivo(ctx context.Context, in *ActualizarVersionArchivoRequest, opts ...grpc.CallOption) (*ActualizarVersionArchivoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActualizarVersionArchivoResponse)
	err := c.cc.Invoke(ctx, RecursosService_ActualizarVersionArchivo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recursosServiceClient) ActualizarTag(ctx context.Context, in *ActualizarTagRequest, opts ...grpc.CallOption) (*ActualizarTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActualizarTagResponse)
	err := c.cc.Invoke(ctx, RecursosService_ActualizarTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recursosServiceClient) EliminarArchivo(ctx context.Context, in *EliminarArchivoRequest, opts ...grpc.CallOption) (*EliminarArchivoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EliminarArchivoResponse)
	err := c.cc.Invoke(ctx, RecursosService_EliminarArchivo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recursosServiceClient) ConsultarRepositorio(ctx context.Context, in *ConsultarRepositorioRequest, opts ...grpc.CallOption) (*ConsultarRepositorioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarRepositorioResponse)
	err := c.cc.Invoke(ctx, RecursosService_ConsultarRepositorio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recursosServiceClient) ConsultarVersionesArchivo(ctx context.Context, in *ConsultarVersionesArchivoRequest, opts ...grpc.CallOption) (*ConsultarVersionesArchivoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarVersionesArchivoResponse)
	err := c.cc.Invoke(ctx, RecursosService_ConsultarVersionesArchivo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recursosServiceClient) ConsultarVersionArchivo(ctx context.Context, in *ConsultarVersionArchivoRequest, opts ...grpc.CallOption) (*ConsultarVersionArchivoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarVersionArchivoResponse)
	err := c.cc.Invoke(ctx, RecursosService_ConsultarVersionArchivo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recursosServiceClient) ConsultarApunte(ctx context.Context, in *ConsultarApunteRequest, opts ...grpc.CallOption) (*ConsultarApunteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarApunteResponse)
	err := c.cc.Invoke(ctx, RecursosService_ConsultarApunte_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recursosServiceClient) CrearApunte(ctx context.Context, in *CrearApunteRequest, opts ...grpc.CallOption) (*CrearApunteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrearApunteResponse)
	err := c.cc.Invoke(ctx, RecursosService_CrearApunte_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recursosServiceClient) ActualizarApunte(ctx context.Context, in *ActualizarApunteRequest, opts ...grpc.CallOption) (*ActualizarApunteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActualizarApunteResponse)
	err := c.cc.Invoke(ctx, RecursosService_ActualizarApunte_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recursosServiceClient) AgregarMarcadorTiempo(ctx context.Context, in *AgregarMarcadorTiempoRequest, opts ...grpc.CallOption) (*AgregarMarcadorTiempoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgregarMarcadorTiempoResponse)
	err := c.cc.Invoke(ctx, RecursosService_AgregarMarcadorTiempo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recursosServiceClient) EliminarMarcadorTiempo(ctx context.Context, in *EliminarMarcadorTiempoRequest, opts ...grpc.CallOption) (*EliminarMarcadorTiempoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EliminarMarcadorTiempoResponse)
	err := c.cc.Invoke(ctx, RecursosService_EliminarMarcadorTiempo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recursosServiceClient) ConsultarDudasClase(ctx context.Context, in *ConsultarDudasClaseRequest, opts ...grpc.CallOption) (*ConsultarDudasClaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarDudasClaseResponse)
	err := c.cc.Invoke(ctx, RecursosService_ConsultarDudasClase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recursosServiceClient) CrearDuda(ctx context.Context, in *CrearDudaRequest, opts ...grpc.CallOption) (*CrearDudaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrearDudaResponse)
	err := c.cc.Invoke(ctx, RecursosService_CrearDuda_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recursosServiceClient) CrearRespuesta(ctx context.Context, in *CrearRespuestaRequest, opts ...grpc.CallOption) (*CrearRespuestaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrearRespuestaResponse)
	err := c.cc.Invoke(ctx, RecursosService_CrearRespuesta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *recursosServiceClient) MarcarRespuesta(ctx context.Context, in *MarcarRespuestaRequest, opts ...grpc.CallOption) (*MarcarRespuestaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarcarRespuestaResponse)
	err := c.cc.Invoke(ctx, RecursosService_MarcarRespuesta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecursosServiceServer is the server API for RecursosService service.
// All implementations must embed UnimplementedRecursosServiceServer
// for forward compatibility.
//
// ──────────────────────────────────────────────
// Servicio de repositorio de recursos
// ──────────────────────────────────────────────
type RecursosServiceServer interface {
	// Repositorio
	CrearRepositorio(context.Context, *CrearRepositorioRequest) (*CrearRepositorioResponse, error)
	// Archivos
	AgregarArchivo(context.Context, *AgregarArchivoRequest) (*AgregarArchivoResponse, error)
	ActualizarVersionArchivo(context.Context, *ActualizarVersionArchivoRequest) (*ActualizarVersionArchivoResponse, error)
	ActualizarTag(context.Context, *ActualizarTagRequest) (*ActualizarTagResponse, error)
	EliminarArchivo(context.Context, *EliminarArchivoRequest) (*EliminarArchivoResponse, error)
	// Consultas
	ConsultarRepositorio(context.Context, *ConsultarRepositorioRequest) (*ConsultarRepositorioResponse, error)
	ConsultarVersionesArchivo(context.Context, *ConsultarVersionesArchivoRequest) (*ConsultarVersionesArchivoResponse, error)
	ConsultarVersionArchivo(context.Context, *ConsultarVersionArchivoRequest) (*ConsultarVersionArchivoResponse, error)
	// Apuntes
	ConsultarApunte(context.Context, *ConsultarApunteRequest) (*ConsultarApunteResponse, error)
	CrearApunte(context.Context, *CrearApunteRequest) (*CrearApunteResponse, error)
	ActualizarApunte(context.Context, *ActualizarApunteRequest) (*ActualizarApunteResponse, error)
	AgregarMarcadorTiempo(context.Context, *AgregarMarcadorTiempoRequest) (*AgregarMarcadorTiempoResponse, error)
	EliminarMarcadorTiempo(context.Context, *EliminarMarcadorTiempoRequest) (*EliminarMarcadorTiempoResponse, error)
	// Dudas y respuestas
	ConsultarDudasClase(context.Context, *ConsultarDudasClaseRequest) (*ConsultarDudasClaseResponse, error)
	CrearDuda(context.Context, *CrearDudaRequest) (*CrearDudaResponse, error)
	CrearRespuesta(context.Context, *CrearRespuestaRequest) (*CrearRespuestaResponse, error)
	MarcarRespuesta(context.Context, *MarcarRespuestaRequest) (*MarcarRespuestaResponse, error)
	mustEmbedUnimplementedRecursosServiceServer()
}

// UnimplementedRecursosServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRecursosServiceServer struct{}

func (UnimplementedRecursosServiceServer) CrearRepositorio(context.Context, *CrearRepositorioRequest) (*CrearRepositorioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearRepositorio not implemented")
}
func (UnimplementedRecursosServiceServer) AgregarArchivo(context.Context, *AgregarArchivoRequest) (*AgregarArchivoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AgregarArchivo not implemented")
}
func (UnimplementedRecursosServiceServer) ActualizarVersionArchivo(context.Context, *ActualizarVersionArchivoRequest) (*ActualizarVersionArchivoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActualizarVersionArchivo not implemented")
}
func (UnimplementedRecursosServiceServer) ActualizarTag(context.Context, *ActualizarTagRequest) (*ActualizarTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActualizarTag not implemented")
}
func (UnimplementedRecursosServiceServer) EliminarArchivo(context.Context, *EliminarArchivoRequest) (*EliminarArchivoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EliminarArchivo not implemented")
}
func (UnimplementedRecursosServiceServer) ConsultarRepositorio(context.Context, *ConsultarRepositorioRequest) (*ConsultarRepositorioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarRepositorio not implemented")
}
func (UnimplementedRecursosServiceServer) ConsultarVersionesArchivo(context.Context, *ConsultarVersionesArchivoRequest) (*ConsultarVersionesArchivoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarVersionesArchivo not implemented")
}
func (UnimplementedRecursosServiceServer) ConsultarVersionArchivo(context.Context, *ConsultarVersionArchivoRequest) (*ConsultarVersionArchivoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarVersionArchivo not implemented")
}
func (UnimplementedRecursosServiceServer) ConsultarApunte(context.Context, *ConsultarApunteRequest) (*ConsultarApunteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarApunte not implemented")
}
func (UnimplementedRecursosServiceServer) CrearApunte(context.Context, *CrearApunteRequest) (*CrearApunteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearApunte not implemented")
}
func (UnimplementedRecursosServiceServer) ActualizarApunte(context.Context, *ActualizarApunteRequest) (*ActualizarApunteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActualizarApunte not implemented")
}
func (UnimplementedRecursosServiceServer) AgregarMarcadorTiempo(context.Context, *AgregarMarcadorTiempoRequest) (*AgregarMarcadorTiempoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AgregarMarcadorTiempo not implemented")
}
func (UnimplementedRecursosServiceServer) EliminarMarcadorTiempo(context.Context, *EliminarMarcadorTiempoRequest) (*EliminarMarcadorTiempoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EliminarMarcadorTiempo not implemented")
}
func (UnimplementedRecursosServiceServer) ConsultarDudasClase(context.Context, *ConsultarDudasClaseRequest) (*ConsultarDudasClaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarDudasClase not implemented")
}
func (UnimplementedRecursosServiceServer) CrearDuda(context.Context, *CrearDudaRequest) (*CrearDudaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearDuda not implemented")
}
func (UnimplementedRecursosServiceServer) CrearRespuesta(context.Context, *CrearRespuestaRequest) (*CrearRespuestaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearRespuesta not implemented")
}
func (UnimplementedRecursosServiceServer) MarcarRespuesta(context.Context, *MarcarRespuestaRequest) (*MarcarRespuestaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarcarRespuesta not implemented")
}
func (UnimplementedRecursosServiceServer) mustEmbedUnimplementedRecursosServiceServer() {}
func (UnimplementedRecursosServiceServer) testEmbeddedByValue()                         {}

// UnsafeRecursosServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RecursosServiceServer will
// result in compilation errors.
type UnsafeRecursosServiceServer interface {
	mustEmbedUnimplementedRecursosServiceServer()
}

func RegisterRecursosServiceServer(s grpc.ServiceRegistrar, srv RecursosServiceServer) {
	// If the following call panics, it indicates UnimplementedRecursosServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RecursosService_ServiceDesc, srv)
}

func _RecursosService_CrearRepositorio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearRepositorioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecursosServiceServer).CrearRepositorio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecursosService_CrearRepositorio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecursosServiceServer).CrearRepositorio(ctx, req.(*CrearRepositorioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecursosService_AgregarArchivo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgregarArchivoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecursosServiceServer).AgregarArchivo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecursosService_AgregarArchivo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecursosServiceServer).AgregarArchivo(ctx, req.(*AgregarArchivoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecursosService_ActualizarVersionArchivo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActualizarVersionArchivoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecursosServiceServer).ActualizarVersionArchivo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecursosService_ActualizarVersionArchivo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecursosServiceServer).ActualizarVersionArchivo(ctx, req.(*ActualizarVersionArchivoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecursosService_ActualizarTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActualizarTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecursosServiceServer).ActualizarTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecursosService_ActualizarTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecursosServiceServer).ActualizarTag(ctx, req.(*ActualizarTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecursosService_EliminarArchivo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EliminarArchivoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecursosServiceServer).EliminarArchivo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecursosService_EliminarArchivo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecursosServiceServer).EliminarArchivo(ctx, req.(*EliminarArchivoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecursosService_ConsultarRepositorio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarRepositorioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecursosServiceServer).ConsultarRepositorio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecursosService_ConsultarRepositorio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecursosServiceServer).ConsultarRepositorio(ctx, req.(*ConsultarRepositorioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecursosService_ConsultarVersionesArchivo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarVersionesArchivoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecursosServiceServer).ConsultarVersionesArchivo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecursosService_ConsultarVersionesArchivo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecursosServiceServer).ConsultarVersionesArchivo(ctx, req.(*ConsultarVersionesArchivoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecursosService_ConsultarVersionArchivo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarVersionArchivoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecursosServiceServer).ConsultarVersionArchivo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecursosService_ConsultarVersionArchivo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecursosServiceServer).ConsultarVersionArchivo(ctx, req.(*ConsultarVersionArchivoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecursosService_ConsultarApunte_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarApunteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecursosServiceServer).ConsultarApunte(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecursosService_ConsultarApunte_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecursosServiceServer).ConsultarApunte(ctx, req.(*ConsultarApunteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecursosService_CrearApunte_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearApunteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecursosServiceServer).CrearApunte(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecursosService_CrearApunte_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecursosServiceServer).CrearApunte(ctx, req.(*CrearApunteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecursosService_ActualizarApunte_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActualizarApunteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecursosServiceServer).ActualizarApunte(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecursosService_ActualizarApunte_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecursosServiceServer).ActualizarApunte(ctx, req.(*ActualizarApunteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecursosService_AgregarMarcadorTiempo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgregarMarcadorTiempoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecursosServiceServer).AgregarMarcadorTiempo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecursosService_AgregarMarcadorTiempo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecursosServiceServer).AgregarMarcadorTiempo(ctx, req.(*AgregarMarcadorTiempoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecursosService_EliminarMarcadorTiempo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EliminarMarcadorTiempoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecursosServiceServer).EliminarMarcadorTiempo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecursosService_EliminarMarcadorTiempo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecursosServiceServer).EliminarMarcadorTiempo(ctx, req.(*EliminarMarcadorTiempoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecursosService_ConsultarDudasClase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarDudasClaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecursosServiceServer).ConsultarDudasClase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecursosService_ConsultarDudasClase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecursosServiceServer).ConsultarDudasClase(ctx, req.(*ConsultarDudasClaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecursosService_CrearDuda_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearDudaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecursosServiceServer).CrearDuda(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecursosService_CrearDuda_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecursosServiceServer).CrearDuda(ctx, req.(*CrearDudaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecursosService_CrearRespuesta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearRespuestaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecursosServiceServer).CrearRespuesta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecursosService_CrearRespuesta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecursosServiceServer).CrearRespuesta(ctx, req.(*CrearRespuestaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RecursosService_MarcarRespuesta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarcarRespuestaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecursosServiceServer).MarcarRespuesta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RecursosService_MarcarRespuesta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecursosServiceServer).MarcarRespuesta(ctx, req.(*MarcarRespuestaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RecursosService_ServiceDesc is the grpc.ServiceDesc for RecursosService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RecursosService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "recursos.RecursosService",
	HandlerType: (*RecursosServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CrearRepositorio",
			Handler:    _RecursosService_CrearRepositorio_Handler,
		},
		{
			MethodName: "AgregarArchivo",
			Handler:    _RecursosService_AgregarArchivo_Handler,
		},
		{
			MethodName: "ActualizarVersionArchivo",
			Handler:    _RecursosService_ActualizarVersionArchivo_Handler,
		},
		{
			MethodName: "ActualizarTag",
			Handler:    _RecursosService_ActualizarTag_Handler,
		},
		{
			MethodName: "EliminarArchivo",
			Handler:    _RecursosService_EliminarArchivo_Handler,
		},
		{
			MethodName: "ConsultarRepositorio",
			Handler:    _RecursosService_ConsultarRepositorio_Handler,
		},
		{
			MethodName: "ConsultarVersionesArchivo",
			Handler:    _RecursosService_ConsultarVersionesArchivo_Handler,
		},
		{
			MethodName: "ConsultarVersionArchivo",
			Handler:    _RecursosService_ConsultarVersionArchivo_Handler,
		},
		{
			MethodName: "ConsultarApunte",
			Handler:    _RecursosService_ConsultarApunte_Handler,
		},
		{
			MethodName: "CrearApunte",
			Handler:    _RecursosService_CrearApunte_Handler,
		},
		{
			MethodName: "ActualizarApunte",
			Handler:    _RecursosService_ActualizarApunte_Handler,
		},
		{
			MethodName: "AgregarMarcadorTiempo",
			Handler:    _RecursosService_AgregarMarcadorTiempo_Handler,
		},
		{
			MethodName: "EliminarMarcadorTiempo",
			Handler:    _RecursosService_EliminarMarcadorTiempo_Handler,
		},
		{
			MethodName: "ConsultarDudasClase",
			Handler:    _RecursosService_ConsultarDudasClase_Handler,
		},
		{
			MethodName: "CrearDuda",
			Handler:    _RecursosService_CrearDuda_Handler,
		},
		{
			MethodName: "CrearRespuesta",
			Handler:    _RecursosService_CrearRespuesta_Handler,
		},
		{
			MethodName: "MarcarRespuesta",
			Handler:    _RecursosService_MarcarRespuesta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "recursos.proto",
}
