// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: recursos.proto

package recursos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ──────────────────────────────────────────────
// Mensajes de dominio
// ──────────────────────────────────────────────
type ArchivoRepositorio struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdArchivo     int32                  `protobuf:"varint,1,opt,name=id_archivo,json=idArchivo,proto3" json:"id_archivo,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchivoRepositorio) Reset() {
	*x = ArchivoRepositorio{}
	mi := &file_recursos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchivoRepositorio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchivoRepositorio) ProtoMessage() {}

func (x *ArchivoRepositorio) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchivoRepositorio.ProtoReflect.Descriptor instead.
func (*ArchivoRepositorio) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{0}
}

func (x *ArchivoRepositorio) GetIdArchivo() int32 {
	if x != nil {
		return x.IdArchivo
	}
	return 0
}

func (x *ArchivoRepositorio) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type VersionArchivo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdVersion     int32                  `protobuf:"varint,1,opt,name=id_version,json=idVersion,proto3" json:"id_version,omitempty"`
	IdArchivo     int32                  `protobuf:"varint,2,opt,name=id_archivo,json=idArchivo,proto3" json:"id_archivo,omitempty"`
	Link          string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	Tag           string                 `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	FechaCreacion string                 `protobuf:"bytes,5,opt,name=fecha_creacion,json=fechaCreacion,proto3" json:"fecha_creacion,omitempty"`
	Hash          string                 `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	Latest        bool                   `protobuf:"varint,7,opt,name=latest,proto3" json:"latest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionArchivo) Reset() {
	*x = VersionArchivo{}
	mi := &file_recursos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionArchivo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionArchivo) ProtoMessage() {}

func (x *VersionArchivo) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionArchivo.ProtoReflect.Descriptor instead.
func (*VersionArchivo) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{1}
}

func (x *VersionArchivo) GetIdVersion() int32 {
	if x != nil {
		return x.IdVersion
	}
	return 0
}

func (x *VersionArchivo) GetIdArchivo() int32 {
	if x != nil {
		return x.IdArchivo
	}
	return 0
}

func (x *VersionArchivo) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *VersionArchivo) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *VersionArchivo) GetFechaCreacion() string {
	if x != nil {
		return x.FechaCreacion
	}
	return ""
}

func (x *VersionArchivo) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *VersionArchivo) GetLatest() bool {
	if x != nil {
		return x.Latest
	}
	return false
}

type RepositorioInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdRepositorio int32                  `protobuf:"varint,1,opt,name=id_repositorio,json=idRepositorio,proto3" json:"id_repositorio,omitempty"`
	IdClase       int32                  `protobuf:"varint,2,opt,name=id_clase,json=idClase,proto3" json:"id_clase,omitempty"`
	Nombre        string                 `protobuf:"bytes,3,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Archivos      []*ArchivoRepositorio  `protobuf:"bytes,4,rep,name=archivos,proto3" json:"archivos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RepositorioInfo) Reset() {
	*x = RepositorioInfo{}
	mi := &file_recursos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RepositorioInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RepositorioInfo) ProtoMessage() {}

func (x *RepositorioInfo) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RepositorioInfo.ProtoReflect.Descriptor instead.
func (*RepositorioInfo) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{2}
}

func (x *RepositorioInfo) GetIdRepositorio() int32 {
	if x != nil {
		return x.IdRepositorio
	}
	return 0
}

func (x *RepositorioInfo) GetIdClase() int32 {
	if x != nil {
		return x.IdClase
	}
	return 0
}

func (x *RepositorioInfo) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *RepositorioInfo) GetArchivos() []*ArchivoRepositorio {
	if x != nil {
		return x.Archivos
	}
	return nil
}

// ──────────────────────────────────────────────
// CrearRepositorio
// ──────────────────────────────────────────────
type CrearRepositorioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdClase       int32                  `protobuf:"varint,1,opt,name=id_clase,json=idClase,proto3" json:"id_clase,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearRepositorioRequest) Reset() {
	*x = CrearRepositorioRequest{}
	mi := &file_recursos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearRepositorioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearRepositorioRequest) ProtoMessage() {}

func (x *CrearRepositorioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearRepositorioRequest.ProtoReflect.Descriptor instead.
func (*CrearRepositorioRequest) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{3}
}

func (x *CrearRepositorioRequest) GetIdClase() int32 {
	if x != nil {
		return x.IdClase
	}
	return 0
}

func (x *CrearRepositorioRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

type CrearRepositorioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	IdRepositorio int32                  `protobuf:"varint,3,opt,name=id_repositorio,json=idRepositorio,proto3" json:"id_repositorio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearRepositorioResponse) Reset() {
	*x = CrearRepositorioResponse{}
	mi := &file_recursos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearRepositorioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearRepositorioResponse) ProtoMessage() {}

func (x *CrearRepositorioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearRepositorioResponse.ProtoReflect.Descriptor instead.
func (*CrearRepositorioResponse) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{4}
}

func (x *CrearRepositorioResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *CrearRepositorioResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *CrearRepositorioResponse) GetIdRepositorio() int32 {
	if x != nil {
		return x.IdRepositorio
	}
	return 0
}

// ──────────────────────────────────────────────
// AgregarArchivo
// ──────────────────────────────────────────────
type AgregarArchivoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdRepositorio int32                  `protobuf:"varint,1,opt,name=id_repositorio,json=idRepositorio,proto3" json:"id_repositorio,omitempty"`
	Nombre        string                 `protobuf:"bytes,2,opt,name=nombre,proto3" json:"nombre,omitempty"`
	Link          string                 `protobuf:"bytes,3,opt,name=link,proto3" json:"link,omitempty"`
	Tag           string                 `protobuf:"bytes,4,opt,name=tag,proto3" json:"tag,omitempty"`
	Hash          string                 `protobuf:"bytes,5,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgregarArchivoRequest) Reset() {
	*x = AgregarArchivoRequest{}
	mi := &file_recursos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgregarArchivoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgregarArchivoRequest) ProtoMessage() {}

func (x *AgregarArchivoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgregarArchivoRequest.ProtoReflect.Descriptor instead.
func (*AgregarArchivoRequest) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{5}
}

func (x *AgregarArchivoRequest) GetIdRepositorio() int32 {
	if x != nil {
		return x.IdRepositorio
	}
	return 0
}

func (x *AgregarArchivoRequest) GetNombre() string {
	if x != nil {
		return x.Nombre
	}
	return ""
}

func (x *AgregarArchivoRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *AgregarArchivoRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AgregarArchivoRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type AgregarArchivoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	IdArchivo     int32                  `protobuf:"varint,3,opt,name=id_archivo,json=idArchivo,proto3" json:"id_archivo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgregarArchivoResponse) Reset() {
	*x = AgregarArchivoResponse{}
	mi := &file_recursos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgregarArchivoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgregarArchivoResponse) ProtoMessage() {}

func (x *AgregarArchivoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgregarArchivoResponse.ProtoReflect.Descriptor instead.
func (*AgregarArchivoResponse) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{6}
}

func (x *AgregarArchivoResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *AgregarArchivoResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *AgregarArchivoResponse) GetIdArchivo() int32 {
	if x != nil {
		return x.IdArchivo
	}
	return 0
}

// ──────────────────────────────────────────────
// ActualizarVersionArchivo
// ──────────────────────────────────────────────
type ActualizarVersionArchivoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdArchivo     int32                  `protobuf:"varint,1,opt,name=id_archivo,json=idArchivo,proto3" json:"id_archivo,omitempty"`
	Link          string                 `protobuf:"bytes,2,opt,name=link,proto3" json:"link,omitempty"`
	Tag           string                 `protobuf:"bytes,3,opt,name=tag,proto3" json:"tag,omitempty"`
	Hash          string                 `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualizarVersionArchivoRequest) Reset() {
	*x = ActualizarVersionArchivoRequest{}
	mi := &file_recursos_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizarVersionArchivoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarVersionArchivoRequest) ProtoMessage() {}

func (x *ActualizarVersionArchivoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarVersionArchivoRequest.ProtoReflect.Descriptor instead.
func (*ActualizarVersionArchivoRequest) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{7}
}

func (x *ActualizarVersionArchivoRequest) GetIdArchivo() int32 {
	if x != nil {
		return x.IdArchivo
	}
	return 0
}

func (x *ActualizarVersionArchivoRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *ActualizarVersionArchivoRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *ActualizarVersionArchivoRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type ActualizarVersionArchivoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualizarVersionArchivoResponse) Reset() {
	*x = ActualizarVersionArchivoResponse{}
	mi := &file_recursos_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizarVersionArchivoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarVersionArchivoResponse) ProtoMessage() {}

func (x *ActualizarVersionArchivoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarVersionArchivoResponse.ProtoReflect.Descriptor instead.
func (*ActualizarVersionArchivoResponse) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{8}
}

func (x *ActualizarVersionArchivoResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ActualizarVersionArchivoResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

// ──────────────────────────────────────────────
// EliminarArchivo
// ──────────────────────────────────────────────
type EliminarArchivoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdArchivo     int32                  `protobuf:"varint,1,opt,name=id_archivo,json=idArchivo,proto3" json:"id_archivo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EliminarArchivoRequest) Reset() {
	*x = EliminarArchivoRequest{}
	mi := &file_recursos_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EliminarArchivoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminarArchivoRequest) ProtoMessage() {}

func (x *EliminarArchivoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminarArchivoRequest.ProtoReflect.Descriptor instead.
func (*EliminarArchivoRequest) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{9}
}

func (x *EliminarArchivoRequest) GetIdArchivo() int32 {
	if x != nil {
		return x.IdArchivo
	}
	return 0
}

type EliminarArchivoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EliminarArchivoResponse) Reset() {
	*x = EliminarArchivoResponse{}
	mi := &file_recursos_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EliminarArchivoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminarArchivoResponse) ProtoMessage() {}

func (x *EliminarArchivoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminarArchivoResponse.ProtoReflect.Descriptor instead.
func (*EliminarArchivoResponse) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{10}
}

func (x *EliminarArchivoResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *EliminarArchivoResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

// ──────────────────────────────────────────────
// ConsultarRepositorio (con lista de archivos)
// ──────────────────────────────────────────────
type ConsultarRepositorioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdClase       int32                  `protobuf:"varint,1,opt,name=id_clase,json=idClase,proto3" json:"id_clase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarRepositorioRequest) Reset() {
	*x = ConsultarRepositorioRequest{}
	mi := &file_recursos_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarRepositorioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarRepositorioRequest) ProtoMessage() {}

func (x *ConsultarRepositorioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarRepositorioRequest.ProtoReflect.Descriptor instead.
func (*ConsultarRepositorioRequest) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{11}
}

func (x *ConsultarRepositorioRequest) GetIdClase() int32 {
	if x != nil {
		return x.IdClase
	}
	return 0
}

type ConsultarRepositorioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Repositorio   *RepositorioInfo       `protobuf:"bytes,3,opt,name=repositorio,proto3" json:"repositorio,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarRepositorioResponse) Reset() {
	*x = ConsultarRepositorioResponse{}
	mi := &file_recursos_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarRepositorioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarRepositorioResponse) ProtoMessage() {}

func (x *ConsultarRepositorioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarRepositorioResponse.ProtoReflect.Descriptor instead.
func (*ConsultarRepositorioResponse) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{12}
}

func (x *ConsultarRepositorioResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ConsultarRepositorioResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *ConsultarRepositorioResponse) GetRepositorio() *RepositorioInfo {
	if x != nil {
		return x.Repositorio
	}
	return nil
}

// ──────────────────────────────────────────────
// ConsultarVersionesArchivo (todas las versiones)
// ──────────────────────────────────────────────
type ConsultarVersionesArchivoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdArchivo     int32                  `protobuf:"varint,1,opt,name=id_archivo,json=idArchivo,proto3" json:"id_archivo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarVersionesArchivoRequest) Reset() {
	*x = ConsultarVersionesArchivoRequest{}
	mi := &file_recursos_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarVersionesArchivoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarVersionesArchivoRequest) ProtoMessage() {}

func (x *ConsultarVersionesArchivoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarVersionesArchivoRequest.ProtoReflect.Descriptor instead.
func (*ConsultarVersionesArchivoRequest) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{13}
}

func (x *ConsultarVersionesArchivoRequest) GetIdArchivo() int32 {
	if x != nil {
		return x.IdArchivo
	}
	return 0
}

type ConsultarVersionesArchivoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Versiones     []*VersionArchivo      `protobuf:"bytes,3,rep,name=versiones,proto3" json:"versiones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarVersionesArchivoResponse) Reset() {
	*x = ConsultarVersionesArchivoResponse{}
	mi := &file_recursos_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarVersionesArchivoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarVersionesArchivoResponse) ProtoMessage() {}

func (x *ConsultarVersionesArchivoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarVersionesArchivoResponse.ProtoReflect.Descriptor instead.
func (*ConsultarVersionesArchivoResponse) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{14}
}

func (x *ConsultarVersionesArchivoResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ConsultarVersionesArchivoResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *ConsultarVersionesArchivoResponse) GetVersiones() []*VersionArchivo {
	if x != nil {
		return x.Versiones
	}
	return nil
}

// ──────────────────────────────────────────────
// ConsultarVersionArchivo (versión concreta)
// ──────────────────────────────────────────────
type ConsultarVersionArchivoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdArchivo     int32                  `protobuf:"varint,1,opt,name=id_archivo,json=idArchivo,proto3" json:"id_archivo,omitempty"`
	IdVersion     int32                  `protobuf:"varint,2,opt,name=id_version,json=idVersion,proto3" json:"id_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarVersionArchivoRequest) Reset() {
	*x = ConsultarVersionArchivoRequest{}
	mi := &file_recursos_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarVersionArchivoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarVersionArchivoRequest) ProtoMessage() {}

func (x *ConsultarVersionArchivoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarVersionArchivoRequest.ProtoReflect.Descriptor instead.
func (*ConsultarVersionArchivoRequest) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{15}
}

func (x *ConsultarVersionArchivoRequest) GetIdArchivo() int32 {
	if x != nil {
		return x.IdArchivo
	}
	return 0
}

func (x *ConsultarVersionArchivoRequest) GetIdVersion() int32 {
	if x != nil {
		return x.IdVersion
	}
	return 0
}

type ConsultarVersionArchivoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Version       *VersionArchivo        `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarVersionArchivoResponse) Reset() {
	*x = ConsultarVersionArchivoResponse{}
	mi := &file_recursos_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarVersionArchivoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarVersionArchivoResponse) ProtoMessage() {}

func (x *ConsultarVersionArchivoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarVersionArchivoResponse.ProtoReflect.Descriptor instead.
func (*ConsultarVersionArchivoResponse) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{16}
}

func (x *ConsultarVersionArchivoResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ConsultarVersionArchivoResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *ConsultarVersionArchivoResponse) GetVersion() *VersionArchivo {
	if x != nil {
		return x.Version
	}
	return nil
}

// ──────────────────────────────────────────────
// ActualizarTag
// ──────────────────────────────────────────────
type ActualizarTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdVersion     int32                  `protobuf:"varint,1,opt,name=id_version,json=idVersion,proto3" json:"id_version,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualizarTagRequest) Reset() {
	*x = ActualizarTagRequest{}
	mi := &file_recursos_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizarTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarTagRequest) ProtoMessage() {}

func (x *ActualizarTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarTagRequest.ProtoReflect.Descriptor instead.
func (*ActualizarTagRequest) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{17}
}

func (x *ActualizarTagRequest) GetIdVersion() int32 {
	if x != nil {
		return x.IdVersion
	}
	return 0
}

func (x *ActualizarTagRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type ActualizarTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualizarTagResponse) Reset() {
	*x = ActualizarTagResponse{}
	mi := &file_recursos_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizarTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarTagResponse) ProtoMessage() {}

func (x *ActualizarTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarTagResponse.ProtoReflect.Descriptor instead.
func (*ActualizarTagResponse) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{18}
}

func (x *ActualizarTagResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ActualizarTagResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

// ──────────────────────────────────────────────
// Mensajes de dominio — Apuntes
// ──────────────────────────────────────────────
type MarcadorTiempo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdMarcador    int32                  `protobuf:"varint,1,opt,name=id_marcador,json=idMarcador,proto3" json:"id_marcador,omitempty"`
	Segundo       int32                  `protobuf:"varint,2,opt,name=segundo,proto3" json:"segundo,omitempty"`
	Texto         string                 `protobuf:"bytes,3,opt,name=texto,proto3" json:"texto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarcadorTiempo) Reset() {
	*x = MarcadorTiempo{}
	mi := &file_recursos_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarcadorTiempo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarcadorTiempo) ProtoMessage() {}

func (x *MarcadorTiempo) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarcadorTiempo.ProtoReflect.Descriptor instead.
func (*MarcadorTiempo) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{19}
}

func (x *MarcadorTiempo) GetIdMarcador() int32 {
	if x != nil {
		return x.IdMarcador
	}
	return 0
}

func (x *MarcadorTiempo) GetSegundo() int32 {
	if x != nil {
		return x.Segundo
	}
	return 0
}

func (x *MarcadorTiempo) GetTexto() string {
	if x != nil {
		return x.Texto
	}
	return ""
}

type ApunteInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IdApunte           int32                  `protobuf:"varint,1,opt,name=id_apunte,json=idApunte,proto3" json:"id_apunte,omitempty"`
	IdClase            int32                  `protobuf:"varint,2,opt,name=id_clase,json=idClase,proto3" json:"id_clase,omitempty"`
	IdUsuario          int32                  `protobuf:"varint,3,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`
	Titulo             string                 `protobuf:"bytes,4,opt,name=titulo,proto3" json:"titulo,omitempty"`
	ContenidoMarkdown  string                 `protobuf:"bytes,5,opt,name=contenido_markdown,json=contenidoMarkdown,proto3" json:"contenido_markdown,omitempty"`
	FechaCreacion      string                 `protobuf:"bytes,6,opt,name=fecha_creacion,json=fechaCreacion,proto3" json:"fecha_creacion,omitempty"`
	FechaActualizacion string                 `protobuf:"bytes,7,opt,name=fecha_actualizacion,json=fechaActualizacion,proto3" json:"fecha_actualizacion,omitempty"`
	Marcadores         []*MarcadorTiempo      `protobuf:"bytes,8,rep,name=marcadores,proto3" json:"marcadores,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ApunteInfo) Reset() {
	*x = ApunteInfo{}
	mi := &file_recursos_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApunteInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApunteInfo) ProtoMessage() {}

func (x *ApunteInfo) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApunteInfo.ProtoReflect.Descriptor instead.
func (*ApunteInfo) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{20}
}

func (x *ApunteInfo) GetIdApunte() int32 {
	if x != nil {
		return x.IdApunte
	}
	return 0
}

func (x *ApunteInfo) GetIdClase() int32 {
	if x != nil {
		return x.IdClase
	}
	return 0
}

func (x *ApunteInfo) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

func (x *ApunteInfo) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *ApunteInfo) GetContenidoMarkdown() string {
	if x != nil {
		return x.ContenidoMarkdown
	}
	return ""
}

func (x *ApunteInfo) GetFechaCreacion() string {
	if x != nil {
		return x.FechaCreacion
	}
	return ""
}

func (x *ApunteInfo) GetFechaActualizacion() string {
	if x != nil {
		return x.FechaActualizacion
	}
	return ""
}

func (x *ApunteInfo) GetMarcadores() []*MarcadorTiempo {
	if x != nil {
		return x.Marcadores
	}
	return nil
}

// ──────────────────────────────────────────────
// ConsultarApunte
// ──────────────────────────────────────────────
type ConsultarApunteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdClase       int32                  `protobuf:"varint,1,opt,name=id_clase,json=idClase,proto3" json:"id_clase,omitempty"`
	IdUsuario     int32                  `protobuf:"varint,2,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarApunteRequest) Reset() {
	*x = ConsultarApunteRequest{}
	mi := &file_recursos_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarApunteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarApunteRequest) ProtoMessage() {}

func (x *ConsultarApunteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarApunteRequest.ProtoReflect.Descriptor instead.
func (*ConsultarApunteRequest) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{21}
}

func (x *ConsultarApunteRequest) GetIdClase() int32 {
	if x != nil {
		return x.IdClase
	}
	return 0
}

func (x *ConsultarApunteRequest) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

type ConsultarApunteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Apunte        *ApunteInfo            `protobuf:"bytes,3,opt,name=apunte,proto3" json:"apunte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarApunteResponse) Reset() {
	*x = ConsultarApunteResponse{}
	mi := &file_recursos_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarApunteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarApunteResponse) ProtoMessage() {}

func (x *ConsultarApunteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarApunteResponse.ProtoReflect.Descriptor instead.
func (*ConsultarApunteResponse) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{22}
}

func (x *ConsultarApunteResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ConsultarApunteResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *ConsultarApunteResponse) GetApunte() *ApunteInfo {
	if x != nil {
		return x.Apunte
	}
	return nil
}

// ──────────────────────────────────────────────
// CrearApunte
// ──────────────────────────────────────────────
type CrearApunteRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IdClase           int32                  `protobuf:"varint,1,opt,name=id_clase,json=idClase,proto3" json:"id_clase,omitempty"`
	IdUsuario         int32                  `protobuf:"varint,2,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`
	Titulo            string                 `protobuf:"bytes,3,opt,name=titulo,proto3" json:"titulo,omitempty"`
	ContenidoMarkdown string                 `protobuf:"bytes,4,opt,name=contenido_markdown,json=contenidoMarkdown,proto3" json:"contenido_markdown,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CrearApunteRequest) Reset() {
	*x = CrearApunteRequest{}
	mi := &file_recursos_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearApunteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearApunteRequest) ProtoMessage() {}

func (x *CrearApunteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearApunteRequest.ProtoReflect.Descriptor instead.
func (*CrearApunteRequest) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{23}
}

func (x *CrearApunteRequest) GetIdClase() int32 {
	if x != nil {
		return x.IdClase
	}
	return 0
}

func (x *CrearApunteRequest) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

func (x *CrearApunteRequest) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *CrearApunteRequest) GetContenidoMarkdown() string {
	if x != nil {
		return x.ContenidoMarkdown
	}
	return ""
}

type CrearApunteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	IdApunte      int32                  `protobuf:"varint,3,opt,name=id_apunte,json=idApunte,proto3" json:"id_apunte,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearApunteResponse) Reset() {
	*x = CrearApunteResponse{}
	mi := &file_recursos_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearApunteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearApunteResponse) ProtoMessage() {}

func (x *CrearApunteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearApunteResponse.ProtoReflect.Descriptor instead.
func (*CrearApunteResponse) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{24}
}

func (x *CrearApunteResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *CrearApunteResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *CrearApunteResponse) GetIdApunte() int32 {
	if x != nil {
		return x.IdApunte
	}
	return 0
}

// ──────────────────────────────────────────────
// ActualizarApunte
// ──────────────────────────────────────────────
type ActualizarApunteRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	IdApunte          int32                  `protobuf:"varint,1,opt,name=id_apunte,json=idApunte,proto3" json:"id_apunte,omitempty"`
	Titulo            string                 `protobuf:"bytes,2,opt,name=titulo,proto3" json:"titulo,omitempty"`
	ContenidoMarkdown string                 `protobuf:"bytes,3,opt,name=contenido_markdown,json=contenidoMarkdown,proto3" json:"contenido_markdown,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ActualizarApunteRequest) Reset() {
	*x = ActualizarApunteRequest{}
	mi := &file_recursos_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizarApunteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarApunteRequest) ProtoMessage() {}

func (x *ActualizarApunteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarApunteRequest.ProtoReflect.Descriptor instead.
func (*ActualizarApunteRequest) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{25}
}

func (x *ActualizarApunteRequest) GetIdApunte() int32 {
	if x != nil {
		return x.IdApunte
	}
	return 0
}

func (x *ActualizarApunteRequest) GetTitulo() string {
	if x != nil {
		return x.Titulo
	}
	return ""
}

func (x *ActualizarApunteRequest) GetContenidoMarkdown() string {
	if x != nil {
		return x.ContenidoMarkdown
	}
	return ""
}

type ActualizarApunteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualizarApunteResponse) Reset() {
	*x = ActualizarApunteResponse{}
	mi := &file_recursos_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizarApunteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarApunteResponse) ProtoMessage() {}

func (x *ActualizarApunteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarApunteResponse.ProtoReflect.Descriptor instead.
func (*ActualizarApunteResponse) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{26}
}

func (x *ActualizarApunteResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ActualizarApunteResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

// ──────────────────────────────────────────────
// AgregarMarcadorTiempo
// ──────────────────────────────────────────────
type AgregarMarcadorTiempoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdApunte      int32                  `protobuf:"varint,1,opt,name=id_apunte,json=idApunte,proto3" json:"id_apunte,omitempty"`
	Segundo       int32                  `protobuf:"varint,2,opt,name=segundo,proto3" json:"segundo,omitempty"`
	Texto         string                 `protobuf:"bytes,3,opt,name=texto,proto3" json:"texto,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgregarMarcadorTiempoRequest) Reset() {
	*x = AgregarMarcadorTiempoRequest{}
	mi := &file_recursos_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgregarMarcadorTiempoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgregarMarcadorTiempoRequest) ProtoMessage() {}

func (x *AgregarMarcadorTiempoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgregarMarcadorTiempoRequest.ProtoReflect.Descriptor instead.
func (*AgregarMarcadorTiempoRequest) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{27}
}

func (x *AgregarMarcadorTiempoRequest) GetIdApunte() int32 {
	if x != nil {
		return x.IdApunte
	}
	return 0
}

func (x *AgregarMarcadorTiempoRequest) GetSegundo() int32 {
	if x != nil {
		return x.Segundo
	}
	return 0
}

func (x *AgregarMarcadorTiempoRequest) GetTexto() string {
	if x != nil {
		return x.Texto
	}
	return ""
}

type AgregarMarcadorTiempoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	IdMarcador    int32                  `protobuf:"varint,3,opt,name=id_marcador,json=idMarcador,proto3" json:"id_marcador,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgregarMarcadorTiempoResponse) Reset() {
	*x = AgregarMarcadorTiempoResponse{}
	mi := &file_recursos_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgregarMarcadorTiempoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgregarMarcadorTiempoResponse) ProtoMessage() {}

func (x *AgregarMarcadorTiempoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgregarMarcadorTiempoResponse.ProtoReflect.Descriptor instead.
func (*AgregarMarcadorTiempoResponse) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{28}
}

func (x *AgregarMarcadorTiempoResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *AgregarMarcadorTiempoResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *AgregarMarcadorTiempoResponse) GetIdMarcador() int32 {
	if x != nil {
		return x.IdMarcador
	}
	return 0
}

// ──────────────────────────────────────────────
// EliminarMarcadorTiempo
// ──────────────────────────────────────────────
type EliminarMarcadorTiempoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdMarcador    int32                  `protobuf:"varint,1,opt,name=id_marcador,json=idMarcador,proto3" json:"id_marcador,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EliminarMarcadorTiempoRequest) Reset() {
	*x = EliminarMarcadorTiempoRequest{}
	mi := &file_recursos_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EliminarMarcadorTiempoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminarMarcadorTiempoRequest) ProtoMessage() {}

func (x *EliminarMarcadorTiempoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminarMarcadorTiempoRequest.ProtoReflect.Descriptor instead.
func (*EliminarMarcadorTiempoRequest) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{29}
}

func (x *EliminarMarcadorTiempoRequest) GetIdMarcador() int32 {
	if x != nil {
		return x.IdMarcador
	}
	return 0
}

type EliminarMarcadorTiempoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EliminarMarcadorTiempoResponse) Reset() {
	*x = EliminarMarcadorTiempoResponse{}
	mi := &file_recursos_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EliminarMarcadorTiempoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminarMarcadorTiempoResponse) ProtoMessage() {}

func (x *EliminarMarcadorTiempoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminarMarcadorTiempoResponse.ProtoReflect.Descriptor instead.
func (*EliminarMarcadorTiempoResponse) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{30}
}

func (x *EliminarMarcadorTiempoResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *EliminarMarcadorTiempoResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

// ──────────────────────────────────────────────
// Mensajes de dominio — Dudas y respuestas
// ──────────────────────────────────────────────
type Duda struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdDudas       int32                  `protobuf:"varint,1,opt,name=id_dudas,json=idDudas,proto3" json:"id_dudas,omitempty"`
	IdClase       int32                  `protobuf:"varint,2,opt,name=id_clase,json=idClase,proto3" json:"id_clase,omitempty"`
	IdUsuario     int32                  `protobuf:"varint,3,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`
	Duda          string                 `protobuf:"bytes,4,opt,name=duda,proto3" json:"duda,omitempty"`
	Segundo       *int32                 `protobuf:"varint,5,opt,name=segundo,proto3,oneof" json:"segundo,omitempty"`
	FechaCreacion string                 `protobuf:"bytes,6,opt,name=fecha_creacion,json=fechaCreacion,proto3" json:"fecha_creacion,omitempty"`
	Respuestas    []*Respuesta           `protobuf:"bytes,7,rep,name=respuestas,proto3" json:"respuestas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Duda) Reset() {
	*x = Duda{}
	mi := &file_recursos_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Duda) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Duda) ProtoMessage() {}

func (x *Duda) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Duda.ProtoReflect.Descriptor instead.
func (*Duda) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{31}
}

func (x *Duda) GetIdDudas() int32 {
	if x != nil {
		return x.IdDudas
	}
	return 0
}

func (x *Duda) GetIdClase() int32 {
	if x != nil {
		return x.IdClase
	}
	return 0
}

func (x *Duda) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

func (x *Duda) GetDuda() string {
	if x != nil {
		return x.Duda
	}
	return ""
}

func (x *Duda) GetSegundo() int32 {
	if x != nil && x.Segundo != nil {
		return *x.Segundo
	}
	return 0
}

func (x *Duda) GetFechaCreacion() string {
	if x != nil {
		return x.FechaCreacion
	}
	return ""
}

func (x *Duda) GetRespuestas() []*Respuesta {
	if x != nil {
		return x.Respuestas
	}
	return nil
}

type Respuesta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdRespuesta   int32                  `protobuf:"varint,1,opt,name=id_respuesta,json=idRespuesta,proto3" json:"id_respuesta,omitempty"`
	IdDuda        int32                  `protobuf:"varint,2,opt,name=id_duda,json=idDuda,proto3" json:"id_duda,omitempty"`
	IdUsuario     int32                  `protobuf:"varint,3,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`
	Respuesta     string                 `protobuf:"bytes,4,opt,name=respuesta,proto3" json:"respuesta,omitempty"`
	Marcada       bool                   `protobuf:"varint,5,opt,name=marcada,proto3" json:"marcada,omitempty"`
	FechaCreacion string                 `protobuf:"bytes,6,opt,name=fecha_creacion,json=fechaCreacion,proto3" json:"fecha_creacion,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Respuesta) Reset() {
	*x = Respuesta{}
	mi := &file_recursos_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Respuesta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Respuesta) ProtoMessage() {}

func (x *Respuesta) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Respuesta.ProtoReflect.Descriptor instead.
func (*Respuesta) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{32}
}

func (x *Respuesta) GetIdRespuesta() int32 {
	if x != nil {
		return x.IdRespuesta
	}
	return 0
}

func (x *Respuesta) GetIdDuda() int32 {
	if x != nil {
		return x.IdDuda
	}
	return 0
}

func (x *Respuesta) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

func (x *Respuesta) GetRespuesta() string {
	if x != nil {
		return x.Respuesta
	}
	return ""
}

func (x *Respuesta) GetMarcada() bool {
	if x != nil {
		return x.Marcada
	}
	return false
}

func (x *Respuesta) GetFechaCreacion() string {
	if x != nil {
		return x.FechaCreacion
	}
	return ""
}

// ──────────────────────────────────────────────
// ConsultarDudasClase
// ──────────────────────────────────────────────
type ConsultarDudasClaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdClase       int32                  `protobuf:"varint,1,opt,name=id_clase,json=idClase,proto3" json:"id_clase,omitempty"`
	Pagina        int32                  `protobuf:"varint,2,opt,name=pagina,proto3" json:"pagina,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarDudasClaseRequest) Reset() {
	*x = ConsultarDudasClaseRequest{}
	mi := &file_recursos_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarDudasClaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarDudasClaseRequest) ProtoMessage() {}

func (x *ConsultarDudasClaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarDudasClaseRequest.ProtoReflect.Descriptor instead.
func (*ConsultarDudasClaseRequest) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{33}
}

func (x *ConsultarDudasClaseRequest) GetIdClase() int32 {
	if x != nil {
		return x.IdClase
	}
	return 0
}

func (x *ConsultarDudasClaseRequest) GetPagina() int32 {
	if x != nil {
		return x.Pagina
	}
	return 0
}

type ConsultarDudasClaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Dudas         []*Duda                `protobuf:"bytes,3,rep,name=dudas,proto3" json:"dudas,omitempty"`
	TotalPaginas  int32                  `protobuf:"varint,4,opt,name=total_paginas,json=totalPaginas,proto3" json:"total_paginas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarDudasClaseResponse) Reset() {
	*x = ConsultarDudasClaseResponse{}
	mi := &file_recursos_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarDudasClaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarDudasClaseResponse) ProtoMessage() {}

func (x *ConsultarDudasClaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarDudasClaseResponse.ProtoReflect.Descriptor instead.
func (*ConsultarDudasClaseResponse) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{34}
}

func (x *ConsultarDudasClaseResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ConsultarDudasClaseResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *ConsultarDudasClaseResponse) GetDudas() []*Duda {
	if x != nil {
		return x.Dudas
	}
	return nil
}

func (x *ConsultarDudasClaseResponse) GetTotalPaginas() int32 {
	if x != nil {
		return x.TotalPaginas
	}
	return 0
}

// ──────────────────────────────────────────────
// CrearDuda
// ──────────────────────────────────────────────
type CrearDudaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdClase       int32                  `protobuf:"varint,1,opt,name=id_clase,json=idClase,proto3" json:"id_clase,omitempty"`
	IdUsuario     int32                  `protobuf:"varint,2,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`
	Duda          string                 `protobuf:"bytes,3,opt,name=duda,proto3" json:"duda,omitempty"`
	Segundo       *int32                 `protobuf:"varint,4,opt,name=segundo,proto3,oneof" json:"segundo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearDudaRequest) Reset() {
	*x = CrearDudaRequest{}
	mi := &file_recursos_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearDudaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearDudaRequest) ProtoMessage() {}

func (x *CrearDudaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearDudaRequest.ProtoReflect.Descriptor instead.
func (*CrearDudaRequest) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{35}
}

func (x *CrearDudaRequest) GetIdClase() int32 {
	if x != nil {
		return x.IdClase
	}
	return 0
}

func (x *CrearDudaRequest) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

func (x *CrearDudaRequest) GetDuda() string {
	if x != nil {
		return x.Duda
	}
	return ""
}

func (x *CrearDudaRequest) GetSegundo() int32 {
	if x != nil && x.Segundo != nil {
		return *x.Segundo
	}
	return 0
}

type CrearDudaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	IdDudas       int32                  `protobuf:"varint,3,opt,name=id_dudas,json=idDudas,proto3" json:"id_dudas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearDudaResponse) Reset() {
	*x = CrearDudaResponse{}
	mi := &file_recursos_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearDudaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearDudaResponse) ProtoMessage() {}

func (x *CrearDudaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearDudaResponse.ProtoReflect.Descriptor instead.
func (*CrearDudaResponse) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{36}
}

func (x *CrearDudaResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *CrearDudaResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *CrearDudaResponse) GetIdDudas() int32 {
	if x != nil {
		return x.IdDudas
	}
	return 0
}

// ──────────────────────────────────────────────
// CrearRespuesta
// ──────────────────────────────────────────────
type CrearRespuestaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdDuda        int32                  `protobuf:"varint,1,opt,name=id_duda,json=idDuda,proto3" json:"id_duda,omitempty"`
	IdUsuario     int32                  `protobuf:"varint,2,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`
	Respuesta     string                 `protobuf:"bytes,3,opt,name=respuesta,proto3" json:"respuesta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearRespuestaRequest) Reset() {
	*x = CrearRespuestaRequest{}
	mi := &file_recursos_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearRespuestaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearRespuestaRequest) ProtoMessage() {}

func (x *CrearRespuestaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearRespuestaRequest.ProtoReflect.Descriptor instead.
func (*CrearRespuestaRequest) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{37}
}

func (x *CrearRespuestaRequest) GetIdDuda() int32 {
	if x != nil {
		return x.IdDuda
	}
	return 0
}

func (x *CrearRespuestaRequest) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

func (x *CrearRespuestaRequest) GetRespuesta() string {
	if x != nil {
		return x.Respuesta
	}
	return ""
}

type CrearRespuestaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	IdRespuesta   int32                  `protobuf:"varint,3,opt,name=id_respuesta,json=idRespuesta,proto3" json:"id_respuesta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrearRespuestaResponse) Reset() {
	*x = CrearRespuestaResponse{}
	mi := &file_recursos_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrearRespuestaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrearRespuestaResponse) ProtoMessage() {}

func (x *CrearRespuestaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrearRespuestaResponse.ProtoReflect.Descriptor instead.
func (*CrearRespuestaResponse) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{38}
}

func (x *CrearRespuestaResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *CrearRespuestaResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *CrearRespuestaResponse) GetIdRespuesta() int32 {
	if x != nil {
		return x.IdRespuesta
	}
	return 0
}

// ──────────────────────────────────────────────
// MarcarRespuesta
// ──────────────────────────────────────────────
type MarcarRespuestaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdRespuesta   int32                  `protobuf:"varint,1,opt,name=id_respuesta,json=idRespuesta,proto3" json:"id_respuesta,omitempty"`
	IdUsuario     int32                  `protobuf:"varint,2,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarcarRespuestaRequest) Reset() {
	*x = MarcarRespuestaRequest{}
	mi := &file_recursos_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarcarRespuestaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarcarRespuestaRequest) ProtoMessage() {}

func (x *MarcarRespuestaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarcarRespuestaRequest.ProtoReflect.Descriptor instead.
func (*MarcarRespuestaRequest) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{39}
}

func (x *MarcarRespuestaRequest) GetIdRespuesta() int32 {
	if x != nil {
		return x.IdRespuesta
	}
	return 0
}

func (x *MarcarRespuestaRequest) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

type MarcarRespuestaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarcarRespuestaResponse) Reset() {
	*x = MarcarRespuestaResponse{}
	mi := &file_recursos_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarcarRespuestaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarcarRespuestaResponse) ProtoMessage() {}

func (x *MarcarRespuestaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_recursos_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarcarRespuestaResponse.ProtoReflect.Descriptor instead.
func (*MarcarRespuestaResponse) Descriptor() ([]byte, []int) {
	return file_recursos_proto_rawDescGZIP(), []int{40}
}

func (x *MarcarRespuestaResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *MarcarRespuestaResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_recursos_proto protoreflect.FileDescriptor

const file_recursos_proto_rawDesc = "" +
	"\n" +
	"\x0erecursos.proto\x12\brecursos\"K\n" +
	"\x12ArchivoRepositorio\x12\x1d\n" +
	"\n" +
	"id_archivo\x18\x01 \x01(\x05R\tidArchivo\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\"\xc7\x01\n" +
	"\x0eVersionArchivo\x12\x1d\n" +
	"\n" +
	"id_version\x18\x01 \x01(\x05R\tidVersion\x12\x1d\n" +
	"\n" +
	"id_archivo\x18\x02 \x01(\x05R\tidArchivo\x12\x12\n" +
	"\x04link\x18\x03 \x01(\tR\x04link\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag\x12%\n" +
	"\x0efecha_creacion\x18\x05 \x01(\tR\rfechaCreacion\x12\x12\n" +
	"\x04hash\x18\x06 \x01(\tR\x04hash\x12\x16\n" +
	"\x06latest\x18\a \x01(\bR\x06latest\"\xa5\x01\n" +
	"\x0fRepositorioInfo\x12%\n" +
	"\x0eid_repositorio\x18\x01 \x01(\x05R\ridRepositorio\x12\x19\n" +
	"\bid_clase\x18\x02 \x01(\x05R\aidClase\x12\x16\n" +
	"\x06nombre\x18\x03 \x01(\tR\x06nombre\x128\n" +
	"\barchivos\x18\x04 \x03(\v2\x1c.recursos.ArchivoRepositorioR\barchivos\"L\n" +
	"\x17CrearRepositorioRequest\x12\x19\n" +
	"\bid_clase\x18\x01 \x01(\x05R\aidClase\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\"q\n" +
	"\x18CrearRepositorioResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12%\n" +
	"\x0eid_repositorio\x18\x03 \x01(\x05R\ridRepositorio\"\x90\x01\n" +
	"\x15AgregarArchivoRequest\x12%\n" +
	"\x0eid_repositorio\x18\x01 \x01(\x05R\ridRepositorio\x12\x16\n" +
	"\x06nombre\x18\x02 \x01(\tR\x06nombre\x12\x12\n" +
	"\x04link\x18\x03 \x01(\tR\x04link\x12\x10\n" +
	"\x03tag\x18\x04 \x01(\tR\x03tag\x12\x12\n" +
	"\x04hash\x18\x05 \x01(\tR\x04hash\"g\n" +
	"\x16AgregarArchivoResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12\x1d\n" +
	"\n" +
	"id_archivo\x18\x03 \x01(\x05R\tidArchivo\"z\n" +
	"\x1fActualizarVersionArchivoRequest\x12\x1d\n" +
	"\n" +
	"id_archivo\x18\x01 \x01(\x05R\tidArchivo\x12\x12\n" +
	"\x04link\x18\x02 \x01(\tR\x04link\x12\x10\n" +
	"\x03tag\x18\x03 \x01(\tR\x03tag\x12\x12\n" +
	"\x04hash\x18\x04 \x01(\tR\x04hash\"R\n" +
	" ActualizarVersionArchivoResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"7\n" +
	"\x16EliminarArchivoRequest\x12\x1d\n" +
	"\n" +
	"id_archivo\x18\x01 \x01(\x05R\tidArchivo\"I\n" +
	"\x17EliminarArchivoResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"8\n" +
	"\x1bConsultarRepositorioRequest\x12\x19\n" +
	"\bid_clase\x18\x01 \x01(\x05R\aidClase\"\x8b\x01\n" +
	"\x1cConsultarRepositorioResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12;\n" +
	"\vrepositorio\x18\x03 \x01(\v2\x19.recursos.RepositorioInfoR\vrepositorio\"A\n" +
	" ConsultarVersionesArchivoRequest\x12\x1d\n" +
	"\n" +
	"id_archivo\x18\x01 \x01(\x05R\tidArchivo\"\x8b\x01\n" +
	"!ConsultarVersionesArchivoResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x126\n" +
	"\tversiones\x18\x03 \x03(\v2\x18.recursos.VersionArchivoR\tversiones\"^\n" +
	"\x1eConsultarVersionArchivoRequest\x12\x1d\n" +
	"\n" +
	"id_archivo\x18\x01 \x01(\x05R\tidArchivo\x12\x1d\n" +
	"\n" +
	"id_version\x18\x02 \x01(\x05R\tidVersion\"\x85\x01\n" +
	"\x1fConsultarVersionArchivoResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x122\n" +
	"\aversion\x18\x03 \x01(\v2\x18.recursos.VersionArchivoR\aversion\"G\n" +
	"\x14ActualizarTagRequest\x12\x1d\n" +
	"\n" +
	"id_version\x18\x01 \x01(\x05R\tidVersion\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\"G\n" +
	"\x15ActualizarTagResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"a\n" +
	"\x0eMarcadorTiempo\x12\x1f\n" +
	"\vid_marcador\x18\x01 \x01(\x05R\n" +
	"idMarcador\x12\x18\n" +
	"\asegundo\x18\x02 \x01(\x05R\asegundo\x12\x14\n" +
	"\x05texto\x18\x03 \x01(\tR\x05texto\"\xbc\x02\n" +
	"\n" +
	"ApunteInfo\x12\x1b\n" +
	"\tid_apunte\x18\x01 \x01(\x05R\bidApunte\x12\x19\n" +
	"\bid_clase\x18\x02 \x01(\x05R\aidClase\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x03 \x01(\x05R\tidUsuario\x12\x16\n" +
	"\x06titulo\x18\x04 \x01(\tR\x06titulo\x12-\n" +
	"\x12contenido_markdown\x18\x05 \x01(\tR\x11contenidoMarkdown\x12%\n" +
	"\x0efecha_creacion\x18\x06 \x01(\tR\rfechaCreacion\x12/\n" +
	"\x13fecha_actualizacion\x18\a \x01(\tR\x12fechaActualizacion\x128\n" +
	"\n" +
	"marcadores\x18\b \x03(\v2\x18.recursos.MarcadorTiempoR\n" +
	"marcadores\"R\n" +
	"\x16ConsultarApunteRequest\x12\x19\n" +
	"\bid_clase\x18\x01 \x01(\x05R\aidClase\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x02 \x01(\x05R\tidUsuario\"w\n" +
	"\x17ConsultarApunteResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12,\n" +
	"\x06apunte\x18\x03 \x01(\v2\x14.recursos.ApunteInfoR\x06apunte\"\x95\x01\n" +
	"\x12CrearApunteRequest\x12\x19\n" +
	"\bid_clase\x18\x01 \x01(\x05R\aidClase\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x02 \x01(\x05R\tidUsuario\x12\x16\n" +
	"\x06titulo\x18\x03 \x01(\tR\x06titulo\x12-\n" +
	"\x12contenido_markdown\x18\x04 \x01(\tR\x11contenidoMarkdown\"b\n" +
	"\x13CrearApunteResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12\x1b\n" +
	"\tid_apunte\x18\x03 \x01(\x05R\bidApunte\"}\n" +
	"\x17ActualizarApunteRequest\x12\x1b\n" +
	"\tid_apunte\x18\x01 \x01(\x05R\bidApunte\x12\x16\n" +
	"\x06titulo\x18\x02 \x01(\tR\x06titulo\x12-\n" +
	"\x12contenido_markdown\x18\x03 \x01(\tR\x11contenidoMarkdown\"J\n" +
	"\x18ActualizarApunteResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"k\n" +
	"\x1cAgregarMarcadorTiempoRequest\x12\x1b\n" +
	"\tid_apunte\x18\x01 \x01(\x05R\bidApunte\x12\x18\n" +
	"\asegundo\x18\x02 \x01(\x05R\asegundo\x12\x14\n" +
	"\x05texto\x18\x03 \x01(\tR\x05texto\"p\n" +
	"\x1dAgregarMarcadorTiempoResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12\x1f\n" +
	"\vid_marcador\x18\x03 \x01(\x05R\n" +
	"idMarcador\"@\n" +
	"\x1dEliminarMarcadorTiempoRequest\x12\x1f\n" +
	"\vid_marcador\x18\x01 \x01(\x05R\n" +
	"idMarcador\"P\n" +
	"\x1eEliminarMarcadorTiempoResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"\xf6\x01\n" +
	"\x04Duda\x12\x19\n" +
	"\bid_dudas\x18\x01 \x01(\x05R\aidDudas\x12\x19\n" +
	"\bid_clase\x18\x02 \x01(\x05R\aidClase\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x03 \x01(\x05R\tidUsuario\x12\x12\n" +
	"\x04duda\x18\x04 \x01(\tR\x04duda\x12\x1d\n" +
	"\asegundo\x18\x05 \x01(\x05H\x00R\asegundo\x88\x01\x01\x12%\n" +
	"\x0efecha_creacion\x18\x06 \x01(\tR\rfechaCreacion\x123\n" +
	"\n" +
	"respuestas\x18\a \x03(\v2\x13.recursos.RespuestaR\n" +
	"respuestasB\n" +
	"\n" +
	"\b_segundo\"\xc5\x01\n" +
	"\tRespuesta\x12!\n" +
	"\fid_respuesta\x18\x01 \x01(\x05R\vidRespuesta\x12\x17\n" +
	"\aid_duda\x18\x02 \x01(\x05R\x06idDuda\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x03 \x01(\x05R\tidUsuario\x12\x1c\n" +
	"\trespuesta\x18\x04 \x01(\tR\trespuesta\x12\x18\n" +
	"\amarcada\x18\x05 \x01(\bR\amarcada\x12%\n" +
	"\x0efecha_creacion\x18\x06 \x01(\tR\rfechaCreacion\"O\n" +
	"\x1aConsultarDudasClaseRequest\x12\x19\n" +
	"\bid_clase\x18\x01 \x01(\x05R\aidClase\x12\x16\n" +
	"\x06pagina\x18\x02 \x01(\x05R\x06pagina\"\x98\x01\n" +
	"\x1bConsultarDudasClaseResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12$\n" +
	"\x05dudas\x18\x03 \x03(\v2\x0e.recursos.DudaR\x05dudas\x12#\n" +
	"\rtotal_paginas\x18\x04 \x01(\x05R\ftotalPaginas\"\x8b\x01\n" +
	"\x10CrearDudaRequest\x12\x19\n" +
	"\bid_clase\x18\x01 \x01(\x05R\aidClase\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x02 \x01(\x05R\tidUsuario\x12\x12\n" +
	"\x04duda\x18\x03 \x01(\tR\x04duda\x12\x1d\n" +
	"\asegundo\x18\x04 \x01(\x05H\x00R\asegundo\x88\x01\x01B\n" +
	"\n" +
	"\b_segundo\"^\n" +
	"\x11CrearDudaResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12\x19\n" +
	"\bid_dudas\x18\x03 \x01(\x05R\aidDudas\"m\n" +
	"\x15CrearRespuestaRequest\x12\x17\n" +
	"\aid_duda\x18\x01 \x01(\x05R\x06idDuda\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x02 \x01(\x05R\tidUsuario\x12\x1c\n" +
	"\trespuesta\x18\x03 \x01(\tR\trespuesta\"k\n" +
	"\x16CrearRespuestaResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12!\n" +
	"\fid_respuesta\x18\x03 \x01(\x05R\vidRespuesta\"Z\n" +
	"\x16MarcarRespuestaRequest\x12!\n" +
	"\fid_respuesta\x18\x01 \x01(\x05R\vidRespuesta\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x02 \x01(\x05R\tidUsuario\"I\n" +
	"\x17MarcarRespuestaResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje2\xd8\f\n" +
	"\x0fRecursosService\x12Y\n" +
	"\x10CrearRepositorio\x12!.recursos.CrearRepositorioRequest\x1a\".recursos.CrearRepositorioResponse\x12S\n" +
	"\x0eAgregarArchivo\x12\x1f.recursos.AgregarArchivoRequest\x1a .recursos.AgregarArchivoResponse\x12q\n" +
	"\x18ActualizarVersionArchivo\x12).recursos.ActualizarVersionArchivoRequest\x1a*.recursos.ActualizarVersionArchivoResponse\x12P\n" +
	"\rActualizarTag\x12\x1e.recursos.ActualizarTagRequest\x1a\x1f.recursos.ActualizarTagResponse\x12V\n" +
	"\x0fEliminarArchivo\x12 .recursos.EliminarArchivoRequest\x1a!.recursos.EliminarArchivoResponse\x12e\n" +
	"\x14ConsultarRepositorio\x12%.recursos.ConsultarRepositorioRequest\x1a&.recursos.ConsultarRepositorioResponse\x12t\n" +
	"\x19ConsultarVersionesArchivo\x12*.recursos.ConsultarVersionesArchivoRequest\x1a+.recursos.ConsultarVersionesArchivoResponse\x12n\n" +
	"\x17ConsultarVersionArchivo\x12(.recursos.ConsultarVersionArchivoRequest\x1a).recursos.ConsultarVersionArchivoResponse\x12V\n" +
	"\x0fConsultarApunte\x12 .recursos.ConsultarApunteRequest\x1a!.recursos.ConsultarApunteResponse\x12J\n" +
	"\vCrearApunte\x12\x1c.recursos.CrearApunteRequest\x1a\x1d.recursos.CrearApunteResponse\x12Y\n" +
	"\x10ActualizarApunte\x12!.recursos.ActualizarApunteRequest\x1a\".recursos.ActualizarApunteResponse\x12h\n" +
	"\x15AgregarMarcadorTiempo\x12&.recursos.AgregarMarcadorTiempoRequest\x1a'.recursos.AgregarMarcadorTiempoResponse\x12k\n" +
	"\x16EliminarMarcadorTiempo\x12'.recursos.EliminarMarcadorTiempoRequest\x1a(.recursos.EliminarMarcadorTiempoResponse\x12b\n" +
	"\x13ConsultarDudasClase\x12$.recursos.ConsultarDudasClaseRequest\x1a%.recursos.ConsultarDudasClaseResponse\x12D\n" +
	"\tCrearDuda\x12\x1a.recursos.CrearDudaRequest\x1a\x1b.recursos.CrearDudaResponse\x12S\n" +
	"\x0eCrearRespuesta\x12\x1f.recursos.CrearRespuestaRequest\x1a .recursos.CrearRespuestaResponse\x12V\n" +
	"\x0fMarcarRespuesta\x12 .recursos.MarcarRespuestaRequest\x1a!.recursos.MarcarRespuestaResponseB\x10Z\x0eproto/recursosb\x06proto3"

var (
	file_recursos_proto_rawDescOnce sync.Once
	file_recursos_proto_rawDescData []byte
)

func file_recursos_proto_rawDescGZIP() []byte {
	file_recursos_proto_rawDescOnce.Do(func() {
		file_recursos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recursos_proto_rawDesc), len(file_recursos_proto_rawDesc)))
	})
	return file_recursos_proto_rawDescData
}

var file_recursos_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_recursos_proto_goTypes = []any{
	(*ArchivoRepositorio)(nil),                // 0: recursos.ArchivoRepositorio
	(*VersionArchivo)(nil),                    // 1: recursos.VersionArchivo
	(*RepositorioInfo)(nil),                   // 2: recursos.RepositorioInfo
	(*CrearRepositorioRequest)(nil),           // 3: recursos.CrearRepositorioRequest
	(*CrearRepositorioResponse)(nil),          // 4: recursos.CrearRepositorioResponse
	(*AgregarArchivoRequest)(nil),             // 5: recursos.AgregarArchivoRequest
	(*AgregarArchivoResponse)(nil),            // 6: recursos.AgregarArchivoResponse
	(*ActualizarVersionArchivoRequest)(nil),   // 7: recursos.ActualizarVersionArchivoRequest
	(*ActualizarVersionArchivoResponse)(nil),  // 8: recursos.ActualizarVersionArchivoResponse
	(*EliminarArchivoRequest)(nil),            // 9: recursos.EliminarArchivoRequest
	(*EliminarArchivoResponse)(nil),           // 10: recursos.EliminarArchivoResponse
	(*ConsultarRepositorioRequest)(nil),       // 11: recursos.ConsultarRepositorioRequest
	(*ConsultarRepositorioResponse)(nil),      // 12: recursos.ConsultarRepositorioResponse
	(*ConsultarVersionesArchivoRequest)(nil),  // 13: recursos.ConsultarVersionesArchivoRequest
	(*ConsultarVersionesArchivoResponse)(nil), // 14: recursos.ConsultarVersionesArchivoResponse
	(*ConsultarVersionArchivoRequest)(nil),    // 15: recursos.ConsultarVersionArchivoRequest
	(*ConsultarVersionArchivoResponse)(nil),   // 16: recursos.ConsultarVersionArchivoResponse
	(*ActualizarTagRequest)(nil),              // 17: recursos.ActualizarTagRequest
	(*ActualizarTagResponse)(nil),             // 18: recursos.ActualizarTagResponse
	(*MarcadorTiempo)(nil),                    // 19: recursos.MarcadorTiempo
	(*ApunteInfo)(nil),                        // 20: recursos.ApunteInfo
	(*ConsultarApunteRequest)(nil),            // 21: recursos.ConsultarApunteRequest
	(*ConsultarApunteResponse)(nil),           // 22: recursos.ConsultarApunteResponse
	(*CrearApunteRequest)(nil),                // 23: recursos.CrearApunteRequest
	(*CrearApunteResponse)(nil),               // 24: recursos.CrearApunteResponse
	(*ActualizarApunteRequest)(nil),           // 25: recursos.ActualizarApunteRequest
	(*ActualizarApunteResponse)(nil),          // 26: recursos.ActualizarApunteResponse
	(*AgregarMarcadorTiempoRequest)(nil),      // 27: recursos.AgregarMarcadorTiempoRequest
	(*AgregarMarcadorTiempoResponse)(nil),     // 28: recursos.AgregarMarcadorTiempoResponse
	(*EliminarMarcadorTiempoRequest)(nil),     // 29: recursos.EliminarMarcadorTiempoRequest
	(*EliminarMarcadorTiempoResponse)(nil),    // 30: recursos.EliminarMarcadorTiempoResponse
	(*Duda)(nil),                              // 31: recursos.Duda
	(*Respuesta)(nil),                         // 32: recursos.Respuesta
	(*ConsultarDudasClaseRequest)(nil),        // 33: recursos.ConsultarDudasClaseRequest
	(*ConsultarDudasClaseResponse)(nil),       // 34: recursos.ConsultarDudasClaseResponse
	(*CrearDudaRequest)(nil),                  // 35: recursos.CrearDudaRequest
	(*CrearDudaResponse)(nil),                 // 36: recursos.CrearDudaResponse
	(*CrearRespuestaRequest)(nil),             // 37: recursos.CrearRespuestaRequest
	(*CrearRespuestaResponse)(nil),            // 38: recursos.CrearRespuestaResponse
	(*MarcarRespuestaRequest)(nil),            // 39: recursos.MarcarRespuestaRequest
	(*MarcarRespuestaResponse)(nil),           // 40: recursos.MarcarRespuestaResponse
}
var file_recursos_proto_depIdxs = []int32{
	0,  // 0: recursos.RepositorioInfo.archivos:type_name -> recursos.ArchivoRepositorio
	2,  // 1: recursos.ConsultarRepositorioResponse.repositorio:type_name -> recursos.RepositorioInfo
	1,  // 2: recursos.ConsultarVersionesArchivoResponse.versiones:type_name -> recursos.VersionArchivo
	1,  // 3: recursos.ConsultarVersionArchivoResponse.version:type_name -> recursos.VersionArchivo
	19, // 4: recursos.ApunteInfo.marcadores:type_name -> recursos.MarcadorTiempo
	20, // 5: recursos.ConsultarApunteResponse.apunte:type_name -> recursos.ApunteInfo
	32, // 6: recursos.Duda.respuestas:type_name -> recursos.Respuesta
	31, // 7: recursos.ConsultarDudasClaseResponse.dudas:type_name -> recursos.Duda
	3,  // 8: recursos.RecursosService.CrearRepositorio:input_type -> recursos.CrearRepositorioRequest
	5,  // 9: recursos.RecursosService.AgregarArchivo:input_type -> recursos.AgregarArchivoRequest
	7,  // 10: recursos.RecursosService.ActualizarVersionArchivo:input_type -> recursos.ActualizarVersionArchivoRequest
	17, // 11: recursos.RecursosService.ActualizarTag:input_type -> recursos.ActualizarTagRequest
	9,  // 12: recursos.RecursosService.EliminarArchivo:input_type -> recursos.EliminarArchivoRequest
	11, // 13: recursos.RecursosService.ConsultarRepositorio:input_type -> recursos.ConsultarRepositorioRequest
	13, // 14: recursos.RecursosService.ConsultarVersionesArchivo:input_type -> recursos.ConsultarVersionesArchivoRequest
	15, // 15: recursos.RecursosService.ConsultarVersionArchivo:input_type -> recursos.ConsultarVersionArchivoRequest
	21, // 16: recursos.RecursosService.ConsultarApunte:input_type -> recursos.ConsultarApunteRequest
	23, // 17: recursos.RecursosService.CrearApunte:input_type -> recursos.CrearApunteRequest
	25, // 18: recursos.RecursosService.ActualizarApunte:input_type -> recursos.ActualizarApunteRequest
	27, // 19: recursos.RecursosService.AgregarMarcadorTiempo:input_type -> recursos.AgregarMarcadorTiempoRequest
	29, // 20: recursos.RecursosService.EliminarMarcadorTiempo:input_type -> recursos.EliminarMarcadorTiempoRequest
	33, // 21: recursos.RecursosService.ConsultarDudasClase:input_type -> recursos.ConsultarDudasClaseRequest
	35, // 22: recursos.RecursosService.CrearDuda:input_type -> recursos.CrearDudaRequest
	37, // 23: recursos.RecursosService.CrearRespuesta:input_type -> recursos.CrearRespuestaRequest
	39, // 24: recursos.RecursosService.MarcarRespuesta:input_type -> recursos.MarcarRespuestaRequest
	4,  // 25: recursos.RecursosService.CrearRepositorio:output_type -> recursos.CrearRepositorioResponse
	6,  // 26: recursos.RecursosService.AgregarArchivo:output_type -> recursos.AgregarArchivoResponse
	8,  // 27: recursos.RecursosService.ActualizarVersionArchivo:output_type -> recursos.ActualizarVersionArchivoResponse
	18, // 28: recursos.RecursosService.ActualizarTag:output_type -> recursos.ActualizarTagResponse
	10, // 29: recursos.RecursosService.EliminarArchivo:output_type -> recursos.EliminarArchivoResponse
	12, // 30: recursos.RecursosService.ConsultarRepositorio:output_type -> recursos.ConsultarRepositorioResponse
	14, // 31: recursos.RecursosService.ConsultarVersionesArchivo:output_type -> recursos.ConsultarVersionesArchivoResponse
	16, // 32: recursos.RecursosService.ConsultarVersionArchivo:output_type -> recursos.ConsultarVersionArchivoResponse
	22, // 33: recursos.RecursosService.ConsultarApunte:output_type -> recursos.ConsultarApunteResponse
	24, // 34: recursos.RecursosService.CrearApunte:output_type -> recursos.CrearApunteResponse
	26, // 35: recursos.RecursosService.ActualizarApunte:output_type -> recursos.ActualizarApunteResponse
	28, // 36: recursos.RecursosService.AgregarMarcadorTiempo:output_type -> recursos.AgregarMarcadorTiempoResponse
	30, // 37: recursos.RecursosService.EliminarMarcadorTiempo:output_type -> recursos.EliminarMarcadorTiempoResponse
	34, // 38: recursos.RecursosService.ConsultarDudasClase:output_type -> recursos.ConsultarDudasClaseResponse
	36, // 39: recursos.RecursosService.CrearDuda:output_type -> recursos.CrearDudaResponse
	38, // 40: recursos.RecursosService.CrearRespuesta:output_type -> recursos.CrearRespuestaResponse
	40, // 41: recursos.RecursosService.MarcarRespuesta:output_type -> recursos.MarcarRespuestaResponse
	25, // [25:42] is the sub-list for method output_type
	8,  // [8:25] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_recursos_proto_init() }
func file_recursos_proto_init() {
	if File_recursos_proto != nil {
		return
	}
	file_recursos_proto_msgTypes[31].OneofWrappers = []any{}
	file_recursos_proto_msgTypes[35].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recursos_proto_rawDesc), len(file_recursos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recursos_proto_goTypes,
		DependencyIndexes: file_recursos_proto_depIdxs,
		MessageInfos:      file_recursos_proto_msgTypes,
	}.Build()
	File_recursos_proto = out.File
	file_recursos_proto_goTypes = nil
	file_recursos_proto_depIdxs = nil
}
