"""HeinzGomez - Práctica 9: interfaces de persistencia (DIP: el servicio no sabe si es PostgreSQL
o memoria; LSP: ambas implementaciones son intercambiables)."""
from __future__ import annotations

from typing import List, Optional, Protocol, Sequence, Tuple

from ..domain import Certificado, Examen, Intento, Pregunta


class RepositorioInscripciones(Protocol):
    def registrar_inscripcion(self, usuario_id: str, evento_id: str, ticket_id: str) -> None: ...

    def esta_inscrito(self, usuario_id: str, evento_id: str) -> bool: ...


class RepositorioExamen(Protocol):
    def examen_de(self, evento_id: str) -> Optional[Examen]: ...

    def examen_por_id(self, examen_id: int) -> Optional[Examen]: ...

    def crear_examen(self, evento_id: str, titulo: str, puntaje_minimo: float, estado: str) -> Examen: ...

    def agregar_pregunta(self, examen_id: int, enunciado: str, punteo: float,
                         opciones: Sequence[Tuple[str, bool]]) -> Pregunta: ...

    def contar_preguntas(self, examen_id: int) -> int: ...

    def guardar_intento(self, intento: Intento) -> None: ...

    def intentos_de(self, usuario_id: str, evento_id: str) -> List[Intento]: ...


class RepositorioCertificados(Protocol):
    def guardar_certificado(self, certificado: Certificado) -> None: ...

    def certificado_de(self, usuario_id: str, evento_id: str) -> Optional[Certificado]: ...

    def buscar_certificado(self, codigo: str) -> Optional[Certificado]: ...

    def certificados_de_usuario(self, usuario_id: str) -> List[Certificado]: ...
