# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import notificaciones_pb2 as notificaciones__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in notificaciones_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NotificacionesServiceStub:
    """──────────────────────────────────────────────
    Servicio principal de notificaciones
    ──────────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnviarNotificacionRegistro = channel.unary_unary(
                '/notificaciones.NotificacionesService/EnviarNotificacionRegistro',
                request_serializer=notificaciones__pb2.EnviarNotificacionRegistroRequest.SerializeToString,
                response_deserializer=notificaciones__pb2.EnviarNotificacionRegistroResponse.FromString,
                _registered_method=True)
        self.EnviarNotificacionContenidoNuevo = channel.unary_unary(
                '/notificaciones.NotificacionesService/EnviarNotificacionContenidoNuevo',
                request_serializer=notificaciones__pb2.EnviarNotificacionContenidoNuevoRequest.SerializeToString,
                response_deserializer=notificaciones__pb2.EnviarNotificacionContenidoNuevoResponse.FromString,
                _registered_method=True)
        self.EnviarNotificacionAvisoGeneral = channel.unary_unary(
                '/notificaciones.NotificacionesService/EnviarNotificacionAvisoGeneral',
                request_serializer=notificaciones__pb2.EnviarNotificacionAvisoGeneralRequest.SerializeToString,
                response_deserializer=notificaciones__pb2.EnviarNotificacionAvisoGeneralResponse.FromString,
                _registered_method=True)
        self.ConsultarNotificaciones = channel.unary_unary(
                '/notificaciones.NotificacionesService/ConsultarNotificaciones',
                request_serializer=notificaciones__pb2.ConsultarNotificacionesRequest.SerializeToString,
                response_deserializer=notificaciones__pb2.ConsultarNotificacionesResponse.FromString,
                _registered_method=True)
        self.ConsultarAuditLogs = channel.unary_unary(
                '/notificaciones.NotificacionesService/ConsultarAuditLogs',
                request_serializer=notificaciones__pb2.ConsultarAuditLogsRequest.SerializeToString,
                response_deserializer=notificaciones__pb2.ConsultarAuditLogsResponse.FromString,
                _registered_method=True)


class NotificacionesServiceServicer:
    """──────────────────────────────────────────────
    Servicio principal de notificaciones
    ──────────────────────────────────────────────
    """

    def EnviarNotificacionRegistro(self, request, context):
        """Envío de correos
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnviarNotificacionContenidoNuevo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnviarNotificacionAvisoGeneral(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarNotificaciones(self, request, context):
        """Consultas
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarAuditLogs(self, request, context):
        """Auditoría
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotificacionesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnviarNotificacionRegistro': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarNotificacionRegistro,
                    request_deserializer=notificaciones__pb2.EnviarNotificacionRegistroRequest.FromString,
                    response_serializer=notificaciones__pb2.EnviarNotificacionRegistroResponse.SerializeToString,
            ),
            'EnviarNotificacionContenidoNuevo': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarNotificacionContenidoNuevo,
                    request_deserializer=notificaciones__pb2.EnviarNotificacionContenidoNuevoRequest.FromString,
                    response_serializer=notificaciones__pb2.EnviarNotificacionContenidoNuevoResponse.SerializeToString,
            ),
            'EnviarNotificacionAvisoGeneral': grpc.unary_unary_rpc_method_handler(
                    servicer.EnviarNotificacionAvisoGeneral,
                    request_deserializer=notificaciones__pb2.EnviarNotificacionAvisoGeneralRequest.FromString,
                    response_serializer=notificaciones__pb2.EnviarNotificacionAvisoGeneralResponse.SerializeToString,
            ),
            'ConsultarNotificaciones': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarNotificaciones,
                    request_deserializer=notificaciones__pb2.ConsultarNotificacionesRequest.FromString,
                    response_serializer=notificaciones__pb2.ConsultarNotificacionesResponse.SerializeToString,
            ),
            'ConsultarAuditLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarAuditLogs,
                    request_deserializer=notificaciones__pb2.ConsultarAuditLogsRequest.FromString,
                    response_serializer=notificaciones__pb2.ConsultarAuditLogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notificaciones.NotificacionesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('notificaciones.NotificacionesService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NotificacionesService:
    """──────────────────────────────────────────────
    Servicio principal de notificaciones
    ──────────────────────────────────────────────
    """

    @staticmethod
    def EnviarNotificacionRegistro(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notificaciones.NotificacionesService/EnviarNotificacionRegistro',
            notificaciones__pb2.EnviarNotificacionRegistroRequest.SerializeToString,
            notificaciones__pb2.EnviarNotificacionRegistroResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnviarNotificacionContenidoNuevo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notificaciones.NotificacionesService/EnviarNotificacionContenidoNuevo',
            notificaciones__pb2.EnviarNotificacionContenidoNuevoRequest.SerializeToString,
            notificaciones__pb2.EnviarNotificacionContenidoNuevoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnviarNotificacionAvisoGeneral(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notificaciones.NotificacionesService/EnviarNotificacionAvisoGeneral',
            notificaciones__pb2.EnviarNotificacionAvisoGeneralRequest.SerializeToString,
            notificaciones__pb2.EnviarNotificacionAvisoGeneralResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarNotificaciones(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notificaciones.NotificacionesService/ConsultarNotificaciones',
            notificaciones__pb2.ConsultarNotificacionesRequest.SerializeToString,
            notificaciones__pb2.ConsultarNotificacionesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarAuditLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notificaciones.NotificacionesService/ConsultarAuditLogs',
            notificaciones__pb2.ConsultarAuditLogsRequest.SerializeToString,
            notificaciones__pb2.ConsultarAuditLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
