// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: grabaciones.proto

package grabaciones

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GrabacionesService_ConsultarCatalogoClases_FullMethodName        = "/grabaciones.GrabacionesService/ConsultarCatalogoClases"
	GrabacionesService_CrearUnidad_FullMethodName                    = "/grabaciones.GrabacionesService/CrearUnidad"
	GrabacionesService_EditarUnidad_FullMethodName                   = "/grabaciones.GrabacionesService/EditarUnidad"
	GrabacionesService_EliminarUnidad_FullMethodName                 = "/grabaciones.GrabacionesService/EliminarUnidad"
	GrabacionesService_ConsultarUnidades_FullMethodName              = "/grabaciones.GrabacionesService/ConsultarUnidades"
	GrabacionesService_CrearTema_FullMethodName                      = "/grabaciones.GrabacionesService/CrearTema"
	GrabacionesService_EditarTema_FullMethodName                     = "/grabaciones.GrabacionesService/EditarTema"
	GrabacionesService_EliminarTema_FullMethodName                   = "/grabaciones.GrabacionesService/EliminarTema"
	GrabacionesService_ConsultarTemas_FullMethodName                 = "/grabaciones.GrabacionesService/ConsultarTemas"
	GrabacionesService_CrearClaseGrabada_FullMethodName              = "/grabaciones.GrabacionesService/CrearClaseGrabada"
	GrabacionesService_CargaMasivaClases_FullMethodName              = "/grabaciones.GrabacionesService/CargaMasivaClases"
	GrabacionesService_EditarClaseGrabada_FullMethodName             = "/grabaciones.GrabacionesService/EditarClaseGrabada"
	GrabacionesService_EliminarClaseGrabada_FullMethodName           = "/grabaciones.GrabacionesService/EliminarClaseGrabada"
	GrabacionesService_BusquedaAvanzada_FullMethodName               = "/grabaciones.GrabacionesService/BusquedaAvanzada"
	GrabacionesService_ObtenerDetalleClaseGrabada_FullMethodName     = "/grabaciones.GrabacionesService/ObtenerDetalleClaseGrabada"
	GrabacionesService_ObtenerEnlaceClaseGrabada_FullMethodName      = "/grabaciones.GrabacionesService/ObtenerEnlaceClaseGrabada"
	GrabacionesService_AsignarDocente_FullMethodName                 = "/grabaciones.GrabacionesService/AsignarDocente"
	GrabacionesService_DesasignarDocente_FullMethodName              = "/grabaciones.GrabacionesService/DesasignarDocente"
	GrabacionesService_AsignarAuxiliar_FullMethodName                = "/grabaciones.GrabacionesService/AsignarAuxiliar"
	GrabacionesService_DesasignarAuxiliar_FullMethodName             = "/grabaciones.GrabacionesService/DesasignarAuxiliar"
	GrabacionesService_AsignarMaterialApoyo_FullMethodName           = "/grabaciones.GrabacionesService/AsignarMaterialApoyo"
	GrabacionesService_DesasignarMaterialApoyo_FullMethodName        = "/grabaciones.GrabacionesService/DesasignarMaterialApoyo"
	GrabacionesService_AsignarTemaClaseGrabada_FullMethodName        = "/grabaciones.GrabacionesService/AsignarTemaClaseGrabada"
	GrabacionesService_DesasignarTemaClaseGrabada_FullMethodName     = "/grabaciones.GrabacionesService/DesasignarTemaClaseGrabada"
	GrabacionesService_ConsultarParticipantesClase_FullMethodName    = "/grabaciones.GrabacionesService/ConsultarParticipantesClase"
	GrabacionesService_CrearCapitulo_FullMethodName                  = "/grabaciones.GrabacionesService/CrearCapitulo"
	GrabacionesService_EditarCapitulo_FullMethodName                 = "/grabaciones.GrabacionesService/EditarCapitulo"
	GrabacionesService_EliminarCapitulo_FullMethodName               = "/grabaciones.GrabacionesService/EliminarCapitulo"
	GrabacionesService_ConsultarCapitulosClase_FullMethodName        = "/grabaciones.GrabacionesService/ConsultarCapitulosClase"
	GrabacionesService_ConsultarPlaylistsUsuario_FullMethodName      = "/grabaciones.GrabacionesService/ConsultarPlaylistsUsuario"
	GrabacionesService_ConsultarPlaylistPorHash_FullMethodName       = "/grabaciones.GrabacionesService/ConsultarPlaylistPorHash"
	GrabacionesService_ConsultarVideosPlaylist_FullMethodName        = "/grabaciones.GrabacionesService/ConsultarVideosPlaylist"
	GrabacionesService_ConsultarVideosPlaylistPorHash_FullMethodName = "/grabaciones.GrabacionesService/ConsultarVideosPlaylistPorHash"
	GrabacionesService_CrearPlaylist_FullMethodName                  = "/grabaciones.GrabacionesService/CrearPlaylist"
	GrabacionesService_EliminarPlaylist_FullMethodName               = "/grabaciones.GrabacionesService/EliminarPlaylist"
	GrabacionesService_CambiarVisibilidadPlaylist_FullMethodName     = "/grabaciones.GrabacionesService/CambiarVisibilidadPlaylist"
	GrabacionesService_AgregarVideoPlaylist_FullMethodName           = "/grabaciones.GrabacionesService/AgregarVideoPlaylist"
	GrabacionesService_EliminarVideoPlaylist_FullMethodName          = "/grabaciones.GrabacionesService/EliminarVideoPlaylist"
	GrabacionesService_GenerarLinkPlaylist_FullMethodName            = "/grabaciones.GrabacionesService/GenerarLinkPlaylist"
	GrabacionesService_ConsultarAuditLogs_FullMethodName             = "/grabaciones.GrabacionesService/ConsultarAuditLogs"
)

// GrabacionesServiceClient is the client API for GrabacionesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ──────────────────────────────────────────────
// Servicio principal de grabaciones
// ──────────────────────────────────────────────
type GrabacionesServiceClient interface {
	// Catálogo
	ConsultarCatalogoClases(ctx context.Context, in *ConsultarCatalogoClasesRequest, opts ...grpc.CallOption) (*ConsultarCatalogoClasesResponse, error)
	// Unidades y temas
	CrearUnidad(ctx context.Context, in *CrearUnidadRequest, opts ...grpc.CallOption) (*CrearUnidadResponse, error)
	EditarUnidad(ctx context.Context, in *EditarUnidadRequest, opts ...grpc.CallOption) (*EditarUnidadResponse, error)
	EliminarUnidad(ctx context.Context, in *EliminarUnidadRequest, opts ...grpc.CallOption) (*EliminarUnidadResponse, error)
	ConsultarUnidades(ctx context.Context, in *ConsultarUnidadesRequest, opts ...grpc.CallOption) (*ConsultarUnidadesResponse, error)
	CrearTema(ctx context.Context, in *CrearTemaRequest, opts ...grpc.CallOption) (*CrearTemaResponse, error)
	EditarTema(ctx context.Context, in *EditarTemaRequest, opts ...grpc.CallOption) (*EditarTemaResponse, error)
	EliminarTema(ctx context.Context, in *EliminarTemaRequest, opts ...grpc.CallOption) (*EliminarTemaResponse, error)
	ConsultarTemas(ctx context.Context, in *ConsultarTemasRequest, opts ...grpc.CallOption) (*ConsultarTemasResponse, error)
	// Clases grabadas
	CrearClaseGrabada(ctx context.Context, in *CrearClaseGrabadaRequest, opts ...grpc.CallOption) (*CrearClaseGrabadaResponse, error)
	CargaMasivaClases(ctx context.Context, in *BatchCrearClaseRequest, opts ...grpc.CallOption) (*BatchCrearClaseResponse, error)
	EditarClaseGrabada(ctx context.Context, in *EditarClaseGrabadaRequest, opts ...grpc.CallOption) (*EditarClaseGrabadaResponse, error)
	EliminarClaseGrabada(ctx context.Context, in *EliminarClaseGrabadaRequest, opts ...grpc.CallOption) (*EliminarClaseGrabadaResponse, error)
	BusquedaAvanzada(ctx context.Context, in *BusquedaAvanzadaRequest, opts ...grpc.CallOption) (*BusquedaAvanzadaResponse, error)
	ObtenerDetalleClaseGrabada(ctx context.Context, in *ObtenerDetalleClaseGrabadaRequest, opts ...grpc.CallOption) (*ObtenerDetalleClaseGrabadaResponse, error)
	ObtenerEnlaceClaseGrabada(ctx context.Context, in *ObtenerEnlaceClaseGrabadaRequest, opts ...grpc.CallOption) (*ObtenerEnlaceClaseGrabadaResponse, error)
	// Asignaciones
	AsignarDocente(ctx context.Context, in *AsignarDocenteRequest, opts ...grpc.CallOption) (*AsignarDocenteResponse, error)
	DesasignarDocente(ctx context.Context, in *DesasignarDocenteRequest, opts ...grpc.CallOption) (*DesasignarDocenteResponse, error)
	AsignarAuxiliar(ctx context.Context, in *AsignarAuxiliarRequest, opts ...grpc.CallOption) (*AsignarAuxiliarResponse, error)
	DesasignarAuxiliar(ctx context.Context, in *DesasignarAuxiliarRequest, opts ...grpc.CallOption) (*DesasignarAuxiliarResponse, error)
	AsignarMaterialApoyo(ctx context.Context, in *AsignarMaterialApoyoRequest, opts ...grpc.CallOption) (*AsignarMaterialApoyoResponse, error)
	DesasignarMaterialApoyo(ctx context.Context, in *DesasignarMaterialApoyoRequest, opts ...grpc.CallOption) (*DesasignarMaterialApoyoResponse, error)
	AsignarTemaClaseGrabada(ctx context.Context, in *AsignarTemaClaseGrabadaRequest, opts ...grpc.CallOption) (*AsignarTemaClaseGrabadaResponse, error)
	DesasignarTemaClaseGrabada(ctx context.Context, in *DesasignarTemaClaseGrabadaRequest, opts ...grpc.CallOption) (*DesasignarTemaClaseGrabadaResponse, error)
	ConsultarParticipantesClase(ctx context.Context, in *ConsultarParticipantesClaseRequest, opts ...grpc.CallOption) (*ConsultarParticipantesClaseResponse, error)
	// HeinzGomez - Segmentación por capítulos (video chapters)
	CrearCapitulo(ctx context.Context, in *CrearCapituloRequest, opts ...grpc.CallOption) (*CrearCapituloResponse, error)
	EditarCapitulo(ctx context.Context, in *EditarCapituloRequest, opts ...grpc.CallOption) (*EditarCapituloResponse, error)
	EliminarCapitulo(ctx context.Context, in *EliminarCapituloRequest, opts ...grpc.CallOption) (*EliminarCapituloResponse, error)
	ConsultarCapitulosClase(ctx context.Context, in *ConsultarCapitulosClaseRequest, opts ...grpc.CallOption) (*ConsultarCapitulosClaseResponse, error)
	// Playlists
	ConsultarPlaylistsUsuario(ctx context.Context, in *ConsultarPlaylistsUsuarioRequest, opts ...grpc.CallOption) (*ConsultarPlaylistsUsuarioResponse, error)
	ConsultarPlaylistPorHash(ctx context.Context, in *ConsultarPlaylistPorHashRequest, opts ...grpc.CallOption) (*ConsultarPlaylistPorHashResponse, error)
	ConsultarVideosPlaylist(ctx context.Context, in *ConsultarVideosPlaylistRequest, opts ...grpc.CallOption) (*ConsultarVideosPlaylistResponse, error)
	ConsultarVideosPlaylistPorHash(ctx context.Context, in *ConsultarVideosPlaylistPorHashRequest, opts ...grpc.CallOption) (*ConsultarVideosPlaylistPorHashResponse, error)
	CrearPlaylist(ctx context.Context, in *CrearPlaylistRequest, opts ...grpc.CallOption) (*CrearPlaylistResponse, error)
	EliminarPlaylist(ctx context.Context, in *EliminarPlaylistRequest, opts ...grpc.CallOption) (*EliminarPlaylistResponse, error)
	CambiarVisibilidadPlaylist(ctx context.Context, in *CambiarVisibilidadPlaylistRequest, opts ...grpc.CallOption) (*CambiarVisibilidadPlaylistResponse, error)
	AgregarVideoPlaylist(ctx context.Context, in *AgregarVideoPlaylistRequest, opts ...grpc.CallOption) (*AgregarVideoPlaylistResponse, error)
	EliminarVideoPlaylist(ctx context.Context, in *EliminarVideoPlaylistRequest, opts ...grpc.CallOption) (*EliminarVideoPlaylistResponse, error)
	GenerarLinkPlaylist(ctx context.Context, in *GenerarLinkPlaylistRequest, opts ...grpc.CallOption) (*GenerarLinkPlaylistResponse, error)
	// Auditoría
	ConsultarAuditLogs(ctx context.Context, in *ConsultarAuditLogsRequest, opts ...grpc.CallOption) (*ConsultarAuditLogsResponse, error)
}

type grabacionesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGrabacionesServiceClient(cc grpc.ClientConnInterface) GrabacionesServiceClient {
	return &grabacionesServiceClient{cc}
}

func (c *grabacionesServiceClient) ConsultarCatalogoClases(ctx context.Context, in *ConsultarCatalogoClasesRequest, opts ...grpc.CallOption) (*ConsultarCatalogoClasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarCatalogoClasesResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_ConsultarCatalogoClases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) CrearUnidad(ctx context.Context, in *CrearUnidadRequest, opts ...grpc.CallOption) (*CrearUnidadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrearUnidadResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_CrearUnidad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) EditarUnidad(ctx context.Context, in *EditarUnidadRequest, opts ...grpc.CallOption) (*EditarUnidadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditarUnidadResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_EditarUnidad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) EliminarUnidad(ctx context.Context, in *EliminarUnidadRequest, opts ...grpc.CallOption) (*EliminarUnidadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EliminarUnidadResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_EliminarUnidad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) ConsultarUnidades(ctx context.Context, in *ConsultarUnidadesRequest, opts ...grpc.CallOption) (*ConsultarUnidadesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarUnidadesResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_ConsultarUnidades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) CrearTema(ctx context.Context, in *CrearTemaRequest, opts ...grpc.CallOption) (*CrearTemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrearTemaResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_CrearTema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) EditarTema(ctx context.Context, in *EditarTemaRequest, opts ...grpc.CallOption) (*EditarTemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditarTemaResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_EditarTema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) EliminarTema(ctx context.Context, in *EliminarTemaRequest, opts ...grpc.CallOption) (*EliminarTemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EliminarTemaResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_EliminarTema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) ConsultarTemas(ctx context.Context, in *ConsultarTemasRequest, opts ...grpc.CallOption) (*ConsultarTemasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarTemasResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_ConsultarTemas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) CrearClaseGrabada(ctx context.Context, in *CrearClaseGrabadaRequest, opts ...grpc.CallOption) (*CrearClaseGrabadaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrearClaseGrabadaResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_CrearClaseGrabada_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) CargaMasivaClases(ctx context.Context, in *BatchCrearClaseRequest, opts ...grpc.CallOption) (*BatchCrearClaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCrearClaseResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_CargaMasivaClases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) EditarClaseGrabada(ctx context.Context, in *EditarClaseGrabadaRequest, opts ...grpc.CallOption) (*EditarClaseGrabadaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditarClaseGrabadaResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_EditarClaseGrabada_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) EliminarClaseGrabada(ctx context.Context, in *EliminarClaseGrabadaRequest, opts ...grpc.CallOption) (*EliminarClaseGrabadaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EliminarClaseGrabadaResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_EliminarClaseGrabada_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) BusquedaAvanzada(ctx context.Context, in *BusquedaAvanzadaRequest, opts ...grpc.CallOption) (*BusquedaAvanzadaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BusquedaAvanzadaResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_BusquedaAvanzada_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) ObtenerDetalleClaseGrabada(ctx context.Context, in *ObtenerDetalleClaseGrabadaRequest, opts ...grpc.CallOption) (*ObtenerDetalleClaseGrabadaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObtenerDetalleClaseGrabadaResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_ObtenerDetalleClaseGrabada_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) ObtenerEnlaceClaseGrabada(ctx context.Context, in *ObtenerEnlaceClaseGrabadaRequest, opts ...grpc.CallOption) (*ObtenerEnlaceClaseGrabadaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObtenerEnlaceClaseGrabadaResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_ObtenerEnlaceClaseGrabada_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) AsignarDocente(ctx context.Context, in *AsignarDocenteRequest, opts ...grpc.CallOption) (*AsignarDocenteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AsignarDocenteResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_AsignarDocente_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) DesasignarDocente(ctx context.Context, in *DesasignarDocenteRequest, opts ...grpc.CallOption) (*DesasignarDocenteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesasignarDocenteResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_DesasignarDocente_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) AsignarAuxiliar(ctx context.Context, in *AsignarAuxiliarRequest, opts ...grpc.CallOption) (*AsignarAuxiliarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AsignarAuxiliarResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_AsignarAuxiliar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) DesasignarAuxiliar(ctx context.Context, in *DesasignarAuxiliarRequest, opts ...grpc.CallOption) (*DesasignarAuxiliarResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesasignarAuxiliarResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_DesasignarAuxiliar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) AsignarMaterialApoyo(ctx context.Context, in *AsignarMaterialApoyoRequest, opts ...grpc.CallOption) (*AsignarMaterialApoyoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AsignarMaterialApoyoResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_AsignarMaterialApoyo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) DesasignarMaterialApoyo(ctx context.Context, in *DesasignarMaterialApoyoRequest, opts ...grpc.CallOption) (*DesasignarMaterialApoyoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesasignarMaterialApoyoResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_DesasignarMaterialApoyo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) AsignarTemaClaseGrabada(ctx context.Context, in *AsignarTemaClaseGrabadaRequest, opts ...grpc.CallOption) (*AsignarTemaClaseGrabadaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AsignarTemaClaseGrabadaResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_AsignarTemaClaseGrabada_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) DesasignarTemaClaseGrabada(ctx context.Context, in *DesasignarTemaClaseGrabadaRequest, opts ...grpc.CallOption) (*DesasignarTemaClaseGrabadaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DesasignarTemaClaseGrabadaResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_DesasignarTemaClaseGrabada_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) ConsultarParticipantesClase(ctx context.Context, in *ConsultarParticipantesClaseRequest, opts ...grpc.CallOption) (*ConsultarParticipantesClaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarParticipantesClaseResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_ConsultarParticipantesClase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) CrearCapitulo(ctx context.Context, in *CrearCapituloRequest, opts ...grpc.CallOption) (*CrearCapituloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrearCapituloResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_CrearCapitulo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) EditarCapitulo(ctx context.Context, in *EditarCapituloRequest, opts ...grpc.CallOption) (*EditarCapituloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EditarCapituloResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_EditarCapitulo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) EliminarCapitulo(ctx context.Context, in *EliminarCapituloRequest, opts ...grpc.CallOption) (*EliminarCapituloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EliminarCapituloResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_EliminarCapitulo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) ConsultarCapitulosClase(ctx context.Context, in *ConsultarCapitulosClaseRequest, opts ...grpc.CallOption) (*ConsultarCapitulosClaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarCapitulosClaseResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_ConsultarCapitulosClase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) ConsultarPlaylistsUsuario(ctx context.Context, in *ConsultarPlaylistsUsuarioRequest, opts ...grpc.CallOption) (*ConsultarPlaylistsUsuarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarPlaylistsUsuarioResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_ConsultarPlaylistsUsuario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) ConsultarPlaylistPorHash(ctx context.Context, in *ConsultarPlaylistPorHashRequest, opts ...grpc.CallOption) (*ConsultarPlaylistPorHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarPlaylistPorHashResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_ConsultarPlaylistPorHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) ConsultarVideosPlaylist(ctx context.Context, in *ConsultarVideosPlaylistRequest, opts ...grpc.CallOption) (*ConsultarVideosPlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarVideosPlaylistResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_ConsultarVideosPlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) ConsultarVideosPlaylistPorHash(ctx context.Context, in *ConsultarVideosPlaylistPorHashRequest, opts ...grpc.CallOption) (*ConsultarVideosPlaylistPorHashResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarVideosPlaylistPorHashResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_ConsultarVideosPlaylistPorHash_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) CrearPlaylist(ctx context.Context, in *CrearPlaylistRequest, opts ...grpc.CallOption) (*CrearPlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CrearPlaylistResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_CrearPlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) EliminarPlaylist(ctx context.Context, in *EliminarPlaylistRequest, opts ...grpc.CallOption) (*EliminarPlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EliminarPlaylistResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_EliminarPlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) CambiarVisibilidadPlaylist(ctx context.Context, in *CambiarVisibilidadPlaylistRequest, opts ...grpc.CallOption) (*CambiarVisibilidadPlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CambiarVisibilidadPlaylistResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_CambiarVisibilidadPlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) AgregarVideoPlaylist(ctx context.Context, in *AgregarVideoPlaylistRequest, opts ...grpc.CallOption) (*AgregarVideoPlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AgregarVideoPlaylistResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_AgregarVideoPlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) EliminarVideoPlaylist(ctx context.Context, in *EliminarVideoPlaylistRequest, opts ...grpc.CallOption) (*EliminarVideoPlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EliminarVideoPlaylistResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_EliminarVideoPlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) GenerarLinkPlaylist(ctx context.Context, in *GenerarLinkPlaylistRequest, opts ...grpc.CallOption) (*GenerarLinkPlaylistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerarLinkPlaylistResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_GenerarLinkPlaylist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *grabacionesServiceClient) ConsultarAuditLogs(ctx context.Context, in *ConsultarAuditLogsRequest, opts ...grpc.CallOption) (*ConsultarAuditLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarAuditLogsResponse)
	err := c.cc.Invoke(ctx, GrabacionesService_ConsultarAuditLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GrabacionesServiceServer is the server API for GrabacionesService service.
// All implementations must embed UnimplementedGrabacionesServiceServer
// for forward compatibility.
//
// ──────────────────────────────────────────────
// Servicio principal de grabaciones
// ──────────────────────────────────────────────
type GrabacionesServiceServer interface {
	// Catálogo
	ConsultarCatalogoClases(context.Context, *ConsultarCatalogoClasesRequest) (*ConsultarCatalogoClasesResponse, error)
	// Unidades y temas
	CrearUnidad(context.Context, *CrearUnidadRequest) (*CrearUnidadResponse, error)
	EditarUnidad(context.Context, *EditarUnidadRequest) (*EditarUnidadResponse, error)
	EliminarUnidad(context.Context, *EliminarUnidadRequest) (*EliminarUnidadResponse, error)
	ConsultarUnidades(context.Context, *ConsultarUnidadesRequest) (*ConsultarUnidadesResponse, error)
	CrearTema(context.Context, *CrearTemaRequest) (*CrearTemaResponse, error)
	EditarTema(context.Context, *EditarTemaRequest) (*EditarTemaResponse, error)
	EliminarTema(context.Context, *EliminarTemaRequest) (*EliminarTemaResponse, error)
	ConsultarTemas(context.Context, *ConsultarTemasRequest) (*ConsultarTemasResponse, error)
	// Clases grabadas
	CrearClaseGrabada(context.Context, *CrearClaseGrabadaRequest) (*CrearClaseGrabadaResponse, error)
	CargaMasivaClases(context.Context, *BatchCrearClaseRequest) (*BatchCrearClaseResponse, error)
	EditarClaseGrabada(context.Context, *EditarClaseGrabadaRequest) (*EditarClaseGrabadaResponse, error)
	EliminarClaseGrabada(context.Context, *EliminarClaseGrabadaRequest) (*EliminarClaseGrabadaResponse, error)
	BusquedaAvanzada(context.Context, *BusquedaAvanzadaRequest) (*BusquedaAvanzadaResponse, error)
	ObtenerDetalleClaseGrabada(context.Context, *ObtenerDetalleClaseGrabadaRequest) (*ObtenerDetalleClaseGrabadaResponse, error)
	ObtenerEnlaceClaseGrabada(context.Context, *ObtenerEnlaceClaseGrabadaRequest) (*ObtenerEnlaceClaseGrabadaResponse, error)
	// Asignaciones
	AsignarDocente(context.Context, *AsignarDocenteRequest) (*AsignarDocenteResponse, error)
	DesasignarDocente(context.Context, *DesasignarDocenteRequest) (*DesasignarDocenteResponse, error)
	AsignarAuxiliar(context.Context, *AsignarAuxiliarRequest) (*AsignarAuxiliarResponse, error)
	DesasignarAuxiliar(context.Context, *DesasignarAuxiliarRequest) (*DesasignarAuxiliarResponse, error)
	AsignarMaterialApoyo(context.Context, *AsignarMaterialApoyoRequest) (*AsignarMaterialApoyoResponse, error)
	DesasignarMaterialApoyo(context.Context, *DesasignarMaterialApoyoRequest) (*DesasignarMaterialApoyoResponse, error)
	AsignarTemaClaseGrabada(context.Context, *AsignarTemaClaseGrabadaRequest) (*AsignarTemaClaseGrabadaResponse, error)
	DesasignarTemaClaseGrabada(context.Context, *DesasignarTemaClaseGrabadaRequest) (*DesasignarTemaClaseGrabadaResponse, error)
	ConsultarParticipantesClase(context.Context, *ConsultarParticipantesClaseRequest) (*ConsultarParticipantesClaseResponse, error)
	// HeinzGomez - Segmentación por capítulos (video chapters)
	CrearCapitulo(context.Context, *CrearCapituloRequest) (*CrearCapituloResponse, error)
	EditarCapitulo(context.Context, *EditarCapituloRequest) (*EditarCapituloResponse, error)
	EliminarCapitulo(context.Context, *EliminarCapituloRequest) (*EliminarCapituloResponse, error)
	ConsultarCapitulosClase(context.Context, *ConsultarCapitulosClaseRequest) (*ConsultarCapitulosClaseResponse, error)
	// Playlists
	ConsultarPlaylistsUsuario(context.Context, *ConsultarPlaylistsUsuarioRequest) (*ConsultarPlaylistsUsuarioResponse, error)
	ConsultarPlaylistPorHash(context.Context, *ConsultarPlaylistPorHashRequest) (*ConsultarPlaylistPorHashResponse, error)
	ConsultarVideosPlaylist(context.Context, *ConsultarVideosPlaylistRequest) (*ConsultarVideosPlaylistResponse, error)
	ConsultarVideosPlaylistPorHash(context.Context, *ConsultarVideosPlaylistPorHashRequest) (*ConsultarVideosPlaylistPorHashResponse, error)
	CrearPlaylist(context.Context, *CrearPlaylistRequest) (*CrearPlaylistResponse, error)
	EliminarPlaylist(context.Context, *EliminarPlaylistRequest) (*EliminarPlaylistResponse, error)
	CambiarVisibilidadPlaylist(context.Context, *CambiarVisibilidadPlaylistRequest) (*CambiarVisibilidadPlaylistResponse, error)
	AgregarVideoPlaylist(context.Context, *AgregarVideoPlaylistRequest) (*AgregarVideoPlaylistResponse, error)
	EliminarVideoPlaylist(context.Context, *EliminarVideoPlaylistRequest) (*EliminarVideoPlaylistResponse, error)
	GenerarLinkPlaylist(context.Context, *GenerarLinkPlaylistRequest) (*GenerarLinkPlaylistResponse, error)
	// Auditoría
	ConsultarAuditLogs(context.Context, *ConsultarAuditLogsRequest) (*ConsultarAuditLogsResponse, error)
	mustEmbedUnimplementedGrabacionesServiceServer()
}

// UnimplementedGrabacionesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGrabacionesServiceServer struct{}

func (UnimplementedGrabacionesServiceServer) ConsultarCatalogoClases(context.Context, *ConsultarCatalogoClasesRequest) (*ConsultarCatalogoClasesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarCatalogoClases not implemented")
}
func (UnimplementedGrabacionesServiceServer) CrearUnidad(context.Context, *CrearUnidadRequest) (*CrearUnidadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearUnidad not implemented")
}
func (UnimplementedGrabacionesServiceServer) EditarUnidad(context.Context, *EditarUnidadRequest) (*EditarUnidadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditarUnidad not implemented")
}
func (UnimplementedGrabacionesServiceServer) EliminarUnidad(context.Context, *EliminarUnidadRequest) (*EliminarUnidadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EliminarUnidad not implemented")
}
func (UnimplementedGrabacionesServiceServer) ConsultarUnidades(context.Context, *ConsultarUnidadesRequest) (*ConsultarUnidadesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarUnidades not implemented")
}
func (UnimplementedGrabacionesServiceServer) CrearTema(context.Context, *CrearTemaRequest) (*CrearTemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearTema not implemented")
}
func (UnimplementedGrabacionesServiceServer) EditarTema(context.Context, *EditarTemaRequest) (*EditarTemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditarTema not implemented")
}
func (UnimplementedGrabacionesServiceServer) EliminarTema(context.Context, *EliminarTemaRequest) (*EliminarTemaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EliminarTema not implemented")
}
func (UnimplementedGrabacionesServiceServer) ConsultarTemas(context.Context, *ConsultarTemasRequest) (*ConsultarTemasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarTemas not implemented")
}
func (UnimplementedGrabacionesServiceServer) CrearClaseGrabada(context.Context, *CrearClaseGrabadaRequest) (*CrearClaseGrabadaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearClaseGrabada not implemented")
}
func (UnimplementedGrabacionesServiceServer) CargaMasivaClases(context.Context, *BatchCrearClaseRequest) (*BatchCrearClaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CargaMasivaClases not implemented")
}
func (UnimplementedGrabacionesServiceServer) EditarClaseGrabada(context.Context, *EditarClaseGrabadaRequest) (*EditarClaseGrabadaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditarClaseGrabada not implemented")
}
func (UnimplementedGrabacionesServiceServer) EliminarClaseGrabada(context.Context, *EliminarClaseGrabadaRequest) (*EliminarClaseGrabadaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EliminarClaseGrabada not implemented")
}
func (UnimplementedGrabacionesServiceServer) BusquedaAvanzada(context.Context, *BusquedaAvanzadaRequest) (*BusquedaAvanzadaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BusquedaAvanzada not implemented")
}
func (UnimplementedGrabacionesServiceServer) ObtenerDetalleClaseGrabada(context.Context, *ObtenerDetalleClaseGrabadaRequest) (*ObtenerDetalleClaseGrabadaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerDetalleClaseGrabada not implemented")
}
func (UnimplementedGrabacionesServiceServer) ObtenerEnlaceClaseGrabada(context.Context, *ObtenerEnlaceClaseGrabadaRequest) (*ObtenerEnlaceClaseGrabadaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerEnlaceClaseGrabada not implemented")
}
func (UnimplementedGrabacionesServiceServer) AsignarDocente(context.Context, *AsignarDocenteRequest) (*AsignarDocenteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AsignarDocente not implemented")
}
func (UnimplementedGrabacionesServiceServer) DesasignarDocente(context.Context, *DesasignarDocenteRequest) (*DesasignarDocenteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DesasignarDocente not implemented")
}
func (UnimplementedGrabacionesServiceServer) AsignarAuxiliar(context.Context, *AsignarAuxiliarRequest) (*AsignarAuxiliarResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AsignarAuxiliar not implemented")
}
func (UnimplementedGrabacionesServiceServer) DesasignarAuxiliar(context.Context, *DesasignarAuxiliarRequest) (*DesasignarAuxiliarResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DesasignarAuxiliar not implemented")
}
func (UnimplementedGrabacionesServiceServer) AsignarMaterialApoyo(context.Context, *AsignarMaterialApoyoRequest) (*AsignarMaterialApoyoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AsignarMaterialApoyo not implemented")
}
func (UnimplementedGrabacionesServiceServer) DesasignarMaterialApoyo(context.Context, *DesasignarMaterialApoyoRequest) (*DesasignarMaterialApoyoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DesasignarMaterialApoyo not implemented")
}
func (UnimplementedGrabacionesServiceServer) AsignarTemaClaseGrabada(context.Context, *AsignarTemaClaseGrabadaRequest) (*AsignarTemaClaseGrabadaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AsignarTemaClaseGrabada not implemented")
}
func (UnimplementedGrabacionesServiceServer) DesasignarTemaClaseGrabada(context.Context, *DesasignarTemaClaseGrabadaRequest) (*DesasignarTemaClaseGrabadaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DesasignarTemaClaseGrabada not implemented")
}
func (UnimplementedGrabacionesServiceServer) ConsultarParticipantesClase(context.Context, *ConsultarParticipantesClaseRequest) (*ConsultarParticipantesClaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarParticipantesClase not implemented")
}
func (UnimplementedGrabacionesServiceServer) CrearCapitulo(context.Context, *CrearCapituloRequest) (*CrearCapituloResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearCapitulo not implemented")
}
func (UnimplementedGrabacionesServiceServer) EditarCapitulo(context.Context, *EditarCapituloRequest) (*EditarCapituloResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EditarCapitulo not implemented")
}
func (UnimplementedGrabacionesServiceServer) EliminarCapitulo(context.Context, *EliminarCapituloRequest) (*EliminarCapituloResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EliminarCapitulo not implemented")
}
func (UnimplementedGrabacionesServiceServer) ConsultarCapitulosClase(context.Context, *ConsultarCapitulosClaseRequest) (*ConsultarCapitulosClaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarCapitulosClase not implemented")
}
func (UnimplementedGrabacionesServiceServer) ConsultarPlaylistsUsuario(context.Context, *ConsultarPlaylistsUsuarioRequest) (*ConsultarPlaylistsUsuarioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarPlaylistsUsuario not implemented")
}
func (UnimplementedGrabacionesServiceServer) ConsultarPlaylistPorHash(context.Context, *ConsultarPlaylistPorHashRequest) (*ConsultarPlaylistPorHashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarPlaylistPorHash not implemented")
}
func (UnimplementedGrabacionesServiceServer) ConsultarVideosPlaylist(context.Context, *ConsultarVideosPlaylistRequest) (*ConsultarVideosPlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarVideosPlaylist not implemented")
}
func (UnimplementedGrabacionesServiceServer) ConsultarVideosPlaylistPorHash(context.Context, *ConsultarVideosPlaylistPorHashRequest) (*ConsultarVideosPlaylistPorHashResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarVideosPlaylistPorHash not implemented")
}
func (UnimplementedGrabacionesServiceServer) CrearPlaylist(context.Context, *CrearPlaylistRequest) (*CrearPlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CrearPlaylist not implemented")
}
func (UnimplementedGrabacionesServiceServer) EliminarPlaylist(context.Context, *EliminarPlaylistRequest) (*EliminarPlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EliminarPlaylist not implemented")
}
func (UnimplementedGrabacionesServiceServer) CambiarVisibilidadPlaylist(context.Context, *CambiarVisibilidadPlaylistRequest) (*CambiarVisibilidadPlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CambiarVisibilidadPlaylist not implemented")
}
func (UnimplementedGrabacionesServiceServer) AgregarVideoPlaylist(context.Context, *AgregarVideoPlaylistRequest) (*AgregarVideoPlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AgregarVideoPlaylist not implemented")
}
func (UnimplementedGrabacionesServiceServer) EliminarVideoPlaylist(context.Context, *EliminarVideoPlaylistRequest) (*EliminarVideoPlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EliminarVideoPlaylist not implemented")
}
func (UnimplementedGrabacionesServiceServer) GenerarLinkPlaylist(context.Context, *GenerarLinkPlaylistRequest) (*GenerarLinkPlaylistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerarLinkPlaylist not implemented")
}
func (UnimplementedGrabacionesServiceServer) ConsultarAuditLogs(context.Context, *ConsultarAuditLogsRequest) (*ConsultarAuditLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarAuditLogs not implemented")
}
func (UnimplementedGrabacionesServiceServer) mustEmbedUnimplementedGrabacionesServiceServer() {}
func (UnimplementedGrabacionesServiceServer) testEmbeddedByValue()                            {}

// UnsafeGrabacionesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GrabacionesServiceServer will
// result in compilation errors.
type UnsafeGrabacionesServiceServer interface {
	mustEmbedUnimplementedGrabacionesServiceServer()
}

func RegisterGrabacionesServiceServer(s grpc.ServiceRegistrar, srv GrabacionesServiceServer) {
	// If the following call panics, it indicates UnimplementedGrabacionesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GrabacionesService_ServiceDesc, srv)
}

func _GrabacionesService_ConsultarCatalogoClases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarCatalogoClasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).ConsultarCatalogoClases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_ConsultarCatalogoClases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).ConsultarCatalogoClases(ctx, req.(*ConsultarCatalogoClasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_CrearUnidad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearUnidadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).CrearUnidad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_CrearUnidad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).CrearUnidad(ctx, req.(*CrearUnidadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_EditarUnidad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditarUnidadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).EditarUnidad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_EditarUnidad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).EditarUnidad(ctx, req.(*EditarUnidadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_EliminarUnidad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EliminarUnidadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).EliminarUnidad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_EliminarUnidad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).EliminarUnidad(ctx, req.(*EliminarUnidadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_ConsultarUnidades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarUnidadesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).ConsultarUnidades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_ConsultarUnidades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).ConsultarUnidades(ctx, req.(*ConsultarUnidadesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_CrearTema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearTemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).CrearTema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_CrearTema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).CrearTema(ctx, req.(*CrearTemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_EditarTema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditarTemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).EditarTema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_EditarTema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).EditarTema(ctx, req.(*EditarTemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_EliminarTema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EliminarTemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).EliminarTema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_EliminarTema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).EliminarTema(ctx, req.(*EliminarTemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_ConsultarTemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarTemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).ConsultarTemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_ConsultarTemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).ConsultarTemas(ctx, req.(*ConsultarTemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_CrearClaseGrabada_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearClaseGrabadaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).CrearClaseGrabada(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_CrearClaseGrabada_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).CrearClaseGrabada(ctx, req.(*CrearClaseGrabadaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_CargaMasivaClases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCrearClaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).CargaMasivaClases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_CargaMasivaClases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).CargaMasivaClases(ctx, req.(*BatchCrearClaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_EditarClaseGrabada_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditarClaseGrabadaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).EditarClaseGrabada(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_EditarClaseGrabada_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).EditarClaseGrabada(ctx, req.(*EditarClaseGrabadaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_EliminarClaseGrabada_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EliminarClaseGrabadaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).EliminarClaseGrabada(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_EliminarClaseGrabada_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).EliminarClaseGrabada(ctx, req.(*EliminarClaseGrabadaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_BusquedaAvanzada_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BusquedaAvanzadaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).BusquedaAvanzada(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_BusquedaAvanzada_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).BusquedaAvanzada(ctx, req.(*BusquedaAvanzadaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_ObtenerDetalleClaseGrabada_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObtenerDetalleClaseGrabadaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).ObtenerDetalleClaseGrabada(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_ObtenerDetalleClaseGrabada_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).ObtenerDetalleClaseGrabada(ctx, req.(*ObtenerDetalleClaseGrabadaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_ObtenerEnlaceClaseGrabada_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObtenerEnlaceClaseGrabadaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).ObtenerEnlaceClaseGrabada(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_ObtenerEnlaceClaseGrabada_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).ObtenerEnlaceClaseGrabada(ctx, req.(*ObtenerEnlaceClaseGrabadaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_AsignarDocente_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AsignarDocenteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).AsignarDocente(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_AsignarDocente_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).AsignarDocente(ctx, req.(*AsignarDocenteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_DesasignarDocente_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesasignarDocenteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).DesasignarDocente(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_DesasignarDocente_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).DesasignarDocente(ctx, req.(*DesasignarDocenteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_AsignarAuxiliar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AsignarAuxiliarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).AsignarAuxiliar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_AsignarAuxiliar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).AsignarAuxiliar(ctx, req.(*AsignarAuxiliarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_DesasignarAuxiliar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesasignarAuxiliarRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).DesasignarAuxiliar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_DesasignarAuxiliar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).DesasignarAuxiliar(ctx, req.(*DesasignarAuxiliarRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_AsignarMaterialApoyo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AsignarMaterialApoyoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).AsignarMaterialApoyo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_AsignarMaterialApoyo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).AsignarMaterialApoyo(ctx, req.(*AsignarMaterialApoyoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_DesasignarMaterialApoyo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesasignarMaterialApoyoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).DesasignarMaterialApoyo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_DesasignarMaterialApoyo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).DesasignarMaterialApoyo(ctx, req.(*DesasignarMaterialApoyoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_AsignarTemaClaseGrabada_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AsignarTemaClaseGrabadaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).AsignarTemaClaseGrabada(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_AsignarTemaClaseGrabada_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).AsignarTemaClaseGrabada(ctx, req.(*AsignarTemaClaseGrabadaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_DesasignarTemaClaseGrabada_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DesasignarTemaClaseGrabadaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).DesasignarTemaClaseGrabada(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_DesasignarTemaClaseGrabada_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).DesasignarTemaClaseGrabada(ctx, req.(*DesasignarTemaClaseGrabadaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_ConsultarParticipantesClase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarParticipantesClaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).ConsultarParticipantesClase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_ConsultarParticipantesClase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).ConsultarParticipantesClase(ctx, req.(*ConsultarParticipantesClaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_CrearCapitulo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearCapituloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).CrearCapitulo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_CrearCapitulo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).CrearCapitulo(ctx, req.(*CrearCapituloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_EditarCapitulo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditarCapituloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).EditarCapitulo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_EditarCapitulo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).EditarCapitulo(ctx, req.(*EditarCapituloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_EliminarCapitulo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EliminarCapituloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).EliminarCapitulo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_EliminarCapitulo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).EliminarCapitulo(ctx, req.(*EliminarCapituloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_ConsultarCapitulosClase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarCapitulosClaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).ConsultarCapitulosClase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_ConsultarCapitulosClase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).ConsultarCapitulosClase(ctx, req.(*ConsultarCapitulosClaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_ConsultarPlaylistsUsuario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarPlaylistsUsuarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).ConsultarPlaylistsUsuario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_ConsultarPlaylistsUsuario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).ConsultarPlaylistsUsuario(ctx, req.(*ConsultarPlaylistsUsuarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_ConsultarPlaylistPorHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarPlaylistPorHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).ConsultarPlaylistPorHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_ConsultarPlaylistPorHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).ConsultarPlaylistPorHash(ctx, req.(*ConsultarPlaylistPorHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_ConsultarVideosPlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarVideosPlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).ConsultarVideosPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_ConsultarVideosPlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).ConsultarVideosPlaylist(ctx, req.(*ConsultarVideosPlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_ConsultarVideosPlaylistPorHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarVideosPlaylistPorHashRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).ConsultarVideosPlaylistPorHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_ConsultarVideosPlaylistPorHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).ConsultarVideosPlaylistPorHash(ctx, req.(*ConsultarVideosPlaylistPorHashRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_CrearPlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CrearPlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).CrearPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_CrearPlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).CrearPlaylist(ctx, req.(*CrearPlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_EliminarPlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EliminarPlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).EliminarPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_EliminarPlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).EliminarPlaylist(ctx, req.(*EliminarPlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_CambiarVisibilidadPlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CambiarVisibilidadPlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).CambiarVisibilidadPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_CambiarVisibilidadPlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).CambiarVisibilidadPlaylist(ctx, req.(*CambiarVisibilidadPlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_AgregarVideoPlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgregarVideoPlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).AgregarVideoPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_AgregarVideoPlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).AgregarVideoPlaylist(ctx, req.(*AgregarVideoPlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_EliminarVideoPlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EliminarVideoPlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).EliminarVideoPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_EliminarVideoPlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).EliminarVideoPlaylist(ctx, req.(*EliminarVideoPlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_GenerarLinkPlaylist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerarLinkPlaylistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).GenerarLinkPlaylist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_GenerarLinkPlaylist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).GenerarLinkPlaylist(ctx, req.(*GenerarLinkPlaylistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GrabacionesService_ConsultarAuditLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarAuditLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GrabacionesServiceServer).ConsultarAuditLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GrabacionesService_ConsultarAuditLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GrabacionesServiceServer).ConsultarAuditLogs(ctx, req.(*ConsultarAuditLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GrabacionesService_ServiceDesc is the grpc.ServiceDesc for GrabacionesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GrabacionesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grabaciones.GrabacionesService",
	HandlerType: (*GrabacionesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConsultarCatalogoClases",
			Handler:    _GrabacionesService_ConsultarCatalogoClases_Handler,
		},
		{
			MethodName: "CrearUnidad",
			Handler:    _GrabacionesService_CrearUnidad_Handler,
		},
		{
			MethodName: "EditarUnidad",
			Handler:    _GrabacionesService_EditarUnidad_Handler,
		},
		{
			MethodName: "EliminarUnidad",
			Handler:    _GrabacionesService_EliminarUnidad_Handler,
		},
		{
			MethodName: "ConsultarUnidades",
			Handler:    _GrabacionesService_ConsultarUnidades_Handler,
		},
		{
			MethodName: "CrearTema",
			Handler:    _GrabacionesService_CrearTema_Handler,
		},
		{
			MethodName: "EditarTema",
			Handler:    _GrabacionesService_EditarTema_Handler,
		},
		{
			MethodName: "EliminarTema",
			Handler:    _GrabacionesService_EliminarTema_Handler,
		},
		{
			MethodName: "ConsultarTemas",
			Handler:    _GrabacionesService_ConsultarTemas_Handler,
		},
		{
			MethodName: "CrearClaseGrabada",
			Handler:    _GrabacionesService_CrearClaseGrabada_Handler,
		},
		{
			MethodName: "CargaMasivaClases",
			Handler:    _GrabacionesService_CargaMasivaClases_Handler,
		},
		{
			MethodName: "EditarClaseGrabada",
			Handler:    _GrabacionesService_EditarClaseGrabada_Handler,
		},
		{
			MethodName: "EliminarClaseGrabada",
			Handler:    _GrabacionesService_EliminarClaseGrabada_Handler,
		},
		{
			MethodName: "BusquedaAvanzada",
			Handler:    _GrabacionesService_BusquedaAvanzada_Handler,
		},
		{
			MethodName: "ObtenerDetalleClaseGrabada",
			Handler:    _GrabacionesService_ObtenerDetalleClaseGrabada_Handler,
		},
		{
			MethodName: "ObtenerEnlaceClaseGrabada",
			Handler:    _GrabacionesService_ObtenerEnlaceClaseGrabada_Handler,
		},
		{
			MethodName: "AsignarDocente",
			Handler:    _GrabacionesService_AsignarDocente_Handler,
		},
		{
			MethodName: "DesasignarDocente",
			Handler:    _GrabacionesService_DesasignarDocente_Handler,
		},
		{
			MethodName: "AsignarAuxiliar",
			Handler:    _GrabacionesService_AsignarAuxiliar_Handler,
		},
		{
			MethodName: "DesasignarAuxiliar",
			Handler:    _GrabacionesService_DesasignarAuxiliar_Handler,
		},
		{
			MethodName: "AsignarMaterialApoyo",
			Handler:    _GrabacionesService_AsignarMaterialApoyo_Handler,
		},
		{
			MethodName: "DesasignarMaterialApoyo",
			Handler:    _GrabacionesService_DesasignarMaterialApoyo_Handler,
		},
		{
			MethodName: "AsignarTemaClaseGrabada",
			Handler:    _GrabacionesService_AsignarTemaClaseGrabada_Handler,
		},
		{
			MethodName: "DesasignarTemaClaseGrabada",
			Handler:    _GrabacionesService_DesasignarTemaClaseGrabada_Handler,
		},
		{
			MethodName: "ConsultarParticipantesClase",
			Handler:    _GrabacionesService_ConsultarParticipantesClase_Handler,
		},
		{
			MethodName: "CrearCapitulo",
			Handler:    _GrabacionesService_CrearCapitulo_Handler,
		},
		{
			MethodName: "EditarCapitulo",
			Handler:    _GrabacionesService_EditarCapitulo_Handler,
		},
		{
			MethodName: "EliminarCapitulo",
			Handler:    _GrabacionesService_EliminarCapitulo_Handler,
		},
		{
			MethodName: "ConsultarCapitulosClase",
			Handler:    _GrabacionesService_ConsultarCapitulosClase_Handler,
		},
		{
			MethodName: "ConsultarPlaylistsUsuario",
			Handler:    _GrabacionesService_ConsultarPlaylistsUsuario_Handler,
		},
		{
			MethodName: "ConsultarPlaylistPorHash",
			Handler:    _GrabacionesService_ConsultarPlaylistPorHash_Handler,
		},
		{
			MethodName: "ConsultarVideosPlaylist",
			Handler:    _GrabacionesService_ConsultarVideosPlaylist_Handler,
		},
		{
			MethodName: "ConsultarVideosPlaylistPorHash",
			Handler:    _GrabacionesService_ConsultarVideosPlaylistPorHash_Handler,
		},
		{
			MethodName: "CrearPlaylist",
			Handler:    _GrabacionesService_CrearPlaylist_Handler,
		},
		{
			MethodName: "EliminarPlaylist",
			Handler:    _GrabacionesService_EliminarPlaylist_Handler,
		},
		{
			MethodName: "CambiarVisibilidadPlaylist",
			Handler:    _GrabacionesService_CambiarVisibilidadPlaylist_Handler,
		},
		{
			MethodName: "AgregarVideoPlaylist",
			Handler:    _GrabacionesService_AgregarVideoPlaylist_Handler,
		},
		{
			MethodName: "EliminarVideoPlaylist",
			Handler:    _GrabacionesService_EliminarVideoPlaylist_Handler,
		},
		{
			MethodName: "GenerarLinkPlaylist",
			Handler:    _GrabacionesService_GenerarLinkPlaylist_Handler,
		},
		{
			MethodName: "ConsultarAuditLogs",
			Handler:    _GrabacionesService_ConsultarAuditLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grabaciones.proto",
}
