# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import analisis_pb2 as analisis__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in analisis_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalisisServiceStub:
    """Servicio principal de analitica, tendencias y recomendaciones
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearUnidad = channel.unary_unary(
                '/analisis.AnalisisService/CrearUnidad',
                request_serializer=analisis__pb2.CrearUnidadRequest.SerializeToString,
                response_deserializer=analisis__pb2.CrearUnidadResponse.FromString,
                _registered_method=True)
        self.EditarUnidad = channel.unary_unary(
                '/analisis.AnalisisService/EditarUnidad',
                request_serializer=analisis__pb2.EditarUnidadRequest.SerializeToString,
                response_deserializer=analisis__pb2.EditarUnidadResponse.FromString,
                _registered_method=True)
        self.EliminarUnidad = channel.unary_unary(
                '/analisis.AnalisisService/EliminarUnidad',
                request_serializer=analisis__pb2.EliminarUnidadRequest.SerializeToString,
                response_deserializer=analisis__pb2.EliminarUnidadResponse.FromString,
                _registered_method=True)
        self.ConsultarUnidades = channel.unary_unary(
                '/analisis.AnalisisService/ConsultarUnidades',
                request_serializer=analisis__pb2.ConsultarUnidadesRequest.SerializeToString,
                response_deserializer=analisis__pb2.ConsultarUnidadesResponse.FromString,
                _registered_method=True)
        self.CrearTema = channel.unary_unary(
                '/analisis.AnalisisService/CrearTema',
                request_serializer=analisis__pb2.CrearTemaRequest.SerializeToString,
                response_deserializer=analisis__pb2.CrearTemaResponse.FromString,
                _registered_method=True)
        self.EditarTema = channel.unary_unary(
                '/analisis.AnalisisService/EditarTema',
                request_serializer=analisis__pb2.EditarTemaRequest.SerializeToString,
                response_deserializer=analisis__pb2.EditarTemaResponse.FromString,
                _registered_method=True)
        self.EliminarTema = channel.unary_unary(
                '/analisis.AnalisisService/EliminarTema',
                request_serializer=analisis__pb2.EliminarTemaRequest.SerializeToString,
                response_deserializer=analisis__pb2.EliminarTemaResponse.FromString,
                _registered_method=True)
        self.ConsultarTemas = channel.unary_unary(
                '/analisis.AnalisisService/ConsultarTemas',
                request_serializer=analisis__pb2.ConsultarTemasRequest.SerializeToString,
                response_deserializer=analisis__pb2.ConsultarTemasResponse.FromString,
                _registered_method=True)
        self.CrearClaseGrabada = channel.unary_unary(
                '/analisis.AnalisisService/CrearClaseGrabada',
                request_serializer=analisis__pb2.CrearClaseGrabadaRequest.SerializeToString,
                response_deserializer=analisis__pb2.CrearClaseGrabadaResponse.FromString,
                _registered_method=True)
        self.EditarClaseGrabada = channel.unary_unary(
                '/analisis.AnalisisService/EditarClaseGrabada',
                request_serializer=analisis__pb2.EditarClaseGrabadaRequest.SerializeToString,
                response_deserializer=analisis__pb2.EditarClaseGrabadaResponse.FromString,
                _registered_method=True)
        self.EliminarClaseGrabada = channel.unary_unary(
                '/analisis.AnalisisService/EliminarClaseGrabada',
                request_serializer=analisis__pb2.EliminarClaseGrabadaRequest.SerializeToString,
                response_deserializer=analisis__pb2.EliminarClaseGrabadaResponse.FromString,
                _registered_method=True)
        self.ConsultarCatalogoClases = channel.unary_unary(
                '/analisis.AnalisisService/ConsultarCatalogoClases',
                request_serializer=analisis__pb2.ConsultarCatalogoClasesRequest.SerializeToString,
                response_deserializer=analisis__pb2.ConsultarCatalogoClasesResponse.FromString,
                _registered_method=True)
        self.AsignarTemaClaseGrabada = channel.unary_unary(
                '/analisis.AnalisisService/AsignarTemaClaseGrabada',
                request_serializer=analisis__pb2.AsignarTemaClaseGrabadaRequest.SerializeToString,
                response_deserializer=analisis__pb2.AsignarTemaClaseGrabadaResponse.FromString,
                _registered_method=True)
        self.DesasignarTemaClaseGrabada = channel.unary_unary(
                '/analisis.AnalisisService/DesasignarTemaClaseGrabada',
                request_serializer=analisis__pb2.DesasignarTemaClaseGrabadaRequest.SerializeToString,
                response_deserializer=analisis__pb2.DesasignarTemaClaseGrabadaResponse.FromString,
                _registered_method=True)
        self.CargaMasivaClases = channel.unary_unary(
                '/analisis.AnalisisService/CargaMasivaClases',
                request_serializer=analisis__pb2.BatchCrearClaseRequest.SerializeToString,
                response_deserializer=analisis__pb2.BatchCrearClaseResponse.FromString,
                _registered_method=True)
        self.VisualizarClase = channel.unary_unary(
                '/analisis.AnalisisService/VisualizarClase',
                request_serializer=analisis__pb2.VisualizarClaseRequest.SerializeToString,
                response_deserializer=analisis__pb2.VisualizarClaseResponse.FromString,
                _registered_method=True)
        self.CalificarClase = channel.unary_unary(
                '/analisis.AnalisisService/CalificarClase',
                request_serializer=analisis__pb2.CalificarClaseRequest.SerializeToString,
                response_deserializer=analisis__pb2.CalificarClaseResponse.FromString,
                _registered_method=True)
        self.ConsultarCalificacionUsuario = channel.unary_unary(
                '/analisis.AnalisisService/ConsultarCalificacionUsuario',
                request_serializer=analisis__pb2.ConsultarCalificacionUsuarioRequest.SerializeToString,
                response_deserializer=analisis__pb2.ConsultarCalificacionUsuarioResponse.FromString,
                _registered_method=True)
        self.ConsultarClasesMasVistas = channel.unary_unary(
                '/analisis.AnalisisService/ConsultarClasesMasVistas',
                request_serializer=analisis__pb2.ConsultarClasesMasVistasRequest.SerializeToString,
                response_deserializer=analisis__pb2.ConsultarClasesMasVistasResponse.FromString,
                _registered_method=True)
        self.ConsultarTemasTendencia = channel.unary_unary(
                '/analisis.AnalisisService/ConsultarTemasTendencia',
                request_serializer=analisis__pb2.ConsultarTemasTendenciaRequest.SerializeToString,
                response_deserializer=analisis__pb2.ConsultarTemasTendenciaResponse.FromString,
                _registered_method=True)
        self.ConsultarRankingValoradas = channel.unary_unary(
                '/analisis.AnalisisService/ConsultarRankingValoradas',
                request_serializer=analisis__pb2.ConsultarRankingValoradasRequest.SerializeToString,
                response_deserializer=analisis__pb2.ConsultarRankingValoradasResponse.FromString,
                _registered_method=True)
        self.ConsultarAuditLogs = channel.unary_unary(
                '/analisis.AnalisisService/ConsultarAuditLogs',
                request_serializer=analisis__pb2.ConsultarAuditLogsRequest.SerializeToString,
                response_deserializer=analisis__pb2.ConsultarAuditLogsResponse.FromString,
                _registered_method=True)


class AnalisisServiceServicer:
    """Servicio principal de analitica, tendencias y recomendaciones
    """

    def CrearUnidad(self, request, context):
        """Espejo local del catalogo (sincronizado con grabaciones)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditarUnidad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarUnidad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarUnidades(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CrearTema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditarTema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarTema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarTemas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CrearClaseGrabada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EditarClaseGrabada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarClaseGrabada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarCatalogoClases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AsignarTemaClaseGrabada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DesasignarTemaClaseGrabada(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CargaMasivaClases(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VisualizarClase(self, request, context):
        """Registro de acciones de usuarios
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalificarClase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarCalificacionUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarClasesMasVistas(self, request, context):
        """asignar desasignar tema

        Tendencias y recomendaciones (con cache Redis TTL)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarTemasTendencia(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarRankingValoradas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConsultarAuditLogs(self, request, context):
        """Auditoria
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalisisServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearUnidad': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearUnidad,
                    request_deserializer=analisis__pb2.CrearUnidadRequest.FromString,
                    response_serializer=analisis__pb2.CrearUnidadResponse.SerializeToString,
            ),
            'EditarUnidad': grpc.unary_unary_rpc_method_handler(
                    servicer.EditarUnidad,
                    request_deserializer=analisis__pb2.EditarUnidadRequest.FromString,
                    response_serializer=analisis__pb2.EditarUnidadResponse.SerializeToString,
            ),
            'EliminarUnidad': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarUnidad,
                    request_deserializer=analisis__pb2.EliminarUnidadRequest.FromString,
                    response_serializer=analisis__pb2.EliminarUnidadResponse.SerializeToString,
            ),
            'ConsultarUnidades': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarUnidades,
                    request_deserializer=analisis__pb2.ConsultarUnidadesRequest.FromString,
                    response_serializer=analisis__pb2.ConsultarUnidadesResponse.SerializeToString,
            ),
            'CrearTema': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearTema,
                    request_deserializer=analisis__pb2.CrearTemaRequest.FromString,
                    response_serializer=analisis__pb2.CrearTemaResponse.SerializeToString,
            ),
            'EditarTema': grpc.unary_unary_rpc_method_handler(
                    servicer.EditarTema,
                    request_deserializer=analisis__pb2.EditarTemaRequest.FromString,
                    response_serializer=analisis__pb2.EditarTemaResponse.SerializeToString,
            ),
            'EliminarTema': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarTema,
                    request_deserializer=analisis__pb2.EliminarTemaRequest.FromString,
                    response_serializer=analisis__pb2.EliminarTemaResponse.SerializeToString,
            ),
            'ConsultarTemas': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarTemas,
                    request_deserializer=analisis__pb2.ConsultarTemasRequest.FromString,
                    response_serializer=analisis__pb2.ConsultarTemasResponse.SerializeToString,
            ),
            'CrearClaseGrabada': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearClaseGrabada,
                    request_deserializer=analisis__pb2.CrearClaseGrabadaRequest.FromString,
                    response_serializer=analisis__pb2.CrearClaseGrabadaResponse.SerializeToString,
            ),
            'EditarClaseGrabada': grpc.unary_unary_rpc_method_handler(
                    servicer.EditarClaseGrabada,
                    request_deserializer=analisis__pb2.EditarClaseGrabadaRequest.FromString,
                    response_serializer=analisis__pb2.EditarClaseGrabadaResponse.SerializeToString,
            ),
            'EliminarClaseGrabada': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarClaseGrabada,
                    request_deserializer=analisis__pb2.EliminarClaseGrabadaRequest.FromString,
                    response_serializer=analisis__pb2.EliminarClaseGrabadaResponse.SerializeToString,
            ),
            'ConsultarCatalogoClases': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarCatalogoClases,
                    request_deserializer=analisis__pb2.ConsultarCatalogoClasesRequest.FromString,
                    response_serializer=analisis__pb2.ConsultarCatalogoClasesResponse.SerializeToString,
            ),
            'AsignarTemaClaseGrabada': grpc.unary_unary_rpc_method_handler(
                    servicer.AsignarTemaClaseGrabada,
                    request_deserializer=analisis__pb2.AsignarTemaClaseGrabadaRequest.FromString,
                    response_serializer=analisis__pb2.AsignarTemaClaseGrabadaResponse.SerializeToString,
            ),
            'DesasignarTemaClaseGrabada': grpc.unary_unary_rpc_method_handler(
                    servicer.DesasignarTemaClaseGrabada,
                    request_deserializer=analisis__pb2.DesasignarTemaClaseGrabadaRequest.FromString,
                    response_serializer=analisis__pb2.DesasignarTemaClaseGrabadaResponse.SerializeToString,
            ),
            'CargaMasivaClases': grpc.unary_unary_rpc_method_handler(
                    servicer.CargaMasivaClases,
                    request_deserializer=analisis__pb2.BatchCrearClaseRequest.FromString,
                    response_serializer=analisis__pb2.BatchCrearClaseResponse.SerializeToString,
            ),
            'VisualizarClase': grpc.unary_unary_rpc_method_handler(
                    servicer.VisualizarClase,
                    request_deserializer=analisis__pb2.VisualizarClaseRequest.FromString,
                    response_serializer=analisis__pb2.VisualizarClaseResponse.SerializeToString,
            ),
            'CalificarClase': grpc.unary_unary_rpc_method_handler(
                    servicer.CalificarClase,
                    request_deserializer=analisis__pb2.CalificarClaseRequest.FromString,
                    response_serializer=analisis__pb2.CalificarClaseResponse.SerializeToString,
            ),
            'ConsultarCalificacionUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarCalificacionUsuario,
                    request_deserializer=analisis__pb2.ConsultarCalificacionUsuarioRequest.FromString,
                    response_serializer=analisis__pb2.ConsultarCalificacionUsuarioResponse.SerializeToString,
            ),
            'ConsultarClasesMasVistas': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarClasesMasVistas,
                    request_deserializer=analisis__pb2.ConsultarClasesMasVistasRequest.FromString,
                    response_serializer=analisis__pb2.ConsultarClasesMasVistasResponse.SerializeToString,
            ),
            'ConsultarTemasTendencia': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarTemasTendencia,
                    request_deserializer=analisis__pb2.ConsultarTemasTendenciaRequest.FromString,
                    response_serializer=analisis__pb2.ConsultarTemasTendenciaResponse.SerializeToString,
            ),
            'ConsultarRankingValoradas': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarRankingValoradas,
                    request_deserializer=analisis__pb2.ConsultarRankingValoradasRequest.FromString,
                    response_serializer=analisis__pb2.ConsultarRankingValoradasResponse.SerializeToString,
            ),
            'ConsultarAuditLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.ConsultarAuditLogs,
                    request_deserializer=analisis__pb2.ConsultarAuditLogsRequest.FromString,
                    response_serializer=analisis__pb2.ConsultarAuditLogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analisis.AnalisisService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analisis.AnalisisService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalisisService:
    """Servicio principal de analitica, tendencias y recomendaciones
    """

    @staticmethod
    def CrearUnidad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/CrearUnidad',
            analisis__pb2.CrearUnidadRequest.SerializeToString,
            analisis__pb2.CrearUnidadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditarUnidad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/EditarUnidad',
            analisis__pb2.EditarUnidadRequest.SerializeToString,
            analisis__pb2.EditarUnidadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarUnidad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/EliminarUnidad',
            analisis__pb2.EliminarUnidadRequest.SerializeToString,
            analisis__pb2.EliminarUnidadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarUnidades(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/ConsultarUnidades',
            analisis__pb2.ConsultarUnidadesRequest.SerializeToString,
            analisis__pb2.ConsultarUnidadesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CrearTema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/CrearTema',
            analisis__pb2.CrearTemaRequest.SerializeToString,
            analisis__pb2.CrearTemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditarTema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/EditarTema',
            analisis__pb2.EditarTemaRequest.SerializeToString,
            analisis__pb2.EditarTemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarTema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/EliminarTema',
            analisis__pb2.EliminarTemaRequest.SerializeToString,
            analisis__pb2.EliminarTemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarTemas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/ConsultarTemas',
            analisis__pb2.ConsultarTemasRequest.SerializeToString,
            analisis__pb2.ConsultarTemasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CrearClaseGrabada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/CrearClaseGrabada',
            analisis__pb2.CrearClaseGrabadaRequest.SerializeToString,
            analisis__pb2.CrearClaseGrabadaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EditarClaseGrabada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/EditarClaseGrabada',
            analisis__pb2.EditarClaseGrabadaRequest.SerializeToString,
            analisis__pb2.EditarClaseGrabadaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarClaseGrabada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/EliminarClaseGrabada',
            analisis__pb2.EliminarClaseGrabadaRequest.SerializeToString,
            analisis__pb2.EliminarClaseGrabadaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarCatalogoClases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/ConsultarCatalogoClases',
            analisis__pb2.ConsultarCatalogoClasesRequest.SerializeToString,
            analisis__pb2.ConsultarCatalogoClasesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AsignarTemaClaseGrabada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/AsignarTemaClaseGrabada',
            analisis__pb2.AsignarTemaClaseGrabadaRequest.SerializeToString,
            analisis__pb2.AsignarTemaClaseGrabadaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DesasignarTemaClaseGrabada(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/DesasignarTemaClaseGrabada',
            analisis__pb2.DesasignarTemaClaseGrabadaRequest.SerializeToString,
            analisis__pb2.DesasignarTemaClaseGrabadaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CargaMasivaClases(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/CargaMasivaClases',
            analisis__pb2.BatchCrearClaseRequest.SerializeToString,
            analisis__pb2.BatchCrearClaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VisualizarClase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/VisualizarClase',
            analisis__pb2.VisualizarClaseRequest.SerializeToString,
            analisis__pb2.VisualizarClaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalificarClase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/CalificarClase',
            analisis__pb2.CalificarClaseRequest.SerializeToString,
            analisis__pb2.CalificarClaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarCalificacionUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/ConsultarCalificacionUsuario',
            analisis__pb2.ConsultarCalificacionUsuarioRequest.SerializeToString,
            analisis__pb2.ConsultarCalificacionUsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarClasesMasVistas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/ConsultarClasesMasVistas',
            analisis__pb2.ConsultarClasesMasVistasRequest.SerializeToString,
            analisis__pb2.ConsultarClasesMasVistasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarTemasTendencia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/ConsultarTemasTendencia',
            analisis__pb2.ConsultarTemasTendenciaRequest.SerializeToString,
            analisis__pb2.ConsultarTemasTendenciaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarRankingValoradas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/ConsultarRankingValoradas',
            analisis__pb2.ConsultarRankingValoradasRequest.SerializeToString,
            analisis__pb2.ConsultarRankingValoradasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConsultarAuditLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analisis.AnalisisService/ConsultarAuditLogs',
            analisis__pb2.ConsultarAuditLogsRequest.SerializeToString,
            analisis__pb2.ConsultarAuditLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
