// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: historial.proto

package historial

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ──────────────────────────────────────────────
// RegistrarProgreso (crea o actualiza el registro de reproducción)
// ──────────────────────────────────────────────
type RegistrarProgresoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdUsuario     int32                  `protobuf:"varint,1,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`             // Usuario que reproduce la clase
	IdClase       int32                  `protobuf:"varint,2,opt,name=id_clase,json=idClase,proto3" json:"id_clase,omitempty"`                   // Clase grabada reproducida
	IdTema        int32                  `protobuf:"varint,3,opt,name=id_tema,json=idTema,proto3" json:"id_tema,omitempty"`                      // Tema actual de la clase
	MinutoActual  int32                  `protobuf:"varint,4,opt,name=minuto_actual,json=minutoActual,proto3" json:"minuto_actual,omitempty"`    // Minuto en el que va la reproducción
	DuracionTotal int32                  `protobuf:"varint,5,opt,name=duracion_total,json=duracionTotal,proto3" json:"duracion_total,omitempty"` // Duración total de la clase en minutos
	SegundoActual int32                  `protobuf:"varint,6,opt,name=segundo_actual,json=segundoActual,proto3" json:"segundo_actual,omitempty"` // Segundo exacto dentro del minuto (0-59)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrarProgresoRequest) Reset() {
	*x = RegistrarProgresoRequest{}
	mi := &file_historial_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrarProgresoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrarProgresoRequest) ProtoMessage() {}

func (x *RegistrarProgresoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_historial_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrarProgresoRequest.ProtoReflect.Descriptor instead.
func (*RegistrarProgresoRequest) Descriptor() ([]byte, []int) {
	return file_historial_proto_rawDescGZIP(), []int{0}
}

func (x *RegistrarProgresoRequest) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

func (x *RegistrarProgresoRequest) GetIdClase() int32 {
	if x != nil {
		return x.IdClase
	}
	return 0
}

func (x *RegistrarProgresoRequest) GetIdTema() int32 {
	if x != nil {
		return x.IdTema
	}
	return 0
}

func (x *RegistrarProgresoRequest) GetMinutoActual() int32 {
	if x != nil {
		return x.MinutoActual
	}
	return 0
}

func (x *RegistrarProgresoRequest) GetDuracionTotal() int32 {
	if x != nil {
		return x.DuracionTotal
	}
	return 0
}

func (x *RegistrarProgresoRequest) GetSegundoActual() int32 {
	if x != nil {
		return x.SegundoActual
	}
	return 0
}

type RegistrarProgresoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Historial     *HistorialReproduccion `protobuf:"bytes,3,opt,name=historial,proto3" json:"historial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrarProgresoResponse) Reset() {
	*x = RegistrarProgresoResponse{}
	mi := &file_historial_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrarProgresoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrarProgresoResponse) ProtoMessage() {}

func (x *RegistrarProgresoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_historial_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrarProgresoResponse.ProtoReflect.Descriptor instead.
func (*RegistrarProgresoResponse) Descriptor() ([]byte, []int) {
	return file_historial_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrarProgresoResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *RegistrarProgresoResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *RegistrarProgresoResponse) GetHistorial() *HistorialReproduccion {
	if x != nil {
		return x.Historial
	}
	return nil
}

// ──────────────────────────────────────────────
// ActualizarCheckpoint (actualiza minuto y tema, conservando la duración)
// ──────────────────────────────────────────────
type ActualizarCheckpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdUsuario     int32                  `protobuf:"varint,1,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`             // Usuario propietario del historial
	IdClase       int32                  `protobuf:"varint,2,opt,name=id_clase,json=idClase,proto3" json:"id_clase,omitempty"`                   // Clase grabada
	IdTema        int32                  `protobuf:"varint,3,opt,name=id_tema,json=idTema,proto3" json:"id_tema,omitempty"`                      // Nuevo tema actual
	MinutoActual  int32                  `protobuf:"varint,4,opt,name=minuto_actual,json=minutoActual,proto3" json:"minuto_actual,omitempty"`    // Nuevo minuto actual
	SegundoActual int32                  `protobuf:"varint,5,opt,name=segundo_actual,json=segundoActual,proto3" json:"segundo_actual,omitempty"` // Segundo exacto dentro del minuto (0-59)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualizarCheckpointRequest) Reset() {
	*x = ActualizarCheckpointRequest{}
	mi := &file_historial_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizarCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarCheckpointRequest) ProtoMessage() {}

func (x *ActualizarCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_historial_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarCheckpointRequest.ProtoReflect.Descriptor instead.
func (*ActualizarCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_historial_proto_rawDescGZIP(), []int{2}
}

func (x *ActualizarCheckpointRequest) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

func (x *ActualizarCheckpointRequest) GetIdClase() int32 {
	if x != nil {
		return x.IdClase
	}
	return 0
}

func (x *ActualizarCheckpointRequest) GetIdTema() int32 {
	if x != nil {
		return x.IdTema
	}
	return 0
}

func (x *ActualizarCheckpointRequest) GetMinutoActual() int32 {
	if x != nil {
		return x.MinutoActual
	}
	return 0
}

func (x *ActualizarCheckpointRequest) GetSegundoActual() int32 {
	if x != nil {
		return x.SegundoActual
	}
	return 0
}

type ActualizarCheckpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Checkpoint    *CheckpointClase       `protobuf:"bytes,3,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActualizarCheckpointResponse) Reset() {
	*x = ActualizarCheckpointResponse{}
	mi := &file_historial_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActualizarCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActualizarCheckpointResponse) ProtoMessage() {}

func (x *ActualizarCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_historial_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActualizarCheckpointResponse.ProtoReflect.Descriptor instead.
func (*ActualizarCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_historial_proto_rawDescGZIP(), []int{3}
}

func (x *ActualizarCheckpointResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ActualizarCheckpointResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *ActualizarCheckpointResponse) GetCheckpoint() *CheckpointClase {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

// ──────────────────────────────────────────────
// MarcarClaseCompletada (marca 100% visto)
// ──────────────────────────────────────────────
type MarcarClaseCompletadaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdUsuario     int32                  `protobuf:"varint,1,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"` // Usuario propietario del historial
	IdClase       int32                  `protobuf:"varint,2,opt,name=id_clase,json=idClase,proto3" json:"id_clase,omitempty"`       // Clase grabada a marcar como completada
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarcarClaseCompletadaRequest) Reset() {
	*x = MarcarClaseCompletadaRequest{}
	mi := &file_historial_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarcarClaseCompletadaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarcarClaseCompletadaRequest) ProtoMessage() {}

func (x *MarcarClaseCompletadaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_historial_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarcarClaseCompletadaRequest.ProtoReflect.Descriptor instead.
func (*MarcarClaseCompletadaRequest) Descriptor() ([]byte, []int) {
	return file_historial_proto_rawDescGZIP(), []int{4}
}

func (x *MarcarClaseCompletadaRequest) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

func (x *MarcarClaseCompletadaRequest) GetIdClase() int32 {
	if x != nil {
		return x.IdClase
	}
	return 0
}

type MarcarClaseCompletadaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Historial     *HistorialReproduccion `protobuf:"bytes,3,opt,name=historial,proto3" json:"historial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarcarClaseCompletadaResponse) Reset() {
	*x = MarcarClaseCompletadaResponse{}
	mi := &file_historial_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarcarClaseCompletadaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarcarClaseCompletadaResponse) ProtoMessage() {}

func (x *MarcarClaseCompletadaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_historial_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarcarClaseCompletadaResponse.ProtoReflect.Descriptor instead.
func (*MarcarClaseCompletadaResponse) Descriptor() ([]byte, []int) {
	return file_historial_proto_rawDescGZIP(), []int{5}
}

func (x *MarcarClaseCompletadaResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *MarcarClaseCompletadaResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *MarcarClaseCompletadaResponse) GetHistorial() *HistorialReproduccion {
	if x != nil {
		return x.Historial
	}
	return nil
}

// ──────────────────────────────────────────────
// ObtenerCheckpointClase (checkpoint del usuario en una clase)
// ──────────────────────────────────────────────
type ObtenerCheckpointClaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdUsuario     int32                  `protobuf:"varint,1,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"` // Usuario
	IdClase       int32                  `protobuf:"varint,2,opt,name=id_clase,json=idClase,proto3" json:"id_clase,omitempty"`       // Clase grabada
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObtenerCheckpointClaseRequest) Reset() {
	*x = ObtenerCheckpointClaseRequest{}
	mi := &file_historial_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObtenerCheckpointClaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtenerCheckpointClaseRequest) ProtoMessage() {}

func (x *ObtenerCheckpointClaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_historial_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtenerCheckpointClaseRequest.ProtoReflect.Descriptor instead.
func (*ObtenerCheckpointClaseRequest) Descriptor() ([]byte, []int) {
	return file_historial_proto_rawDescGZIP(), []int{6}
}

func (x *ObtenerCheckpointClaseRequest) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

func (x *ObtenerCheckpointClaseRequest) GetIdClase() int32 {
	if x != nil {
		return x.IdClase
	}
	return 0
}

type ObtenerCheckpointClaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Checkpoint    *CheckpointClase       `protobuf:"bytes,3,opt,name=checkpoint,proto3" json:"checkpoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ObtenerCheckpointClaseResponse) Reset() {
	*x = ObtenerCheckpointClaseResponse{}
	mi := &file_historial_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObtenerCheckpointClaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObtenerCheckpointClaseResponse) ProtoMessage() {}

func (x *ObtenerCheckpointClaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_historial_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObtenerCheckpointClaseResponse.ProtoReflect.Descriptor instead.
func (*ObtenerCheckpointClaseResponse) Descriptor() ([]byte, []int) {
	return file_historial_proto_rawDescGZIP(), []int{7}
}

func (x *ObtenerCheckpointClaseResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ObtenerCheckpointClaseResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *ObtenerCheckpointClaseResponse) GetCheckpoint() *CheckpointClase {
	if x != nil {
		return x.Checkpoint
	}
	return nil
}

// ──────────────────────────────────────────────
// ConsultarHistorialUsuario (historial completo, paginado)
// ──────────────────────────────────────────────
type ConsultarHistorialUsuarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdUsuario     int32                  `protobuf:"varint,1,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"` // Usuario del que se consulta el historial
	Pagina        int32                  `protobuf:"varint,2,opt,name=pagina,proto3" json:"pagina,omitempty"`                        // Página a consultar (10 registros por página)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarHistorialUsuarioRequest) Reset() {
	*x = ConsultarHistorialUsuarioRequest{}
	mi := &file_historial_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarHistorialUsuarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarHistorialUsuarioRequest) ProtoMessage() {}

func (x *ConsultarHistorialUsuarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_historial_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarHistorialUsuarioRequest.ProtoReflect.Descriptor instead.
func (*ConsultarHistorialUsuarioRequest) Descriptor() ([]byte, []int) {
	return file_historial_proto_rawDescGZIP(), []int{8}
}

func (x *ConsultarHistorialUsuarioRequest) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

func (x *ConsultarHistorialUsuarioRequest) GetPagina() int32 {
	if x != nil {
		return x.Pagina
	}
	return 0
}

type ConsultarHistorialUsuarioResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Exito         bool                     `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                   `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Registros     []*HistorialReproduccion `protobuf:"bytes,3,rep,name=registros,proto3" json:"registros,omitempty"`
	TotalPaginas  int32                    `protobuf:"varint,4,opt,name=total_paginas,json=totalPaginas,proto3" json:"total_paginas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarHistorialUsuarioResponse) Reset() {
	*x = ConsultarHistorialUsuarioResponse{}
	mi := &file_historial_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarHistorialUsuarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarHistorialUsuarioResponse) ProtoMessage() {}

func (x *ConsultarHistorialUsuarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_historial_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarHistorialUsuarioResponse.ProtoReflect.Descriptor instead.
func (*ConsultarHistorialUsuarioResponse) Descriptor() ([]byte, []int) {
	return file_historial_proto_rawDescGZIP(), []int{9}
}

func (x *ConsultarHistorialUsuarioResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ConsultarHistorialUsuarioResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *ConsultarHistorialUsuarioResponse) GetRegistros() []*HistorialReproduccion {
	if x != nil {
		return x.Registros
	}
	return nil
}

func (x *ConsultarHistorialUsuarioResponse) GetTotalPaginas() int32 {
	if x != nil {
		return x.TotalPaginas
	}
	return 0
}

// ──────────────────────────────────────────────
// ConsultarEstadisticasUsuario (resumen de progreso)
// ──────────────────────────────────────────────
type ConsultarEstadisticasUsuarioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdUsuario     int32                  `protobuf:"varint,1,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"` // Usuario
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarEstadisticasUsuarioRequest) Reset() {
	*x = ConsultarEstadisticasUsuarioRequest{}
	mi := &file_historial_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarEstadisticasUsuarioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarEstadisticasUsuarioRequest) ProtoMessage() {}

func (x *ConsultarEstadisticasUsuarioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_historial_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarEstadisticasUsuarioRequest.ProtoReflect.Descriptor instead.
func (*ConsultarEstadisticasUsuarioRequest) Descriptor() ([]byte, []int) {
	return file_historial_proto_rawDescGZIP(), []int{10}
}

func (x *ConsultarEstadisticasUsuarioRequest) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

type ConsultarEstadisticasUsuarioResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Estadisticas  *EstadisticasUsuario   `protobuf:"bytes,3,opt,name=estadisticas,proto3" json:"estadisticas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarEstadisticasUsuarioResponse) Reset() {
	*x = ConsultarEstadisticasUsuarioResponse{}
	mi := &file_historial_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarEstadisticasUsuarioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarEstadisticasUsuarioResponse) ProtoMessage() {}

func (x *ConsultarEstadisticasUsuarioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_historial_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarEstadisticasUsuarioResponse.ProtoReflect.Descriptor instead.
func (*ConsultarEstadisticasUsuarioResponse) Descriptor() ([]byte, []int) {
	return file_historial_proto_rawDescGZIP(), []int{11}
}

func (x *ConsultarEstadisticasUsuarioResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ConsultarEstadisticasUsuarioResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *ConsultarEstadisticasUsuarioResponse) GetEstadisticas() *EstadisticasUsuario {
	if x != nil {
		return x.Estadisticas
	}
	return nil
}

// ──────────────────────────────────────────────
// EliminarHistorialClase (borra el registro de una clase)
// ──────────────────────────────────────────────
type EliminarHistorialClaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdUsuario     int32                  `protobuf:"varint,1,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"` // Usuario propietario del historial
	IdClase       int32                  `protobuf:"varint,2,opt,name=id_clase,json=idClase,proto3" json:"id_clase,omitempty"`       // Clase grabada a eliminar del historial
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EliminarHistorialClaseRequest) Reset() {
	*x = EliminarHistorialClaseRequest{}
	mi := &file_historial_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EliminarHistorialClaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminarHistorialClaseRequest) ProtoMessage() {}

func (x *EliminarHistorialClaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_historial_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminarHistorialClaseRequest.ProtoReflect.Descriptor instead.
func (*EliminarHistorialClaseRequest) Descriptor() ([]byte, []int) {
	return file_historial_proto_rawDescGZIP(), []int{12}
}

func (x *EliminarHistorialClaseRequest) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

func (x *EliminarHistorialClaseRequest) GetIdClase() int32 {
	if x != nil {
		return x.IdClase
	}
	return 0
}

type EliminarHistorialClaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EliminarHistorialClaseResponse) Reset() {
	*x = EliminarHistorialClaseResponse{}
	mi := &file_historial_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EliminarHistorialClaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EliminarHistorialClaseResponse) ProtoMessage() {}

func (x *EliminarHistorialClaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_historial_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EliminarHistorialClaseResponse.ProtoReflect.Descriptor instead.
func (*EliminarHistorialClaseResponse) Descriptor() ([]byte, []int) {
	return file_historial_proto_rawDescGZIP(), []int{13}
}

func (x *EliminarHistorialClaseResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *EliminarHistorialClaseResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

// ──────────────────────────────────────────────
// ConsultarAuditLogs (paginado)
// ──────────────────────────────────────────────
type ConsultarAuditLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pagina        int32                  `protobuf:"varint,1,opt,name=pagina,proto3" json:"pagina,omitempty"`                                    // Página a consultar (10 registros por página)
	UsuarioFiltro int32                  `protobuf:"varint,2,opt,name=usuario_filtro,json=usuarioFiltro,proto3" json:"usuario_filtro,omitempty"` // Filtrar por usuario responsable (0 = todos)
	TablaFiltro   string                 `protobuf:"bytes,3,opt,name=tabla_filtro,json=tablaFiltro,proto3" json:"tabla_filtro,omitempty"`        // Filtrar por tabla afectada (vacío = todas)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarAuditLogsRequest) Reset() {
	*x = ConsultarAuditLogsRequest{}
	mi := &file_historial_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarAuditLogsRequest) ProtoMessage() {}

func (x *ConsultarAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_historial_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*ConsultarAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_historial_proto_rawDescGZIP(), []int{14}
}

func (x *ConsultarAuditLogsRequest) GetPagina() int32 {
	if x != nil {
		return x.Pagina
	}
	return 0
}

func (x *ConsultarAuditLogsRequest) GetUsuarioFiltro() int32 {
	if x != nil {
		return x.UsuarioFiltro
	}
	return 0
}

func (x *ConsultarAuditLogsRequest) GetTablaFiltro() string {
	if x != nil {
		return x.TablaFiltro
	}
	return ""
}

type ConsultarAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Exito         bool                   `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`
	Mensaje       string                 `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	Registros     []*AuditLog            `protobuf:"bytes,3,rep,name=registros,proto3" json:"registros,omitempty"`
	TotalPaginas  int32                  `protobuf:"varint,4,opt,name=total_paginas,json=totalPaginas,proto3" json:"total_paginas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsultarAuditLogsResponse) Reset() {
	*x = ConsultarAuditLogsResponse{}
	mi := &file_historial_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsultarAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsultarAuditLogsResponse) ProtoMessage() {}

func (x *ConsultarAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_historial_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsultarAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*ConsultarAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_historial_proto_rawDescGZIP(), []int{15}
}

func (x *ConsultarAuditLogsResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *ConsultarAuditLogsResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *ConsultarAuditLogsResponse) GetRegistros() []*AuditLog {
	if x != nil {
		return x.Registros
	}
	return nil
}

func (x *ConsultarAuditLogsResponse) GetTotalPaginas() int32 {
	if x != nil {
		return x.TotalPaginas
	}
	return 0
}

// ──────────────────────────────────────────────
// Mensajes compuestos (modelos)
// ──────────────────────────────────────────────
type HistorialReproduccion struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	IdHistorial             int32                  `protobuf:"varint,1,opt,name=id_historial,json=idHistorial,proto3" json:"id_historial,omitempty"`
	IdUsuario               int32                  `protobuf:"varint,2,opt,name=id_usuario,json=idUsuario,proto3" json:"id_usuario,omitempty"`
	IdClase                 int32                  `protobuf:"varint,3,opt,name=id_clase,json=idClase,proto3" json:"id_clase,omitempty"`
	IdTema                  int32                  `protobuf:"varint,4,opt,name=id_tema,json=idTema,proto3" json:"id_tema,omitempty"`
	MinutoActual            int32                  `protobuf:"varint,5,opt,name=minuto_actual,json=minutoActual,proto3" json:"minuto_actual,omitempty"`
	DuracionTotal           int32                  `protobuf:"varint,6,opt,name=duracion_total,json=duracionTotal,proto3" json:"duracion_total,omitempty"`
	PorcentajeVisto         float32                `protobuf:"fixed32,7,opt,name=porcentaje_visto,json=porcentajeVisto,proto3" json:"porcentaje_visto,omitempty"` // 0.00 - 100.00
	FechaUltimaReproduccion string                 `protobuf:"bytes,8,opt,name=fecha_ultima_reproduccion,json=fechaUltimaReproduccion,proto3" json:"fecha_ultima_reproduccion,omitempty"`
	FechaCreacion           string                 `protobuf:"bytes,9,opt,name=fecha_creacion,json=fechaCreacion,proto3" json:"fecha_creacion,omitempty"`
	FechaActualizacion      string                 `protobuf:"bytes,10,opt,name=fecha_actualizacion,json=fechaActualizacion,proto3" json:"fecha_actualizacion,omitempty"`
	Completada              bool                   `protobuf:"varint,11,opt,name=completada,proto3" json:"completada,omitempty"`
	SegundoActual           int32                  `protobuf:"varint,12,opt,name=segundo_actual,json=segundoActual,proto3" json:"segundo_actual,omitempty"` // Segundo exacto dentro del minuto (0-59)
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *HistorialReproduccion) Reset() {
	*x = HistorialReproduccion{}
	mi := &file_historial_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistorialReproduccion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistorialReproduccion) ProtoMessage() {}

func (x *HistorialReproduccion) ProtoReflect() protoreflect.Message {
	mi := &file_historial_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistorialReproduccion.ProtoReflect.Descriptor instead.
func (*HistorialReproduccion) Descriptor() ([]byte, []int) {
	return file_historial_proto_rawDescGZIP(), []int{16}
}

func (x *HistorialReproduccion) GetIdHistorial() int32 {
	if x != nil {
		return x.IdHistorial
	}
	return 0
}

func (x *HistorialReproduccion) GetIdUsuario() int32 {
	if x != nil {
		return x.IdUsuario
	}
	return 0
}

func (x *HistorialReproduccion) GetIdClase() int32 {
	if x != nil {
		return x.IdClase
	}
	return 0
}

func (x *HistorialReproduccion) GetIdTema() int32 {
	if x != nil {
		return x.IdTema
	}
	return 0
}

func (x *HistorialReproduccion) GetMinutoActual() int32 {
	if x != nil {
		return x.MinutoActual
	}
	return 0
}

func (x *HistorialReproduccion) GetDuracionTotal() int32 {
	if x != nil {
		return x.DuracionTotal
	}
	return 0
}

func (x *HistorialReproduccion) GetPorcentajeVisto() float32 {
	if x != nil {
		return x.PorcentajeVisto
	}
	return 0
}

func (x *HistorialReproduccion) GetFechaUltimaReproduccion() string {
	if x != nil {
		return x.FechaUltimaReproduccion
	}
	return ""
}

func (x *HistorialReproduccion) GetFechaCreacion() string {
	if x != nil {
		return x.FechaCreacion
	}
	return ""
}

func (x *HistorialReproduccion) GetFechaActualizacion() string {
	if x != nil {
		return x.FechaActualizacion
	}
	return ""
}

func (x *HistorialReproduccion) GetCompletada() bool {
	if x != nil {
		return x.Completada
	}
	return false
}

func (x *HistorialReproduccion) GetSegundoActual() int32 {
	if x != nil {
		return x.SegundoActual
	}
	return 0
}

type CheckpointClase struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	IdTema                  int32                  `protobuf:"varint,1,opt,name=id_tema,json=idTema,proto3" json:"id_tema,omitempty"`
	MinutoActual            int32                  `protobuf:"varint,2,opt,name=minuto_actual,json=minutoActual,proto3" json:"minuto_actual,omitempty"`
	PorcentajeVisto         float32                `protobuf:"fixed32,3,opt,name=porcentaje_visto,json=porcentajeVisto,proto3" json:"porcentaje_visto,omitempty"`
	Completada              bool                   `protobuf:"varint,4,opt,name=completada,proto3" json:"completada,omitempty"`
	FechaUltimaReproduccion string                 `protobuf:"bytes,5,opt,name=fecha_ultima_reproduccion,json=fechaUltimaReproduccion,proto3" json:"fecha_ultima_reproduccion,omitempty"`
	SegundoActual           int32                  `protobuf:"varint,6,opt,name=segundo_actual,json=segundoActual,proto3" json:"segundo_actual,omitempty"` // Segundo exacto dentro del minuto (0-59)
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *CheckpointClase) Reset() {
	*x = CheckpointClase{}
	mi := &file_historial_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointClase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointClase) ProtoMessage() {}

func (x *CheckpointClase) ProtoReflect() protoreflect.Message {
	mi := &file_historial_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointClase.ProtoReflect.Descriptor instead.
func (*CheckpointClase) Descriptor() ([]byte, []int) {
	return file_historial_proto_rawDescGZIP(), []int{17}
}

func (x *CheckpointClase) GetIdTema() int32 {
	if x != nil {
		return x.IdTema
	}
	return 0
}

func (x *CheckpointClase) GetMinutoActual() int32 {
	if x != nil {
		return x.MinutoActual
	}
	return 0
}

func (x *CheckpointClase) GetPorcentajeVisto() float32 {
	if x != nil {
		return x.PorcentajeVisto
	}
	return 0
}

func (x *CheckpointClase) GetCompletada() bool {
	if x != nil {
		return x.Completada
	}
	return false
}

func (x *CheckpointClase) GetFechaUltimaReproduccion() string {
	if x != nil {
		return x.FechaUltimaReproduccion
	}
	return ""
}

func (x *CheckpointClase) GetSegundoActual() int32 {
	if x != nil {
		return x.SegundoActual
	}
	return 0
}

type EstadisticasUsuario struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalClases        int32                  `protobuf:"varint,1,opt,name=total_clases,json=totalClases,proto3" json:"total_clases,omitempty"`                       // Clases con algún progreso
	ClasesCompletadas  int32                  `protobuf:"varint,2,opt,name=clases_completadas,json=clasesCompletadas,proto3" json:"clases_completadas,omitempty"`     // Clases al 100%
	PorcentajePromedio float32                `protobuf:"fixed32,3,opt,name=porcentaje_promedio,json=porcentajePromedio,proto3" json:"porcentaje_promedio,omitempty"` // Promedio de porcentaje visto
	MinutosVistos      int32                  `protobuf:"varint,4,opt,name=minutos_vistos,json=minutosVistos,proto3" json:"minutos_vistos,omitempty"`                 // Suma de minutos actuales registrados
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EstadisticasUsuario) Reset() {
	*x = EstadisticasUsuario{}
	mi := &file_historial_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstadisticasUsuario) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstadisticasUsuario) ProtoMessage() {}

func (x *EstadisticasUsuario) ProtoReflect() protoreflect.Message {
	mi := &file_historial_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstadisticasUsuario.ProtoReflect.Descriptor instead.
func (*EstadisticasUsuario) Descriptor() ([]byte, []int) {
	return file_historial_proto_rawDescGZIP(), []int{18}
}

func (x *EstadisticasUsuario) GetTotalClases() int32 {
	if x != nil {
		return x.TotalClases
	}
	return 0
}

func (x *EstadisticasUsuario) GetClasesCompletadas() int32 {
	if x != nil {
		return x.ClasesCompletadas
	}
	return 0
}

func (x *EstadisticasUsuario) GetPorcentajePromedio() float32 {
	if x != nil {
		return x.PorcentajePromedio
	}
	return 0
}

func (x *EstadisticasUsuario) GetMinutosVistos() int32 {
	if x != nil {
		return x.MinutosVistos
	}
	return 0
}

type AuditLog struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IdAuditoria        int32                  `protobuf:"varint,1,opt,name=id_auditoria,json=idAuditoria,proto3" json:"id_auditoria,omitempty"`
	UsuarioResponsable int32                  `protobuf:"varint,2,opt,name=usuario_responsable,json=usuarioResponsable,proto3" json:"usuario_responsable,omitempty"`
	Operacion          string                 `protobuf:"bytes,3,opt,name=operacion,proto3" json:"operacion,omitempty"`
	TablaAfectada      string                 `protobuf:"bytes,4,opt,name=tabla_afectada,json=tablaAfectada,proto3" json:"tabla_afectada,omitempty"`
	FechaEvento        string                 `protobuf:"bytes,5,opt,name=fecha_evento,json=fechaEvento,proto3" json:"fecha_evento,omitempty"`
	EstadoAnterior     string                 `protobuf:"bytes,6,opt,name=estado_anterior,json=estadoAnterior,proto3" json:"estado_anterior,omitempty"` // JSON serializado
	EstadoNuevo        string                 `protobuf:"bytes,7,opt,name=estado_nuevo,json=estadoNuevo,proto3" json:"estado_nuevo,omitempty"`          // JSON serializado
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AuditLog) Reset() {
	*x = AuditLog{}
	mi := &file_historial_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLog) ProtoMessage() {}

func (x *AuditLog) ProtoReflect() protoreflect.Message {
	mi := &file_historial_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLog.ProtoReflect.Descriptor instead.
func (*AuditLog) Descriptor() ([]byte, []int) {
	return file_historial_proto_rawDescGZIP(), []int{19}
}

func (x *AuditLog) GetIdAuditoria() int32 {
	if x != nil {
		return x.IdAuditoria
	}
	return 0
}

func (x *AuditLog) GetUsuarioResponsable() int32 {
	if x != nil {
		return x.UsuarioResponsable
	}
	return 0
}

func (x *AuditLog) GetOperacion() string {
	if x != nil {
		return x.Operacion
	}
	return ""
}

func (x *AuditLog) GetTablaAfectada() string {
	if x != nil {
		return x.TablaAfectada
	}
	return ""
}

func (x *AuditLog) GetFechaEvento() string {
	if x != nil {
		return x.FechaEvento
	}
	return ""
}

func (x *AuditLog) GetEstadoAnterior() string {
	if x != nil {
		return x.EstadoAnterior
	}
	return ""
}

func (x *AuditLog) GetEstadoNuevo() string {
	if x != nil {
		return x.EstadoNuevo
	}
	return ""
}

var File_historial_proto protoreflect.FileDescriptor

const file_historial_proto_rawDesc = "" +
	"\n" +
	"\x0fhistorial.proto\x12\thistorial\"\xe0\x01\n" +
	"\x18RegistrarProgresoRequest\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x01 \x01(\x05R\tidUsuario\x12\x19\n" +
	"\bid_clase\x18\x02 \x01(\x05R\aidClase\x12\x17\n" +
	"\aid_tema\x18\x03 \x01(\x05R\x06idTema\x12#\n" +
	"\rminuto_actual\x18\x04 \x01(\x05R\fminutoActual\x12%\n" +
	"\x0eduracion_total\x18\x05 \x01(\x05R\rduracionTotal\x12%\n" +
	"\x0esegundo_actual\x18\x06 \x01(\x05R\rsegundoActual\"\x8b\x01\n" +
	"\x19RegistrarProgresoResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12>\n" +
	"\thistorial\x18\x03 \x01(\v2 .historial.HistorialReproduccionR\thistorial\"\xbc\x01\n" +
	"\x1bActualizarCheckpointRequest\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x01 \x01(\x05R\tidUsuario\x12\x19\n" +
	"\bid_clase\x18\x02 \x01(\x05R\aidClase\x12\x17\n" +
	"\aid_tema\x18\x03 \x01(\x05R\x06idTema\x12#\n" +
	"\rminuto_actual\x18\x04 \x01(\x05R\fminutoActual\x12%\n" +
	"\x0esegundo_actual\x18\x05 \x01(\x05R\rsegundoActual\"\x8a\x01\n" +
	"\x1cActualizarCheckpointResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12:\n" +
	"\n" +
	"checkpoint\x18\x03 \x01(\v2\x1a.historial.CheckpointClaseR\n" +
	"checkpoint\"X\n" +
	"\x1cMarcarClaseCompletadaRequest\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x01 \x01(\x05R\tidUsuario\x12\x19\n" +
	"\bid_clase\x18\x02 \x01(\x05R\aidClase\"\x8f\x01\n" +
	"\x1dMarcarClaseCompletadaResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12>\n" +
	"\thistorial\x18\x03 \x01(\v2 .historial.HistorialReproduccionR\thistorial\"Y\n" +
	"\x1dObtenerCheckpointClaseRequest\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x01 \x01(\x05R\tidUsuario\x12\x19\n" +
	"\bid_clase\x18\x02 \x01(\x05R\aidClase\"\x8c\x01\n" +
	"\x1eObtenerCheckpointClaseResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12:\n" +
	"\n" +
	"checkpoint\x18\x03 \x01(\v2\x1a.historial.CheckpointClaseR\n" +
	"checkpoint\"Y\n" +
	" ConsultarHistorialUsuarioRequest\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x01 \x01(\x05R\tidUsuario\x12\x16\n" +
	"\x06pagina\x18\x02 \x01(\x05R\x06pagina\"\xb8\x01\n" +
	"!ConsultarHistorialUsuarioResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12>\n" +
	"\tregistros\x18\x03 \x03(\v2 .historial.HistorialReproduccionR\tregistros\x12#\n" +
	"\rtotal_paginas\x18\x04 \x01(\x05R\ftotalPaginas\"D\n" +
	"#ConsultarEstadisticasUsuarioRequest\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x01 \x01(\x05R\tidUsuario\"\x9a\x01\n" +
	"$ConsultarEstadisticasUsuarioResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x12B\n" +
	"\festadisticas\x18\x03 \x01(\v2\x1e.historial.EstadisticasUsuarioR\festadisticas\"Y\n" +
	"\x1dEliminarHistorialClaseRequest\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x01 \x01(\x05R\tidUsuario\x12\x19\n" +
	"\bid_clase\x18\x02 \x01(\x05R\aidClase\"P\n" +
	"\x1eEliminarHistorialClaseResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\"}\n" +
	"\x19ConsultarAuditLogsRequest\x12\x16\n" +
	"\x06pagina\x18\x01 \x01(\x05R\x06pagina\x12%\n" +
	"\x0eusuario_filtro\x18\x02 \x01(\x05R\rusuarioFiltro\x12!\n" +
	"\ftabla_filtro\x18\x03 \x01(\tR\vtablaFiltro\"\xa4\x01\n" +
	"\x1aConsultarAuditLogsResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x121\n" +
	"\tregistros\x18\x03 \x03(\v2\x13.historial.AuditLogR\tregistros\x12#\n" +
	"\rtotal_paginas\x18\x04 \x01(\x05R\ftotalPaginas\"\xdf\x03\n" +
	"\x15HistorialReproduccion\x12!\n" +
	"\fid_historial\x18\x01 \x01(\x05R\vidHistorial\x12\x1d\n" +
	"\n" +
	"id_usuario\x18\x02 \x01(\x05R\tidUsuario\x12\x19\n" +
	"\bid_clase\x18\x03 \x01(\x05R\aidClase\x12\x17\n" +
	"\aid_tema\x18\x04 \x01(\x05R\x06idTema\x12#\n" +
	"\rminuto_actual\x18\x05 \x01(\x05R\fminutoActual\x12%\n" +
	"\x0eduracion_total\x18\x06 \x01(\x05R\rduracionTotal\x12)\n" +
	"\x10porcentaje_visto\x18\a \x01(\x02R\x0fporcentajeVisto\x12:\n" +
	"\x19fecha_ultima_reproduccion\x18\b \x01(\tR\x17fechaUltimaReproduccion\x12%\n" +
	"\x0efecha_creacion\x18\t \x01(\tR\rfechaCreacion\x12/\n" +
	"\x13fecha_actualizacion\x18\n" +
	" \x01(\tR\x12fechaActualizacion\x12\x1e\n" +
	"\n" +
	"completada\x18\v \x01(\bR\n" +
	"completada\x12%\n" +
	"\x0esegundo_actual\x18\f \x01(\x05R\rsegundoActual\"\xfd\x01\n" +
	"\x0fCheckpointClase\x12\x17\n" +
	"\aid_tema\x18\x01 \x01(\x05R\x06idTema\x12#\n" +
	"\rminuto_actual\x18\x02 \x01(\x05R\fminutoActual\x12)\n" +
	"\x10porcentaje_visto\x18\x03 \x01(\x02R\x0fporcentajeVisto\x12\x1e\n" +
	"\n" +
	"completada\x18\x04 \x01(\bR\n" +
	"completada\x12:\n" +
	"\x19fecha_ultima_reproduccion\x18\x05 \x01(\tR\x17fechaUltimaReproduccion\x12%\n" +
	"\x0esegundo_actual\x18\x06 \x01(\x05R\rsegundoActual\"\xbf\x01\n" +
	"\x13EstadisticasUsuario\x12!\n" +
	"\ftotal_clases\x18\x01 \x01(\x05R\vtotalClases\x12-\n" +
	"\x12clases_completadas\x18\x02 \x01(\x05R\x11clasesCompletadas\x12/\n" +
	"\x13porcentaje_promedio\x18\x03 \x01(\x02R\x12porcentajePromedio\x12%\n" +
	"\x0eminutos_vistos\x18\x04 \x01(\x05R\rminutosVistos\"\x92\x02\n" +
	"\bAuditLog\x12!\n" +
	"\fid_auditoria\x18\x01 \x01(\x05R\vidAuditoria\x12/\n" +
	"\x13usuario_responsable\x18\x02 \x01(\x05R\x12usuarioResponsable\x12\x1c\n" +
	"\toperacion\x18\x03 \x01(\tR\toperacion\x12%\n" +
	"\x0etabla_afectada\x18\x04 \x01(\tR\rtablaAfectada\x12!\n" +
	"\ffecha_evento\x18\x05 \x01(\tR\vfechaEvento\x12'\n" +
	"\x0festado_anterior\x18\x06 \x01(\tR\x0eestadoAnterior\x12!\n" +
	"\festado_nuevo\x18\a \x01(\tR\vestadoNuevo2\x81\a\n" +
	"\x10HistorialService\x12^\n" +
	"\x11RegistrarProgreso\x12#.historial.RegistrarProgresoRequest\x1a$.historial.RegistrarProgresoResponse\x12g\n" +
	"\x14ActualizarCheckpoint\x12&.historial.ActualizarCheckpointRequest\x1a'.historial.ActualizarCheckpointResponse\x12j\n" +
	"\x15MarcarClaseCompletada\x12'.historial.MarcarClaseCompletadaRequest\x1a(.historial.MarcarClaseCompletadaResponse\x12m\n" +
	"\x16ObtenerCheckpointClase\x12(.historial.ObtenerCheckpointClaseRequest\x1a).historial.ObtenerCheckpointClaseResponse\x12v\n" +
	"\x19ConsultarHistorialUsuario\x12+.historial.ConsultarHistorialUsuarioRequest\x1a,.historial.ConsultarHistorialUsuarioResponse\x12\x7f\n" +
	"\x1cConsultarEstadisticasUsuario\x12..historial.ConsultarEstadisticasUsuarioRequest\x1a/.historial.ConsultarEstadisticasUsuarioResponse\x12m\n" +
	"\x16EliminarHistorialClase\x12(.historial.EliminarHistorialClaseRequest\x1a).historial.EliminarHistorialClaseResponse\x12a\n" +
	"\x12ConsultarAuditLogs\x12$.historial.ConsultarAuditLogsRequest\x1a%.historial.ConsultarAuditLogsResponseB\"\n" +
	"\x0fproto.historialZ\x0fproto/historialb\x06proto3"

var (
	file_historial_proto_rawDescOnce sync.Once
	file_historial_proto_rawDescData []byte
)

func file_historial_proto_rawDescGZIP() []byte {
	file_historial_proto_rawDescOnce.Do(func() {
		file_historial_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_historial_proto_rawDesc), len(file_historial_proto_rawDesc)))
	})
	return file_historial_proto_rawDescData
}

var file_historial_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_historial_proto_goTypes = []any{
	(*RegistrarProgresoRequest)(nil),             // 0: historial.RegistrarProgresoRequest
	(*RegistrarProgresoResponse)(nil),            // 1: historial.RegistrarProgresoResponse
	(*ActualizarCheckpointRequest)(nil),          // 2: historial.ActualizarCheckpointRequest
	(*ActualizarCheckpointResponse)(nil),         // 3: historial.ActualizarCheckpointResponse
	(*MarcarClaseCompletadaRequest)(nil),         // 4: historial.MarcarClaseCompletadaRequest
	(*MarcarClaseCompletadaResponse)(nil),        // 5: historial.MarcarClaseCompletadaResponse
	(*ObtenerCheckpointClaseRequest)(nil),        // 6: historial.ObtenerCheckpointClaseRequest
	(*ObtenerCheckpointClaseResponse)(nil),       // 7: historial.ObtenerCheckpointClaseResponse
	(*ConsultarHistorialUsuarioRequest)(nil),     // 8: historial.ConsultarHistorialUsuarioRequest
	(*ConsultarHistorialUsuarioResponse)(nil),    // 9: historial.ConsultarHistorialUsuarioResponse
	(*ConsultarEstadisticasUsuarioRequest)(nil),  // 10: historial.ConsultarEstadisticasUsuarioRequest
	(*ConsultarEstadisticasUsuarioResponse)(nil), // 11: historial.ConsultarEstadisticasUsuarioResponse
	(*EliminarHistorialClaseRequest)(nil),        // 12: historial.EliminarHistorialClaseRequest
	(*EliminarHistorialClaseResponse)(nil),       // 13: historial.EliminarHistorialClaseResponse
	(*ConsultarAuditLogsRequest)(nil),            // 14: historial.ConsultarAuditLogsRequest
	(*ConsultarAuditLogsResponse)(nil),           // 15: historial.ConsultarAuditLogsResponse
	(*HistorialReproduccion)(nil),                // 16: historial.HistorialReproduccion
	(*CheckpointClase)(nil),                      // 17: historial.CheckpointClase
	(*EstadisticasUsuario)(nil),                  // 18: historial.EstadisticasUsuario
	(*AuditLog)(nil),                             // 19: historial.AuditLog
}
var file_historial_proto_depIdxs = []int32{
	16, // 0: historial.RegistrarProgresoResponse.historial:type_name -> historial.HistorialReproduccion
	17, // 1: historial.ActualizarCheckpointResponse.checkpoint:type_name -> historial.CheckpointClase
	16, // 2: historial.MarcarClaseCompletadaResponse.historial:type_name -> historial.HistorialReproduccion
	17, // 3: historial.ObtenerCheckpointClaseResponse.checkpoint:type_name -> historial.CheckpointClase
	16, // 4: historial.ConsultarHistorialUsuarioResponse.registros:type_name -> historial.HistorialReproduccion
	18, // 5: historial.ConsultarEstadisticasUsuarioResponse.estadisticas:type_name -> historial.EstadisticasUsuario
	19, // 6: historial.ConsultarAuditLogsResponse.registros:type_name -> historial.AuditLog
	0,  // 7: historial.HistorialService.RegistrarProgreso:input_type -> historial.RegistrarProgresoRequest
	2,  // 8: historial.HistorialService.ActualizarCheckpoint:input_type -> historial.ActualizarCheckpointRequest
	4,  // 9: historial.HistorialService.MarcarClaseCompletada:input_type -> historial.MarcarClaseCompletadaRequest
	6,  // 10: historial.HistorialService.ObtenerCheckpointClase:input_type -> historial.ObtenerCheckpointClaseRequest
	8,  // 11: historial.HistorialService.ConsultarHistorialUsuario:input_type -> historial.ConsultarHistorialUsuarioRequest
	10, // 12: historial.HistorialService.ConsultarEstadisticasUsuario:input_type -> historial.ConsultarEstadisticasUsuarioRequest
	12, // 13: historial.HistorialService.EliminarHistorialClase:input_type -> historial.EliminarHistorialClaseRequest
	14, // 14: historial.HistorialService.ConsultarAuditLogs:input_type -> historial.ConsultarAuditLogsRequest
	1,  // 15: historial.HistorialService.RegistrarProgreso:output_type -> historial.RegistrarProgresoResponse
	3,  // 16: historial.HistorialService.ActualizarCheckpoint:output_type -> historial.ActualizarCheckpointResponse
	5,  // 17: historial.HistorialService.MarcarClaseCompletada:output_type -> historial.MarcarClaseCompletadaResponse
	7,  // 18: historial.HistorialService.ObtenerCheckpointClase:output_type -> historial.ObtenerCheckpointClaseResponse
	9,  // 19: historial.HistorialService.ConsultarHistorialUsuario:output_type -> historial.ConsultarHistorialUsuarioResponse
	11, // 20: historial.HistorialService.ConsultarEstadisticasUsuario:output_type -> historial.ConsultarEstadisticasUsuarioResponse
	13, // 21: historial.HistorialService.EliminarHistorialClase:output_type -> historial.EliminarHistorialClaseResponse
	15, // 22: historial.HistorialService.ConsultarAuditLogs:output_type -> historial.ConsultarAuditLogsResponse
	15, // [15:23] is the sub-list for method output_type
	7,  // [7:15] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_historial_proto_init() }
func file_historial_proto_init() {
	if File_historial_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_historial_proto_rawDesc), len(file_historial_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_historial_proto_goTypes,
		DependencyIndexes: file_historial_proto_depIdxs,
		MessageInfos:      file_historial_proto_msgTypes,
	}.Build()
	File_historial_proto = out.File
	file_historial_proto_goTypes = nil
	file_historial_proto_depIdxs = nil
}
