// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: historial.proto

package historial

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HistorialService_RegistrarProgreso_FullMethodName            = "/historial.HistorialService/RegistrarProgreso"
	HistorialService_ActualizarCheckpoint_FullMethodName         = "/historial.HistorialService/ActualizarCheckpoint"
	HistorialService_MarcarClaseCompletada_FullMethodName        = "/historial.HistorialService/MarcarClaseCompletada"
	HistorialService_ObtenerCheckpointClase_FullMethodName       = "/historial.HistorialService/ObtenerCheckpointClase"
	HistorialService_ConsultarHistorialUsuario_FullMethodName    = "/historial.HistorialService/ConsultarHistorialUsuario"
	HistorialService_ConsultarEstadisticasUsuario_FullMethodName = "/historial.HistorialService/ConsultarEstadisticasUsuario"
	HistorialService_EliminarHistorialClase_FullMethodName       = "/historial.HistorialService/EliminarHistorialClase"
	HistorialService_ConsultarAuditLogs_FullMethodName           = "/historial.HistorialService/ConsultarAuditLogs"
)

// HistorialServiceClient is the client API for HistorialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ──────────────────────────────────────────────
// Servicio principal de historial de reproducción
// ──────────────────────────────────────────────
type HistorialServiceClient interface {
	// Progreso y checkpoint
	RegistrarProgreso(ctx context.Context, in *RegistrarProgresoRequest, opts ...grpc.CallOption) (*RegistrarProgresoResponse, error)
	ActualizarCheckpoint(ctx context.Context, in *ActualizarCheckpointRequest, opts ...grpc.CallOption) (*ActualizarCheckpointResponse, error)
	MarcarClaseCompletada(ctx context.Context, in *MarcarClaseCompletadaRequest, opts ...grpc.CallOption) (*MarcarClaseCompletadaResponse, error)
	// Consultas
	ObtenerCheckpointClase(ctx context.Context, in *ObtenerCheckpointClaseRequest, opts ...grpc.CallOption) (*ObtenerCheckpointClaseResponse, error)
	ConsultarHistorialUsuario(ctx context.Context, in *ConsultarHistorialUsuarioRequest, opts ...grpc.CallOption) (*ConsultarHistorialUsuarioResponse, error)
	ConsultarEstadisticasUsuario(ctx context.Context, in *ConsultarEstadisticasUsuarioRequest, opts ...grpc.CallOption) (*ConsultarEstadisticasUsuarioResponse, error)
	// Limpieza
	EliminarHistorialClase(ctx context.Context, in *EliminarHistorialClaseRequest, opts ...grpc.CallOption) (*EliminarHistorialClaseResponse, error)
	// Auditoría
	ConsultarAuditLogs(ctx context.Context, in *ConsultarAuditLogsRequest, opts ...grpc.CallOption) (*ConsultarAuditLogsResponse, error)
}

type historialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHistorialServiceClient(cc grpc.ClientConnInterface) HistorialServiceClient {
	return &historialServiceClient{cc}
}

func (c *historialServiceClient) RegistrarProgreso(ctx context.Context, in *RegistrarProgresoRequest, opts ...grpc.CallOption) (*RegistrarProgresoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrarProgresoResponse)
	err := c.cc.Invoke(ctx, HistorialService_RegistrarProgreso_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historialServiceClient) ActualizarCheckpoint(ctx context.Context, in *ActualizarCheckpointRequest, opts ...grpc.CallOption) (*ActualizarCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActualizarCheckpointResponse)
	err := c.cc.Invoke(ctx, HistorialService_ActualizarCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historialServiceClient) MarcarClaseCompletada(ctx context.Context, in *MarcarClaseCompletadaRequest, opts ...grpc.CallOption) (*MarcarClaseCompletadaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarcarClaseCompletadaResponse)
	err := c.cc.Invoke(ctx, HistorialService_MarcarClaseCompletada_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historialServiceClient) ObtenerCheckpointClase(ctx context.Context, in *ObtenerCheckpointClaseRequest, opts ...grpc.CallOption) (*ObtenerCheckpointClaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObtenerCheckpointClaseResponse)
	err := c.cc.Invoke(ctx, HistorialService_ObtenerCheckpointClase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historialServiceClient) ConsultarHistorialUsuario(ctx context.Context, in *ConsultarHistorialUsuarioRequest, opts ...grpc.CallOption) (*ConsultarHistorialUsuarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarHistorialUsuarioResponse)
	err := c.cc.Invoke(ctx, HistorialService_ConsultarHistorialUsuario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historialServiceClient) ConsultarEstadisticasUsuario(ctx context.Context, in *ConsultarEstadisticasUsuarioRequest, opts ...grpc.CallOption) (*ConsultarEstadisticasUsuarioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarEstadisticasUsuarioResponse)
	err := c.cc.Invoke(ctx, HistorialService_ConsultarEstadisticasUsuario_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historialServiceClient) EliminarHistorialClase(ctx context.Context, in *EliminarHistorialClaseRequest, opts ...grpc.CallOption) (*EliminarHistorialClaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EliminarHistorialClaseResponse)
	err := c.cc.Invoke(ctx, HistorialService_EliminarHistorialClase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *historialServiceClient) ConsultarAuditLogs(ctx context.Context, in *ConsultarAuditLogsRequest, opts ...grpc.CallOption) (*ConsultarAuditLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConsultarAuditLogsResponse)
	err := c.cc.Invoke(ctx, HistorialService_ConsultarAuditLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HistorialServiceServer is the server API for HistorialService service.
// All implementations must embed UnimplementedHistorialServiceServer
// for forward compatibility.
//
// ──────────────────────────────────────────────
// Servicio principal de historial de reproducción
// ──────────────────────────────────────────────
type HistorialServiceServer interface {
	// Progreso y checkpoint
	RegistrarProgreso(context.Context, *RegistrarProgresoRequest) (*RegistrarProgresoResponse, error)
	ActualizarCheckpoint(context.Context, *ActualizarCheckpointRequest) (*ActualizarCheckpointResponse, error)
	MarcarClaseCompletada(context.Context, *MarcarClaseCompletadaRequest) (*MarcarClaseCompletadaResponse, error)
	// Consultas
	ObtenerCheckpointClase(context.Context, *ObtenerCheckpointClaseRequest) (*ObtenerCheckpointClaseResponse, error)
	ConsultarHistorialUsuario(context.Context, *ConsultarHistorialUsuarioRequest) (*ConsultarHistorialUsuarioResponse, error)
	ConsultarEstadisticasUsuario(context.Context, *ConsultarEstadisticasUsuarioRequest) (*ConsultarEstadisticasUsuarioResponse, error)
	// Limpieza
	EliminarHistorialClase(context.Context, *EliminarHistorialClaseRequest) (*EliminarHistorialClaseResponse, error)
	// Auditoría
	ConsultarAuditLogs(context.Context, *ConsultarAuditLogsRequest) (*ConsultarAuditLogsResponse, error)
	mustEmbedUnimplementedHistorialServiceServer()
}

// UnimplementedHistorialServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHistorialServiceServer struct{}

func (UnimplementedHistorialServiceServer) RegistrarProgreso(context.Context, *RegistrarProgresoRequest) (*RegistrarProgresoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegistrarProgreso not implemented")
}
func (UnimplementedHistorialServiceServer) ActualizarCheckpoint(context.Context, *ActualizarCheckpointRequest) (*ActualizarCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ActualizarCheckpoint not implemented")
}
func (UnimplementedHistorialServiceServer) MarcarClaseCompletada(context.Context, *MarcarClaseCompletadaRequest) (*MarcarClaseCompletadaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MarcarClaseCompletada not implemented")
}
func (UnimplementedHistorialServiceServer) ObtenerCheckpointClase(context.Context, *ObtenerCheckpointClaseRequest) (*ObtenerCheckpointClaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ObtenerCheckpointClase not implemented")
}
func (UnimplementedHistorialServiceServer) ConsultarHistorialUsuario(context.Context, *ConsultarHistorialUsuarioRequest) (*ConsultarHistorialUsuarioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarHistorialUsuario not implemented")
}
func (UnimplementedHistorialServiceServer) ConsultarEstadisticasUsuario(context.Context, *ConsultarEstadisticasUsuarioRequest) (*ConsultarEstadisticasUsuarioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarEstadisticasUsuario not implemented")
}
func (UnimplementedHistorialServiceServer) EliminarHistorialClase(context.Context, *EliminarHistorialClaseRequest) (*EliminarHistorialClaseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EliminarHistorialClase not implemented")
}
func (UnimplementedHistorialServiceServer) ConsultarAuditLogs(context.Context, *ConsultarAuditLogsRequest) (*ConsultarAuditLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConsultarAuditLogs not implemented")
}
func (UnimplementedHistorialServiceServer) mustEmbedUnimplementedHistorialServiceServer() {}
func (UnimplementedHistorialServiceServer) testEmbeddedByValue()                          {}

// UnsafeHistorialServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HistorialServiceServer will
// result in compilation errors.
type UnsafeHistorialServiceServer interface {
	mustEmbedUnimplementedHistorialServiceServer()
}

func RegisterHistorialServiceServer(s grpc.ServiceRegistrar, srv HistorialServiceServer) {
	// If the following call panics, it indicates UnimplementedHistorialServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HistorialService_ServiceDesc, srv)
}

func _HistorialService_RegistrarProgreso_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrarProgresoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorialServiceServer).RegistrarProgreso(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistorialService_RegistrarProgreso_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorialServiceServer).RegistrarProgreso(ctx, req.(*RegistrarProgresoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistorialService_ActualizarCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActualizarCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorialServiceServer).ActualizarCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistorialService_ActualizarCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorialServiceServer).ActualizarCheckpoint(ctx, req.(*ActualizarCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistorialService_MarcarClaseCompletada_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarcarClaseCompletadaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorialServiceServer).MarcarClaseCompletada(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistorialService_MarcarClaseCompletada_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorialServiceServer).MarcarClaseCompletada(ctx, req.(*MarcarClaseCompletadaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistorialService_ObtenerCheckpointClase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObtenerCheckpointClaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorialServiceServer).ObtenerCheckpointClase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistorialService_ObtenerCheckpointClase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorialServiceServer).ObtenerCheckpointClase(ctx, req.(*ObtenerCheckpointClaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistorialService_ConsultarHistorialUsuario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarHistorialUsuarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorialServiceServer).ConsultarHistorialUsuario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistorialService_ConsultarHistorialUsuario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorialServiceServer).ConsultarHistorialUsuario(ctx, req.(*ConsultarHistorialUsuarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistorialService_ConsultarEstadisticasUsuario_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarEstadisticasUsuarioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorialServiceServer).ConsultarEstadisticasUsuario(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistorialService_ConsultarEstadisticasUsuario_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorialServiceServer).ConsultarEstadisticasUsuario(ctx, req.(*ConsultarEstadisticasUsuarioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistorialService_EliminarHistorialClase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EliminarHistorialClaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorialServiceServer).EliminarHistorialClase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistorialService_EliminarHistorialClase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorialServiceServer).EliminarHistorialClase(ctx, req.(*EliminarHistorialClaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HistorialService_ConsultarAuditLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConsultarAuditLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HistorialServiceServer).ConsultarAuditLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HistorialService_ConsultarAuditLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HistorialServiceServer).ConsultarAuditLogs(ctx, req.(*ConsultarAuditLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HistorialService_ServiceDesc is the grpc.ServiceDesc for HistorialService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HistorialService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "historial.HistorialService",
	HandlerType: (*HistorialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegistrarProgreso",
			Handler:    _HistorialService_RegistrarProgreso_Handler,
		},
		{
			MethodName: "ActualizarCheckpoint",
			Handler:    _HistorialService_ActualizarCheckpoint_Handler,
		},
		{
			MethodName: "MarcarClaseCompletada",
			Handler:    _HistorialService_MarcarClaseCompletada_Handler,
		},
		{
			MethodName: "ObtenerCheckpointClase",
			Handler:    _HistorialService_ObtenerCheckpointClase_Handler,
		},
		{
			MethodName: "ConsultarHistorialUsuario",
			Handler:    _HistorialService_ConsultarHistorialUsuario_Handler,
		},
		{
			MethodName: "ConsultarEstadisticasUsuario",
			Handler:    _HistorialService_ConsultarEstadisticasUsuario_Handler,
		},
		{
			MethodName: "EliminarHistorialClase",
			Handler:    _HistorialService_EliminarHistorialClase_Handler,
		},
		{
			MethodName: "ConsultarAuditLogs",
			Handler:    _HistorialService_ConsultarAuditLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "historial.proto",
}
